guardian/support-dotcom-components

.eslintignore, artifact.json, bin/package.sh, package.json, riff-raff.yaml, src/cdk/app.ts, yarn.lock
@tjmw and I worked on this, leveraging a lot of the editorial-emails work.
There are a couple of fixes we'll backport to the starter-kit as well as the main build commands themselves.
=> Deployable

README.md, src/server.tsx
Default to 3030 if no PORT specified.
=> Support reading the PORT from the env

.storybook/addons.js, .storybook/config.js, .storybook/presets.js, package.json, src/components/ContributionsEpic.stories.tsx, src/components/ContributionsEpic.tsx, src/components/PrimaryButton.stories.tsx, src/components/PrimaryButton.tsx, src/server.tsx, src/utils/StorybookWrapper.tsx, src/utils/renderHtmlDocument.ts, yarn.lock
Adds Storybook to the project, as well as one story for each of the components we already have. Related to this, breaks down and exports the several parts of the preview HTML template so that the rendering of a component in Storybook visually matches that component when outputted through out service in "preview" mode (injected inside that HTML template).
NOTE: Storybook add on 'Knobs' has been enabled to help us tweak the component props in real time inside Storybook.
Because we're building components and Storybook can be a great tool for that. It will helps us develop components in isolation, as well as preview them outside of the main app.
=> Adding Storybook

src/server.tsx
We can use this to monitor availability of the service.
=> Add a very simple /healthcheck endpoint

.eslintrc.js, src/api/contributionsApi.ts
https://eslint.org/docs/rules/curly for info and motivation.
=> Require braces for if statements

src/components/PrimaryButton.tsx
Adds a couple of tweaks to the Epic button component to fix the glitches we were seeing on Frontend caused by existing styles on the page affecting our Epic.
Because it's a simple fix which will give us more time to look at styling encapsulation holistically.
=> Updates button CSS to handle Frontend glitch

src/components/PrimaryButton.tsx
This is a replica of https://github.com/guardian/contributions-service/pull/26 - as I can't seem to merge that into `master` without bringing some changes from the base branch that I already merged 🤔
=> Apply Epic button fixes for frontend

src/server.tsx
Moving the `validatePayload` function declaration above the first instance where it's called.
=> Moving JSON validation function

src/server.tsx
(We've now set NODE_ENV to 'production' on our PROD lambda so this works.)
=> Re-enable validation for non-prod

src/api/contributionsApi.test.ts
Update contributionsApi test file to make use of `cacheAsync` instead of the now deleted `memoiseAsync`.
=> Refactor contributionsApi test to use cacheAsync

src/server.tsx
Adds the updates needed on the Contributions service to be able to run the 5% DCR test and rely on the remote targeting logic.
=> Preparing for DCR 5% test

src/components/ContributionsEpic.stories.tsx, src/components/ContributionsEpic.testData.ts, src/components/ContributionsEpic.tsx
Adds support for optional `backgroundImageUrl` in Epic variant.
=> Adds support for Epic images

src/server.tsx
To improve the comparison logic.
=> Add targeting logic to comparison endpoint

package.json, yarn.lock
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html
=> Upgrade TypeScript to 3.8.3

src/lib/targeting.ts
For context, see:
https://github.com/guardian/frontend/blob/master/static/src/javascripts/projects/common/modules/commercial/contributions-utilities.js#L559
=> Remove isSensitive check as not needed

src/components/ContributionsEpic.testData.ts, src/components/ContributionsEpicTypes.ts, src/lib/targeting.test.ts, src/schemas/epicPayload.schema.json
Cleanup relating to https://github.com/guardian/contributions-service/pull/85.
=> Remove remaining isSensitive references

src/server.tsx
To build upon: https://github.com/guardian/contributions-service/pull/87 and make things a bit easier to decipher.
=> Log comparison data as JSON

src/server.tsx
For context, see https://github.com/guardian/contributions-service/pull/88.
=> Fix logging - ensure JSON

src/api/contributionsApi.testData.ts
This will be used in future PRs, but reduce the PR noise by adding here.
=> Add some test data for epic-tests.json

src/server.tsx
Generally interested in this, but should also be useful short term in understanding why impressions are higher in our current test for DCR - is it because we are making more requests, or is our impression tracking different somehow?
=> Log client name

src/server.tsx
=> Fix clientName response logging

README.md
=> Tiny tweaks to make README formatting consistent

src/errors/validationError.ts, src/middleware/errorHandling.ts, src/middleware/index.ts, src/middleware/logging.ts, src/server.tsx
As `server.tsx` has grown I've found it harder to navigate around as a lot of functionality is defined inline, some of which we don't have to touch very often.
This is a first step to refactor some functionality out into separate modules.
=> Refactor custom middlewares out of server

.eslintrc.js, src/components/ContributionsEpic.js.ts, src/components/ContributionsEpic.tsx, src/errors/validationError.ts, src/lib/cache.ts, src/lib/history.ts, src/lib/logging.ts, src/lib/validation.ts, src/lib/variants.ts, src/middleware/errorHandling.ts, src/server.test.ts, src/server.tsx
Reverts guardian/contributions-service#126
reverts the revert
=> Revert "Revert "Remove default epic and tidyup controllers""

src/lib/params.ts, src/lib/variants.test.ts, src/lib/variants.ts, src/server.tsx
https://trello.com/c/jC7zjs6x/119-epic-debug-helpers
Adds two new parameters:
?force // require a specific epic/variant, e.g. ?force=acquisitions-epic__thank_you_europe:control
?debug // return detailed info on which filters passed/failed in response
(forcing a specific variant)
(returning debug info)
=> Debug helpers

package.json, src/amp-toolbox-cors.d.ts, src/server.tsx
=> Fix cors for /amp/epic

src/components/ContributionsEpic.js.ts, src/components/modules/ContributionsEpicReminder.tsx, src/lib/env.ts, src/server.tsx
Fix some pathing issues with the `epic.js` endpoint on PROD.
Also, adds some environment helpers for this and elsewhere (`isProd`, `isDev`).
(bug fix)
=> Fix module errors

rollup.config.js
Small change to accommodate feedback on the DCR work - https://github.com/guardian/dotcom-rendering/pull/1523.
=> Namespace module globals under guardian

src/lib/env.ts, src/server.tsx
TODO before merging: set these for CODE+PROD.
This is because on AWS the host differs from the public-facing host.
=> Allow baseURL override through env var

src/server.tsx
Small fix to remove extra brace.
=> Remove extra brace in banner data endpoint

src/components/BannerTypes.ts, src/tests/banners/AusMomentContributionsBannerTest.ts, src/tests/banners/bannerSelection.tsx
And only show the Aus banner on the 2nd pageview
=> Add minPageViews to banner test config

src/lib/fetchTickerData.ts
adding caching to tickerdata call
=> adding caching to tickerdata call

src/components/BannerTypes.ts, src/schemas/bannerPayload.schema.json, src/tests/banners/bannerSelection.tsx
And use it
Fronts do not have a shouldHideReaderRevenue field
=> Make shouldHideReaderRevenue optional

src/components/modules/contributionsBanners/AusMomentContributionsBanner.tsx
This PR fixes bugs with read more/less button being hidden on screen resize increase (after initial decrease). Also generally improves consistency across different screen sizes and browser default font settings.
=> Mj improve aus banner read more

src/components/AusMomentContributionsBanner.stories.tsx, src/components/modules/contributionsBanners/AusMomentContributionsBanner.tsx
Tested with:
Screenshots from storybook:
=> Update Aus banner design for after goal is reached

src/components/modules/banners/digitalSubscriptions/digitalSubscriptionsBannerStyles.ts, src/components/modules/banners/guardianWeekly/guardianWeeklyBannerStyles.ts
Fix cursor:pointer styles on banner by adding `css` prefix to styles.
=> Fix cursor:pointer styles

src/components/modules/epics/ArticleCountOptOut.tsx
Updates article count opt-out modal to use brandAlt colour palette for engagement banners
=> Mj fix article count opt out modal colours

src/server.tsx, src/tests/ampEpic.ts
Add a US specific AMP epic as per [this card](https://trello.com/c/l6uVJHr8/2269-amp-create-a-new-us-epic-specific).c
=> Add us specific amp epic

src/tests/ampEpic.ts
Copy update for US epic (three years -> four years)
=> Update US AMP epic copy

src/tests/banners/ChannelBannerTests.ts
this was lost in the change to support subscriptions banners
=> fix banner highlightedText

src/components/modules/banners/environmentMomentBanner/components/EnvironmentMomentBannerEarth.tsx
Another hawk eye spot from Hyuna - animate the opacity all the way to 1.
=> Animate opacity all the way to 1

src/components/modules/banners/environmentMomentBanner/components/EnvironmentMomentBannerCtas.tsx, src/components/modules/banners/environmentMomentBanner/components/EnvironmentMomentSimpleBannerCtas.tsx
- update the pledge link
- update the aus link
=> Update enviroment moment banner urls

src/tests/banners/EnvironmentMomentBannerABNonSupportersTest.ts
to go live at 8:00 BST 5/10/20
=> Enable environment moment banner

src/tests/banners/bannerDeployCache.ts
while we work out what's going wrong with this
tested locally
=> hardcode contributions banner deploy times

src/tests/banners/bannerDeployCache.ts
=> Redeploy contributions banner again

src/lib/cache.ts, src/tests/banners/bannerDeployCache.ts, src/tests/banners/bannerSelection.tsx, src/tests/banners/bannerTests.ts
The issue only occurs in PROD, which suggests something to do with load
Will revert if it doesn't fix it
=> Pre-warm redeploy timestamps cache

src/lib/cache.ts, src/tests/banners/bannerDeployCache.ts, src/tests/banners/bannerTests.ts
Did not fix it
Reverts guardian/support-dotcom-components#252
=> Revert "Pre-warm redeploy timestamps cache"

src/tests/ampEpic.ts
Updates US AMP epic copy text, per request from Rachel Sturm.
=> updates US AMP epic copy

src/tests/ampEpic.ts
updates US election copy for AMP epics
=> update us election copy in amp epic

src/tests/ampEpic.ts
Updates AMP epic copy for non-US regions, as per [this Trello card](https://trello.com/c/apKsrrWQ).
=> Mj update amp epic copy for non us regions

src/tests/ampEpic.ts
=> Update us amp copy for the election

src/tests/ampEpic.ts
Updating AMP Epic text for non-US readers.
View an AMP page in CODE.
We have analytics on this messaging.
This is just a copy change and is being tested in CODE.
Storybook (fudged):
On-site:
There's a CORS error on CODE AMP that needs to be fixed on DCR at some point:
=> Updating AMP Epic text for non-US readers

src/tests/ampEpic.ts
=> Update AMP copy

src/tests/ampEpic.ts
=> Update Non-US copy for AMP

.gitignore, package.json, src/components/modules/banners/contributionsTemplate/ContributionsTemplate.tsx, src/components/modules/banners/contributionsTemplate/ContributionsTemplateBody.tsx, src/components/modules/banners/contributionsTemplate/ContributionsTemplateHeader.tsx, src/components/modules/banners/contributionsTemplate/ContributionsTemplateSupportingText.tsx, src/components/modules/banners/contributionsTemplate/ContributionsTemplateTicker.tsx, src/components/modules/banners/contributionsTemplate/ContributionsTemplateWithVisual.tsx, src/components/modules/banners/contributionsTemplate/ExampleContributionsTemplate.stories.tsx, src/components/modules/banners/contributionsTemplate/ExampleContributionsTemplate.tsx, src/components/modules/banners/contributionsTemplate/ExampleContributionsTemplateWithVisual.tsx, src/components/modules/banners/usEoyAppeal/UsEoyAppeal.stories.tsx, src/components/modules/banners/usEoyAppeal/UsEoyAppeal.tsx, src/components/modules/banners/usEoyAppeal/UsEoyAppealWithVisual.stories.tsx, src/components/modules/banners/usEoyAppeal/UsEoyAppealWithVisual.tsx, src/components/modules/banners/usEoyAppeal/components/UsEoyAppealBody.tsx, src/components/modules/banners/usEoyAppeal/components/UsEoyAppealCloseButton.tsx, src/components/modules/banners/usEoyAppeal/components/UsEoyAppealCta.tsx, src/components/modules/banners/usEoyAppeal/components/UsEoyAppealHeader.tsx, src/components/modules/banners/usEoyAppeal/components/UsEoyAppealSupportingText.tsx, src/components/modules/banners/usEoyAppeal/components/UsEoyAppealTicker.tsx, src/components/modules/banners/usEoyAppeal/components/UsEoyAppealVisual.tsx, src/components/modules/banners/usEoyAppeal/helpers/ophan.ts, src/modules.ts, src/tests/banners/UsEoyAppealBannerTest.ts, src/tests/banners/bannerTests.ts, yarn.lock
Implement the US EOY appeal banners, as per [this card](https://trello.com/c/03OZOqBC/2415-us-eoy-appeal-implement-the-banners-ui).
=> US EOY Banners

src/tests/banners/UsEoyAppealBannerTest.ts
=> Launch the US EOY appeal banners!

src/tests/banners/UsEoyAppealBannerTest.ts
=> Update ticker copy

src/components/modules/banners/utils/storybook.ts, src/tests/banners/UsEoyAppealBannerTest.ts, src/tests/banners/bannerTests.ts
It's not an A/B test, but we do still want to know the split between supporters / non-supporters
=> US EOY GT: separate test for supporters

.eslintignore, src/components/modules/banners/ausMomentContributionsBanner/AusMomentContributionsBanner.tsx, src/components/modules/banners/digitalSubscriptions/DigitalSubscriptionsBanner.tsx, src/components/modules/epics/ContributionsEpicTicker.tsx, src/lib/fetchTickerData.ts, src/lib/validation.ts, src/server.tsx
Those yellow warnings and squiggles make me sad - this PR fixes that! 
😎
=> Remove those warnings!

src/tests/epicArticleCountTest.ts
=> Add highlightedText for article count test

src/tests/epicArticleCountTest.ts
We were missing a space - not any more!
=> Fix typo in article count epic test

src/server.tsx
Turn off the separate AC test for the christmas period.
=> Turn off epic separate AC test

src/tests/banners/GlobalEoyBannerTest.ts
One character changed to fix typo
=> fix typo in banner

src/components/modules/banners/contributionsTemplate/ContributionsTemplateTicker.tsx, src/components/modules/banners/utils/storybook.ts, src/tests/banners/UsEoyAppealBannerTest.ts
Implements requested changes to US EOY banner ticker copy
=> update us eoy ticker copy

src/components/modules/banners/usEoyAppeal/components/UsEoyAppealBody.tsx
Remove extra year in US end of year banner copy
=> remove extra year

src/server.tsx
Mj prevent fastly caching view event
=> Mj prevent fastly caching view event

src/lib/ampVariantAssignments.ts
fix query param for variant assignments
=> fix query param for variant assignments

src/tests/banners/GlobalEoyBannerTest.ts
=> Update global EOY inauguration banner test name

src/tests/banners/GlobalEoyBannerTest.ts, src/tests/banners/bannerTests.ts
back to the control message
keep AC/non-AC as separate 'tests'
=> Remove global EOY banner test

src/utils/logging.ts
this was copied from DCR, where it's also wrong! I'll tell them, though it looks like they're not really using elk
=> Fix logging stage

teamcity.sh
this was missed in the recent removal of nest
=> Build prod modules

src/tests/banners/ContributionsBannerDesignTest.ts
it should be the contributions page
=> fix banner url

src/components/modules/epics/ContributionsEpic.stories.tsx, src/components/modules/epics/ContributionsEpic.tsx, src/components/modules/epics/ContributionsEpicReminder.tsx
Prefill the email address field for the epic reminder if it's provided as a prop.
=> Pre fill epic reminder email address if provided

src/server.tsx
=> Fix puzzles banner url

src/components/modules/epics/ContributionsEpicReminder.tsx, src/components/modules/epics/ContributionsEpicReminderSignedIn.stories.tsx, src/components/modules/epics/ContributionsEpicReminderSignedIn.tsx, src/components/modules/epics/ContributionsEpicReminderSignedOut.stories.tsx, src/components/modules/epics/ContributionsEpicReminderSignedOut.tsx, src/components/modules/epics/utils/reminders.ts
Remove a couple of circular dependencies:
- `ContributionsEpicReminder` -> `ContributionsEpicReminderSignedIn` -> `ContributionsEpicReminder`
- `ContributionsEpicReminder` -> `ContributionsEpicReminderSignedIn` -> `ContributionsEpicReminder`
=> Remove circular dependencies

src/lib/targeting.ts
temporarily, while we consider a more flexible strategy
=> Allow epics on football content

cfn.yaml, src/channelSwitches.ts, src/payloads.ts, src/server.test.ts
See https://github.com/guardian/support-admin-console/pull/209
=> Channel switches

package.json, src/server.ts, yarn.lock
on the response from the POST endpoints
=> Enable compression

src/payloads.ts
requested by Subs for GA tracking
=> Add prefix to header campaignCode

src/tests/epics/articleCountOptOut.ts
we want it to fall through to the tests from the tool for higher article counts
=> Set maxViews for epic AC test

src/components/modules/epics/ContributionsEpicArticleCountOptOut.tsx, src/payloads.ts, src/tests/epics/articleCountOptOut.ts
* Update the copy on the opt out ctas 
* Enable the test
=> 2nd round test of article count opt out

src/components/modules/banners/contributions/ContributionsBanner.tsx
Fix styles - I think something must have gone wrong in a rebase/merge.
=> Fix styles

src/components/modules/header/Header.stories.tsx, src/components/modules/header/Header.tsx, src/components/modules/header/HeaderSupportAgain.tsx, src/components/modules/header/HeaderWrapper.tsx, src/types/HeaderTypes.ts
- Create a wrapper function for header to prepare for Aus header
=> create header wrapper function

cfn.yaml
Give permissions to super-mode folder in s3
=> Give permissions to super-mode folder in s3

README.md
This should make it easier for people to get up and running
=> better instructions for new devs

src/components/modules/banners/ausMoment/components/AusBannerSocialShare.tsx
=> Update aus banner email share

src/channelSwitches.ts, src/payloads.ts
switch added here https://github.com/guardian/support-admin-console/pull/229
=> Super mode switch

src/lib/targeting.ts
=> Exclude football again

packages/server/package-lock.json, packages/server/src/tests/epics/epicSelection.test.ts, packages/server/src/tests/epics/epicSelection.ts, yarn.lock
Currently 'thank you' epics are included in super mode
=> Exclude supporter-epics from super mode

packages/modules/src/modules/shared/helpers/articleCountOptOut.ts
See https://github.com/guardian/automat-client-v2/blob/master/src/contributions/history.ts#L5
=> Delete articlesThisWeek when user opts out

cdk/lib/__snapshots__/dotcom-components.test.ts.snap, cdk/lib/dotcom-components.ts
=> Update threshold for 5XX alarm

packages/server/src/tests/epics/epicSelection.test.ts, packages/server/src/tests/epics/epicSelection.ts
it doesn't work properly, despite the passing tests.
It's now a tiny bit more efficient as well
=> Fix tag exclusion logic

riff-raff.yaml
For more details see [migration doc](https://docs.google.com/document/d/17M6TK4uVcMiZAHaTFSo-zahIqrA5eGaKNYU-j4BVUB0/edit) and https://github.com/guardian/support-dotcom-components/pull/516.
=> Tidy up after cdk migration

packages/modules/src/modules/banners/investigationsMoment/components/InvestigationsMomentBannerArticleCount.tsx
Tweak AC copy on investigations moment banner
=> Tweak AC copy on investigations moment banner

packages/server/src/lib/targeting.ts
Update exclusion list as per Jesse's request.
=> Update exclusion list

packages/server/src/tests/header/headerSelection.ts, packages/shared/src/config/modules.ts
Turn off support again header test
=> turn off support again header test

packages/server/src/tests/epics/articleCountByTagTest.ts
currently there's no reminder sign up cta for this test
=> Add reminder to AC by tag test

packages/server/src/tests/epics/articleCountByTagTest.ts, packages/server/src/tests/epics/articleCountByTagTestData.ts
Add special US copy for epic ac by tag test
=> Add special US copy for epic ac by tag test

packages/server/src/server.ts
for running DCR locally
Before:
After:
=> support localhost origin

packages/server/src/tests/banners/bannerDeploySchedule.test.ts, packages/server/src/tests/banners/bannerDeploySchedule.ts
while we investigate an issue with banners not going away
=> disable banner auto deploy

packages/modules/src/modules/banners/globalNewYear/components/GlobalNewYearBannerHeader.tsx, packages/modules/src/modules/banners/globalNewYear/components/GlobalNewYearBannerVisual.tsx
Implement styling feedback from @ellenwishartguardian.
=> implement designer feedback for global new year banner template

packages/server/src/tests/banners/bannerTargetingTests.ts
=> Remove subs banner deploy test

packages/modules/src/modules/epics/ContributionsEpicArticleCountAboveWithOptOut.stories.tsx, packages/modules/src/modules/epics/ContributionsEpicReminder.stories.tsx
A few epic stories are broken - they haven't been updated properly as the props have evolved.
=> Fix broken storybook

packages/server/src/tests/banners/bannerTargetingTests.ts
while I address a difference in article count behaviour in frontend vs DCR
=> Disable banner pageview test

packages/modules/src/modules/epics/ContributionsLiveblogEpic.tsx
Adds a data-cy attribute to `ContributionsLiveblogEpic`
This enables platforms using Cypress to run tests ensuring the epic appears when expected.
Because this is the [recommended best practice](https://docs.cypress.io/guides/references/best-practices#Selecting-Elements)
=> Add a `data-cy` attribute on the `ContributionsLiveblogEpic` component

packages/server/src/payloads.ts, packages/server/src/tests/epics/inEpicPayments/build.ts
=> Turn off in-epic payment test

packages/modules/src/modules/banners/guardianWeekly/GuardianWeeklyBanner.tsx
=> Update Guardian Weekly images

packages/modules/src/modules/epics/ContributionsLiveblogEpic.tsx
=> Override DCR link style in liveblog epic

packages/modules/src/modules/epics/ContributionsLiveblogEpic.stories.tsx, packages/modules/src/modules/epics/ContributionsLiveblogEpic.tsx
Replaces `platformId` with `clientName` as the property that varies when deciding which platform we are on
This is the contract that we should be working to
=> Use `clientName` to determine platform, not `platformId`

packages/server/src/tests/epics/topReaderArticleCountBadge/build.ts
Launch 'Top Reader' AC badge test
=> Launch 'Top Reader' AC badge test

packages/server/src/tests/banners/bannerSelection.ts
=> Disable scheduled banner deploys in AU

packages/server/src/tests/banners/topReaderArticleCount/index.ts
This turns on the hardcoded `TopReaderArticleCount` AB test.
=> Turn on TopReaderArticleCount hardcoded test

packages/server/src/tests/epics/environmentArticleCountTest.ts
[Details in previous PR](https://github.com/guardian/support-dotcom-components/pull/745)
=> Launch environment article count epic

packages/server/src/payloads.ts, packages/server/src/tests/epics/epicEnvironmentMoment2022.ts
Add hardcoded Epic-with-byline-and-image tests, as requested by Marketing.
[TODO]
=> Environment moment 2022 hardcoded epic tests

packages/modules/src/modules/banners/common/BannerWrapper.tsx, packages/server/src/api/epicRouter.ts, packages/shared/src/lib/reminderFields.ts
I've refactored things to make `getReminderFields` clearer, and to share it with the banner logic
=> Giving tuesday reminder cut off

packages/modules/src/modules/banners/charityAppeal/CharityAppealBanner.tsx, packages/modules/src/modules/banners/charityAppeal/CharityAppealBannerCta.tsx
This PR creates a variant of the existing Contributions banner for the Guardian Charity appeal. 
[Trello]
https://trello.com/c/cgEOY058/966-charity-appeal-new-colour-change-request
Pre->
| tablet onwards |
|----------|
|![Screenshot 2022-12-22 at 13 34 02](https://user-images.githubusercontent.com/76729591/209145469-af516d89-4e50-4b8d-8148-f47fd607cbb5.png)|
Post->
| tablet onwards |
|----------|
|![Screenshot 2022-12-22 at 13 35 20](https://user-images.githubusercontent.com/76729591/209145798-d82435f8-e73e-4bd5-b156-6b764687ad02.png)|
=> Pd charity appeal banner 2022 REVISED

packages/modules/src/modules/banners/guardianWeekly/guardianWeeklyBannerStyles.ts
=> Fix bold in GW banner

packages/modules/src/modules/banners/guardianWeekly/GuardianWeeklyBanner.tsx, packages/modules/src/modules/banners/guardianWeekly/guardianWeeklyBanner.stories.tsx, packages/modules/src/modules/banners/guardianWeekly/guardianWeeklyBannerStyles.ts
Reverts guardian/support-dotcom-components#834
=> Revert "Update GW banner "

riff-raff.yaml
this amigo recipe is also used by apps-metering
=> Ubuntu Jammy

packages/shared/src/lib/geolocation.ts
=> Update Phillipines to Philippines

packages/shared/src/lib/placeholders.test.ts, packages/shared/src/lib/placeholders.ts
=> Templates for day and date

packages/modules/src/modules/epics/BylineWithHeadshot.tsx
Currently the component flips it horizontally
=> Do not flip byline image

packages/modules/package.json, yarn.lock
`@storybook/addon-essentials` was indirectly bringing in an older version of loader-utils which dependabot flagged as vulnerable.
=> Upgrade @storybook/addon-essentials

packages/modules/src/modules/epics/ContributionsEpicSignInCta.tsx
=> update epic sign-in cta copy

yarn.lock
Flagged by snyk - https://app.snyk.io/vuln/SNYK-JS-SEMVER-3247795
=> Upgrade semver NPM packages

packages/modules/src/modules/banners/environmentMoment/EnvironmentMomentBanner.stories.tsx, packages/modules/src/modules/banners/environmentMoment/EnvironmentMomentBanner.tsx
Images imported from Grid master (1:1) to improve sharpness ->
|Size   |Tool   |URL   |
|----------|----------|----------|
|1300+|GRID|https://media.gutools.co.uk/images/f5b89e25ec6c34d18db071b9d47078d998f0501d|
|1300+|MASTER|https://media.guim.co.uk/images/f5b89e25ec6c34d18db071b9d47078d998f0501d/0_0_696_183/master/696.jpg|
| 1300+ | FASTLYIO | https://i.guim.co.uk/img/media/f5b89e25ec6c34d18db071b9d47078d998f0501d/0_0_696_183/master/696.jpg?width=696&height=183&quality=100&s=fb3c4b40daaed51bd35b5740216d43a4 |
|1140|GRID|https://media.guim.co.uk/images/9fadcec3889f15b45dc9a8177bd30e57b16494dc/
|1140|MASTER|https://media.guim.co.uk/9fadcec3889f15b45dc9a8177bd30e57b16494dc/0_0_624_179/master/624.jpg
|1140|FASTLYIO|https://i.guim.co.uk/img/media/9fadcec3889f15b45dc9a8177bd30e57b16494dc/0_0_6 …
=> Environment moment 2023 banner image improvements

packages/modules/src/modules/banners/environmentMoment/EnvironmentMomentBanner.stories.tsx, packages/modules/src/modules/banners/environmentMoment/EnvironmentMomentBanner.tsx
Images imported from Grid master (1:1) to improve sharpness using DOUBLE HEIGHT AND WIDTH ->
Grid -> https://media.gutools.co.uk/search
FastlyIO Resizer -> https://image-url-signing-service.gutools.co.uk/
1300+: [696 / 183] = [1392 / 366]
GRID : https://media.gutools.co.uk/images/3c1cb611785d3dccc2674636a6f692da1e2fcdb6
MASTER : https://media.guim.co.uk/3c1cb611785d3dccc2674636a6f692da1e2fcdb6/0_0_1392_366/master/1392.jpg
FASTLYIO : https://i.guim.co.uk/img/media/3c1cb611785d3dccc2674636a6f692da1e2fcdb6/0_0_1392_366/master/1392.jpg?width=696&height=183&quality=100&s=5935c1ae5e8cbc5d9ed616bbadb3b09e
1140:[624 / 179] = [1248 / 358]
GRID : https://media.gutools.co.uk/images/6f09850dd1bff07005c162501a95c506ee88038c
MASTER : https://media.guim.co.uk/6f09850dd1bff07005c162501a95c506ee88038c/0_0_ …
=> Environment moment 2023 banner image master quality doubled

packages/modules/src/modules/banners/aus10yrAnniversaryMoment/Aus10yrAnniversaryMomentBanner.stories.tsx, packages/modules/src/modules/banners/designableBanner/stories/DesignableBanner.stories.tsx, packages/modules/src/modules/banners/investigationsMoment/components/InvestigationsMomentBannerCtas.tsx, packages/modules/src/modules/banners/momentTemplate/stories/MomentTemplateBanner.stories.tsx, packages/server/src/lib/fetchTickerData.ts
This PR fixes a couple of minor issues which had crept into `main` and were causing the build to fail:
* A small prettier issue
* A few references to old ticker names
=> Fix the build

packages/server/src/api/bannerRouter.ts
to be merged at the end of November
=> Enable scheduled banner redeploys in the US

packages/dotcom/README.md
Heavily plagiarised from https://github.com/guardian/braze-components
With some additional notes about some issues we're having on this repo.
=> Update npm release notes

packages/modules/src/modules/banners/common/choiceCard/ChoiceCards.tsx, packages/modules/src/modules/banners/designableBanner/DesignableBanner.tsx
After our chat this is a PR to revert guardian/support-dotcom-components#1064
=> Revert "RRCP Banner header and text box widths"

packages/dotcom/.changeset/old-terms-confess.md, packages/dotcom/package.json, yarn.lock
Add zod as a peer and dev dependency to [@guardian/support-dotcom-components](https://www.npmjs.com/package/@guardian/support-dotcom-components?activeTab=dependencies) NPM package. Addresses  [issue 1052](https://github.com/guardian/support-dotcom-components/issues/1052). And follow recommendation [to pin dev dependency](https://github.com/guardian/recommendations/blob/main/npm-packages.md#pin-the-lowest-possible-version-of-peerdependencies-in-your-packages-devdependencies)
=> Add zod as peer dependency

cdk/lib/__snapshots__/dotcom-components.test.ts.snap, cdk/lib/dotcom-components.ts
migrates alarms from email to chat
=> Update alarm topic

packages/dotcom/.changeset/mean-carrots-kiss.md, packages/dotcom/tsconfig.json, packages/modules/package.json, packages/modules/src/modules/shared/ModuleWrapper.tsx, packages/modules/src/types.ts, packages/modules/tsconfig.json, packages/shared/src/types/props/banner.ts, packages/shared/src/types/props/epic.ts, packages/shared/src/types/props/header.ts, yarn.lock
Reverts guardian/support-dotcom-components#1119
=> Revert "use `"moduleResolution": "bundler”` in TypeScript"

packages/server/src/api/epicRouter.ts, packages/server/src/lib/history.test.ts, packages/server/src/lib/history.ts, packages/server/src/tests/epics/epicSelection.test.ts, packages/shared/src/types/abTests/shared.ts
This PR has changes to allow multiple tags in SDC article count logic.
=> Changes to allow multiple tags

packages/modules/src/modules/banners/designableBanner/stories/DesignableBanner.stories.tsx
Adds a new story to demonstrate animated SVGs in banners
Run storybook and go to Banners->Designable->Design Three Animated Header Image
https://github.com/guardian/support-dotcom-components/assets/99400613/d967b7e8-415e-427d-8646-0e438d0e116c
=> Add animated header image

packages/server/src/tests/epics/momentumTest.ts
Widens the audience of momentum testing to low jumps in engagement (two categories)
Unit tests should still cover this
=> Target low jumps in article momentum

packages/server/src/tests/banners/abandonedBasketTests.ts
Turn the abandoned basket test live, when we're ready to release we can merge. 
[Trello](https://trello.com/c/JDYlS0OV/507-abandoned-basket-go-live-steps)
=> 🚀 Abandoned Basket Go Live!

yarn.lock
a dependabot vulnerability
Tested in CODE
=> Upgrade ip dep

packages/dotcom/.changeset/silver-fireants-joke.md, packages/shared/src/lib/history.ts
Add new tags to the list of tags we track for WeeklyArticleHistory
=> Add new tags for tracking

packages/server/src/utils/logging.ts
we need to give "others" permission to read the file in order for the kinesis agent to pick up logs
=> Fix log file permission again

packages/dotcom/.changeset/nice-dodos-punch.md
The changeset for [this PR](https://github.com/guardian/support-dotcom-components/pull/1221).
=> feat: add changeset

cdk/lib/__snapshots__/dotcom-components.test.ts.snap, cdk/lib/dotcom-components.ts
From minimum of 3 to 6 instances
=> Scale up for US election

cdk/lib/__snapshots__/dotcom-components.test.ts.snap, cdk/lib/dotcom-components.ts
Reverts guardian/support-dotcom-components#1244
=> Revert "Scale up for US election"

src/server/bandit/banditData.ts, src/server/bandit/banditSelection.test.ts, src/server/bandit/banditSelection.ts, src/server/lib/ab.ts, src/server/roulette/rouletteSelection.test.ts, src/server/roulette/rouletteSelection.ts, src/shared/types/abTests/shared.ts
Roulette selection method
Tested in  CODE
SDC  serves both variants from this test
=> Roulette selection method

src/server/api/auxiaProxyRouter.ts
This change is the SDC companion of this DCR: https://github.com/guardian/dotcom-rendering/pull/13533
We are passing more data to the proxy for a GetTreatments call to implement extra policies. This is part of an architectural policy to move (some) gate logic from the client side to SDC.
=> auxia experiment: upgrade the proxy payload for GetTreatments

src/server/api/auxiaProxyRouter.ts, src/server/middleware/logging.ts
this will enable us to split auxia tracking requests by type, e.g. `VIEWED`
=> Log auxiaInteractionType

src/server/lib/choiceCards/defaultChoiceCardSettings.ts
=> Update choice cards copy for recurring contribution

src/server/lib/choiceCards/defaultChoiceCardSettings.ts
to match https://github.com/guardian/dotcom-rendering/pull/13940
=> Remove benefitsLabel from recurring contribution on choice cards

src/server/api/auxiaProxyRouter.ts
As a follow up of https://github.com/guardian/support-dotcom-components/pull/1360 , here we implement the logic to gracefully handle requests from Auxia and non Auxia share of the Audience. For this we make use of the `mvtIdIsAuxiaAudienceShare` function that was introduced here ( https://github.com/guardian/support-dotcom-components/pull/1359 ) and for the moment we follow the value of `should_show_legacy_gate_tmp`.
=> gate air traffic control

src/server/api/auxiaProxyRouter.ts
Tiny refactoring of the auxiaProxyRouter, moving logic away from the handler itself.
=> Introduce getTreatments for clarity
