src/server.tsx, src/utils/renderHtmlDocument.ts
Adds support for a `showPreview` parameter to be set in the request URL, indicating the user expects the response data (i.e. `{html, css}`) to be rendered and served inside a basic HTML document for previewing purposes.
The `showPreview` URL parameter is optional and doesn't require any value, neither does it check for one. Not setting the parameter will result in the default behaviour of serving a JSON response.
=> Adds support for showPreview flag

src/utils/renderHtmlDocument.ts
Extends the Preview Template to include the Guardian font faces and some basic CSS resets.
We've realised we'll most definitely need the Guardian font faces to be added to the document, and we're confident we have some very basic CSS resets already in place across Frontend and DCR.
=> Extend Preview Template

src/components/CallToAction.tsx, src/components/DefaultEpic.tsx, src/server.tsx, src/utils/renderHtmlDocument.ts
Adds a `DefaultEpic` component and serves it through the root endpoint. It's been styled for visual parity with Frontend, although making use of @guardian/src-foundations.
Because we want to serve the default epic through our service.
https://trello.com/c/ibvNCUWr/13-implement-the-default-epic-component-in-new-service
=> DefaultEpic component

riff-raff.yaml
RR complains if you provide a parameter with a default value set. This is unfortunate, but the warnings are sufficiently annoying that we should 'fix' them.
=> Remove default RR option

src/components/DefaultEpic.tsx
Quick fix to remove the top margin from the DefaultEpic component; the motivation for this is the belief the outer margins should be controlled by the platform making use of our service, rather than out service (or the components we serve) imposing any spacing rules between themselves and the other components on the platform.
=> Removes outer container top margin

src/api/contributionsApi.ts, src/server.tsx
This PR changes the way we fetch the default epic. Previously we were fetching at boot time (asynchronously) and then starting the app. This approach caused issues when deploying, I think around the fact that the `exports.handler` call was happening asynchronously. I looked into Amazon's docs but didn't quite find an approach that worked. So instead we're now lazily fetching the epic content when the request comes in (and caching the response), which simplifies the server.
Note that I've added a line to the server to kick off the async default epic request immediately, which should reduce the waiting time for the first request. However given that we're not really performance concerned at this point, maybe that's adding unnecessary complexity. Thoughts welcome!
=> Lazily fetch default epic content

src/cdk/app.ts
This gets our integration with https://github.com/guardian/cloudwatch-logs-management working, which means we now have `contributions-service` logs in ELK.
=> Add tags to lamdba

src/server.tsx
Refactors our route handlers to call the `next()` function when an exception is caught. This is then caught by an error handling middleware responsible for sending an error code/response.
To keep as much as possible of our error handling logic in the same place and avoid duplication across every route handler.
=> Refactor route handlers to use error handling middleware

src/components/ContributionsEpic.testData.ts
Simple PR to update our Epic test data with the values now agreed with Contributions team for our first A/B test.
`campaignCode: 'gdnwb_copts_memco_remote_epic_test_api'`
`abTestName: 'remote_epic_test'`
`abTestVariant: 'api'`
=> Updates test metadata with default epic tracking params

src/lib/geolocation.test.ts
As discussed in #16, [here](https://github.com/guardian/contributions-service/pull/16#discussion_r371157899).
=> Use table data for these tests

package.json, src/cdk/app.ts, yarn.lock
@tjmw and I worked on this to migrate from API Gateway REST to HTTP. 
See:
https://aws.amazon.com/blogs/compute/announcing-http-apis-for-amazon-api-gateway/
for info on this. 
The TL;DR version is:
* HTTP is simpler but still suitable for proxying to a lambda (which is what we do)
* it's considerably cheaper (1/3 the cost for the request part of API Gateways costs)  
Note, HTTP Apis are in beta at the moment so the library/interface is still subject to change. But we think the risk here is worth it.
=> API Gateway - use HTTP rather than REST

src/api/contributionsApi.ts
This will help inform our caching strategy for the content.
One thing to note: currently the console log output is visible when running jest tests, which I find really annoying and distracting! I'm going to try out some options and follow up in a separate PR to fix this, but don't want to block this change going out.
=> Log when we fetch default content

README.md, bin/package.sh, package.json, src/components/ContributionsEpic.testData.ts, src/components/ContributionsEpic.tsx, src/components/ContributionsEpicTypes.ts, src/lib/targeting.ts, src/lib/tracking.ts, src/schemas/epicPayload.schema.json, src/scripts/generate-json-schema.ts, src/server.test.ts, src/server.tsx, yarn.lock
This PR introduces a JSON schema document to illustrate the format that the `POST /epic` endpoint expects of the request body.
We also now use the schema to validate the incoming payload. If the request payload isn't the correct format then we'll return `400 Bad Request`.
Anecdotally the validation seems to increase response times by a few milliseconds, but this doesn't seem problematic.
Since this adds even more logic to `src/server.tsx` We have a refactoring to split that file up into separate concerns on another branch (but didn't want to include on this PR because it would have obscured the json schema changes).
=> Validate /epic Request Payloads with JSON Schema

src/server.tsx
In the same way it's useful to keep an eye on when we fetch the default epic content, I think it'll be useful to know how often we're reading/loading this.
=> Log when we load the JSON schema

src/server.test.ts, src/server.tsx
At the moment this is configured via a const which is hardcoded to false. I think going forward we could pull this value from configuration in parameter store (or similar) so we can toggle it per environment, but I didn't get to this today.
We discussed not enabling in prod (it does after all have a small performance penalty) but I can see it continuing to be useful in CODE and DEV, especially when integrating with the service.
Another option in the short term might be to do the validation in PROD but simply log the output (and don’t return a 400). This would allow us to gather data on whether our understanding of the input params is correct.
=> Disable JSON schema validation

src/server.tsx
I think it would be useful to see at a glance (perhaps on a dashboard or something in Kibana) the breakdown of response codes we're serving. This would allow us to spot issues faster.  This adds some logging on every request of the response code, HTTP method and path. Logging a JSON string sends the data to ELK in a structured way and allows us to query it easily.
A few requests logged on CODE:
This was all a bit more manual than I expected, so any alternative approaches/suggestions appreciated!
=> Add HTTP Response Logging

src/server.tsx
Log if this happens. The outcome will just be that the next time a request arrives we’ll attempt to fetch the content then. The function `fetchDefaultEpicContent` is lazy and caches the first successful result.
=> Catch and log a failed epic pre-fetch

src/components/ContributionsEpic.stories.tsx, src/components/ContributionsEpicTypes.ts, src/schemas/epicPayload.schema.json
This makes the `countryCode` property optional so the JSON schema doesn't fail when the value coming from the platform is `undefined`.
It will still fail if the value is `null` but I don't think we have a use case for that. In frontend, when the country cannot be fetched from localStorage, it will be inferred from the Edition, through a function that will either return a string (edition code) or `undefined`.
=> Make countryCode type optional

src/components/ContributionsEpic.tsx
The motivation is that we had a bug in sending this from Frontend. Logging non-default values will give us confidence that the fixworks when we deploy it!
See https://github.com/guardian/frontend/pull/22322 for broader context.
=> Log country code

bin/package.sh
Motivation is that this seems to update frequently, slowing deploys unnecessarily.
E.g. from recent deploy, only things that changed:
Because our cdk code is version controlled and our dependencies pinned, we don't really need to store this metadata in the cloudformation as well.
=> Exclude CDK metadata from synth output

src/api/contributionsApi.test.ts, src/api/contributionsApi.ts, src/server.tsx
Previously if the default epic content fetch failed we were caching that result, which we don't want to be doing. Only cache if we were successful. I also beefed up the tests a little to cover these scenarios.
=> Don’t cache a failed epic content fetch

src/server.tsx
We were noticing that 400/500 responses didn’t seem to be getting logged correctly. Having tested locally this improves things. So the middleware runs before the main handler, but attaches a listener to log when the request completes. This seems to do the right thing and I now see 200,
400 and 500 responses logged correctly locally.
=> Fix HTTP response code logging

src/server.tsx
I think this will be useful once we enable the targeting logic. Once this is available I'll add a graph to the Kibana dashboard to show the numbers of returned epic vs no returned epic.
=> Log whether or not we returned an epic

src/api/contributionsApi.test.ts, src/api/contributionsApi.ts, src/components/ContributionsEpic.testData.ts, src/components/ContributionsEpicTypes.ts, src/lib/memoise.ts, src/lib/variants.test.ts, src/lib/variants.ts, src/schemas/epicPayload.schema.json, src/server.tsx
**DO NOT MERGE as adds additional targeting data requirements requiring a client-lib change first.**
The aim is that platforms (initially Frontend) can send their variant (contributions) decision to us and we can log any differences. This should help us validate that our variant logic is working correctly.
I've also generalised the memoisation logic so keen on thoughts on that too!
=> Comparison endpoint to help us evaluate our variant logic

package.json, src/components/ContributionsEpic.tsx, src/components/PrimaryButton.tsx, yarn.lock
As part of the introduction of dark mode, the value of `brandYellow.dark` has to change from `#F3C100` to `#FFD900`. The value `#F3C100` is now considered "extra dark" 🌚  and has been moved further down the numeric brightness scale as a result.
We're treating this as a breaking change, and so we're going through codebases making the change for you 💁  The breaking change will go live in v0.15.0.
Note that we've made a couple of additional changes, to steer you away from some legacy naming conventions.
- Upgrade `src-foundations` to 0.14.1
- Migrate the `brandYellow` colour category to the new name, `brandAlt`
- Use the numeric colour names associated with the brightness scale instead of deprecated semantic names
=> Upgrade foundations and update colours

src/api/contributionsApi.ts, src/components/ContributionsEpicTypes.ts, src/lib/targeting.test.ts, src/lib/targeting.ts, src/lib/variants.test.ts, src/lib/variants.ts, src/server.tsx
* dynamically fetch configured test JSON (with the usual caching)
* order tests by priority
* add some extra filters (max views, is on, content type check)
* other fixes/tidups to improve tests and also output of the comparison endpoint
=> Fetch variant config and misc fixes

src/server.tsx
Minor correction as we now have view log in targeting so we don't need to pass it separately for the comparison endpoint.
=> Use view log on targeting

src/components/ContributionsEpic.tsx, src/server.tsx
As it's not possible to send undefined in JSON explicitly let's just be broad in what we accept here and then ignore cases where both expected and actual are falsy (false, null, undefined, '', etc.). At the moment these cases appear in our logs as:
comparison failed: got (undefined:undefined, want (:)
Also (separately) stop logging country code as no longer needed.
=> Ignore comparisons where both are falsy

src/lib/targeting.ts, src/lib/variants.ts
Noticed from the logging of errors. And realised we are not applying the global checks on the comparison endpoint which is obviously a problem(!).
=> Add global checks to variant logic

src/lib/targeting.test.ts, src/lib/targeting.ts
Tweaks the throttling conditions to reflect the fact that counting days between dates always starts at zero days.
This should fix some of our failed comparison errors.
=> Tweaks Epic throttling conditions

src/server.tsx
Initially I thought we need to support the existing manual tests in DCR but that is not true because:
* one of them (RemoteRenderEpicRoundTwo) is our own test
* the other (ContributionsEpicAskFourEarning) never gets called from what I can tell
If the second proves untrue, we can revisit.
But for now, I've just updated the comparison endpoint to ignore cases of our own test.
https://trello.com/c/4CxCisjn/73-support-manually-defined-tests
=> Ignore our own manual test for comparison logging

src/api/contributionsApi.test.ts, src/api/contributionsApi.ts, src/components/ContributionsEpic.stories.tsx, src/components/ContributionsEpic.testData.ts, src/components/ContributionsEpic.tsx, src/lib/variants.ts, src/server.tsx
This is in preparation for the ongoing variants work. Rework the default epic content fetch to return a Variant. The current default epic, as it appears to the user, should be unchanged (maybe this is a rare use case for adding a snapshot test?!)
=> Refactor ContributionsEpic to take a Variant

package.json, src/components/PrimaryButton.tsx, yarn.lock
Updates the Primary Button colours to use `main` and `dark` shades, as defined in the latest version of the Design System. 
Shade `200` used until now is no longer supported by the design system so we should adopt the new shades going forward.
=> Updating button colour shades

src/components/ContributionsEpic.stories.tsx, src/components/ContributionsEpic.testData.ts, src/components/ContributionsEpic.tsx, src/components/ContributionsEpicTypes.ts, src/lib/history.test.ts, src/lib/history.ts, src/lib/variants.test.ts, src/lib/variants.ts, src/schemas/epicPayload.schema.json, src/server.tsx
The types, logic and tests needed to include the article viewing history in the variant selection process. Also adds placeholder replacement for number of articles viewed in the Epic copy.
To achieve parity with Frontend, we need to track articles viewed on the platform and include this log in the Epic payload, to then be used in the variant selection logic and template rendering functions.
This effectively adds support for article history in variants and templates, although we're not yet serving Epic variants. Only using them in the variant comparison endpoint.
=> Include article viewed settings in variant checks

src/lib/variants.ts
This is what Frontend does and it appears there are real cases that expect this behaviour, though it is arguably a bug. I.e. this is the relevant test config in the wild:
```
"tagIds" : [
""
],
```
The relevant Frontend code is here:
https://github.com/guardian/frontend/blob/master/static/src/javascripts/projects/common/modules/commercial/contributions-utilities.js#L205
("any string".includes("") is always true in this case.)
=> Ignore empty string in hasTags filter

src/server.tsx
This test seems to account for a lot of our remaining comparison failures, so let's temporarily ignore it.
=> Expand list of ignored tests

src/components/ContributionsEpic.tsx
Adds styling for `<a>` tags in the Epic body (paragraphs & highlighted text). Matches Frontend styles.
Before:
After:
=> Adds styles for link tags

src/lib/variants.test.ts, src/lib/variants.ts
Replaces two variant filters `hasTags` and `hasSections` with a new one `hasSectionOrTags` that checks for for either of these in the same condition.
This is for parity with Frontend and hopefully help reduce the number of failed comparisons.
=> Add new hasSectionOrTags filter

src/components/ContributionsEpic.testData.ts, src/components/ContributionsEpicTypes.ts, src/lib/targeting.test.ts, src/lib/targeting.ts, src/schemas/epicPayload.schema.json
**EDIT: THIS IS NOW OKAY. ~~DO NOT MERGE UNTIL CLIENT LIB AND PLATFORMS UPDATED TO PASS IT.~~**
In Frontend, tests won't run on sensitive pages:
https://github.com/guardian/frontend/blob/master/static/src/javascripts/projects/common/modules/experiments/ab-core.js#L27
(Contributions tests don't override this I think so we can ignore the `shouldShowForSensitive` logic.)
I suspect this accounts for many/all of the comparison failures we have where the expected variant is undefined. These are a lot of the remaining cases.
=> Add sensitive targeting check

src/server.tsx
To exclude our recent manually defined DCR/Frontend test.
=> Update ignores for comparison endpoint

src/server.tsx
For context, see: https://github.com/guardian/frontend/pull/22452.
=> Log frontend data sent to comparison endpoint

src/components/ContributionsEpicTypes.ts, src/lib/dates.test.ts, src/lib/dates.ts, src/lib/targeting.test.ts, src/lib/targeting.ts, src/lib/variants.test.ts, src/lib/variants.ts, src/server.tsx, src/utils/withNowAs.ts
This moves the 'contributor status'  checks away from the targeting logic and into the variants logic, where they can be compared against the `userCohort` property in the test config.
This fundamentally drops the principle that Epics can only be served to non-contributors. They can effectively be served to either contributors, non-contributors or past-contributors, depending on the cohort set in the test: `AllNonSupporters`, `AllExistingSupporters`, `PostAskPauseSingleContributors` and `Everyone`. The user's cohort is determined by checking all 3 relevant targeting props: `showSupportMessaging`, `isRecurringContributor` and `lastOneOffContributionDate`.
Because sometimes we want to thank our contributors by showing them an Epic with a nice message.
=> Adds userCohort variant filter

src/server.tsx
The suspicion is that our logging service detects and interprets pure JSON differently.
(This is speculative and will revert if doesn't work.)
=> Ensure comparison error log is string, not JSON

src/server.tsx
Originally dropped in https://github.com/guardian/contributions-service/pull/88.
=> Re-add got/want key info for comparison logging

src/lib/variants.test.ts, src/lib/variants.ts
...and add some basic tests.
I noticed that we were failing comparison on a lot of cases where Frontend wanted `undefined:undefined`. These are cases where a test matches but the user does not fall into it because their MVT ID is not within the range of the test.
https://trello.com/b/w9rPL4nx/automat-q4
=> Fix user in test logic

src/lib/variants.test.ts, src/lib/variants.ts
Cohorts are not exclusive it looks like, so a user should match against multiple types of test cohort value.
This keeps things close to our current approach.
(See also: https://github.com/guardian/contributions-service/pull/96 for an alternative change that takes things closer to Frontend.)
=> Attempt user cohort fix (closer to existing)

src/api/contributionsApi.testData.ts, src/components/ContributionsEpic.stories.tsx, src/components/ContributionsEpic.testData.ts, src/components/ContributionsEpic.tsx, src/components/ContributionsEpicTypes.ts, src/lib/tracking.test.ts, src/lib/tracking.ts, src/lib/variants.test.ts, src/lib/variants.ts, src/schemas/epicPayload.schema.json, src/server.test.ts, src/server.tsx
Start dynamically selecting a test and variant (or nothing depending on the targeting logic) instead of always returning the default epic. At this stage to mostly force us to figure out any decisions we still need to make.
When an epic is returned, we now include the `abTestName`, `abVariantName`, `campaignCode` and `campaignId` in the payload (under a `meta` key) so the client can use these for tracking, e.g. sending to Ophan.
The behaviour is controlled by an environment variable `ENABLE_DYNAMIC_TESTS`. Unless this is set to `true` the old behaviour of serving the default epic will happen.
There are other elements which need to be in place to fully support this (e.g. rendering of different variant elements which we don't yet support).
For the default epic variant name, we now depend on …
=> Dynamically Select Test and Variant

src/server.tsx
This should give identical results to calling `findTestAndVariant` but it’s higher level (`buildDynamicEpic` calls `findTestAndVariant`) so will give us more confidence that we’ve got things wired up correctly.
=> Use buildDynamicEpic in the comparison endpoint

src/lib/variants.test.ts, src/lib/variants.ts, src/server.tsx
Add maxViews default when test doesn't set it.
Also, apply the max views check to the default epic as well. This should help reduce the discrepancy between impressions in the `FrontendDotcomRenderingEpicTest`test.
For Frontend reference, see:
https://github.com/guardian/frontend/blob/master/static/src/javascripts/projects/common/modules/commercial/contributions-utilities.js#L342
=> Add maxViews default

src/server.tsx
We want to be sure that the service is coming up with the same campaign values as frontend.
=> Include campaign ID and code in the comparison

src/lib/variants.test.ts, src/lib/variants.ts
This fails any test with a ticker set on any of its variants. Unless most (or all?) other test config options, this one is a property of the variant, not the test. So when we run the filter, we need to iterate through the variants and fail the whole test if it has a ticker on one of the variants. This might not be ultimately what we want, but we agreed this is a safety net and a temporary check until we have support for tickers.
=> Adds hasNoTicker filter

src/components/ContributionsEpic.js.ts, src/server.tsx, tsconfig.json
This reverts the changes recently made to the `target` value in `tsconfig` back to the initial value of `es2018` instead of `es5`. Additionally, tweaks the Epic Reminders JS code to decrease the need for es5 transpilation.
=> Revert tsconfig changes

src/lib/variants.test.ts, src/lib/variants.ts
Adds a new variants filter called `hasNoZeroArticleCount`, intended to capture an edge case where the combination of user targeting data and variants logic might allow a test to pass (user has seen sufficient articles to view that Epic) but the value used to replace the article count in the Epic copy is `0` (zero) due to all article views having been within the `periodInWeeks` defined in the test (used for targeting) but before/older than the hardcoded `52` weeks (used for template rendering).
Because we use different timeframes when finding a test/variant and when replacing the Epic placeholder, so we should have a specific check around the logic/values used for template rendering so we never serve an Epic with copy saying "...you've read 0 articles..."
The ultimate goal is to ensure we …
=> Adds hasNoZeroArticleCount variants filter

src/components/ContributionsEpic.tsx, src/lib/tracking.test.ts, src/lib/tracking.ts
This makes the primary CTA in the Epic use dynamic values if they've been set (true for configured tests), defaulting to the current values if not (true for hardcoded tests and default Epic).
=> Makes Epic primary CTA dynamic

src/lib/tracking.ts, src/lib/variants.test.ts, src/lib/variants.ts, src/server.tsx, src/tests/askFourEarning.ts, src/tests/index.ts
Adds support for hardcoded tests by sharing the same interface as configured tests, with a few extra properties. Included addition of a new variants filter `isNotExpired` to ensure expired hardcoded tests don't run.
Co-authored with @tjmw
=> Support for AskFourEarning hardcoded test

src/components/ContributionsEpic.tsx, src/lib/geolocation.test.ts, src/lib/geolocation.ts
Adds a helper function to modify the Epic CTA link to include an internationalisation segment if we know the user's country code.
This modifies the original base URL (`https://support.theguardian.com/contribute`) to be, for example, `https://support.theguardian.com/eu/contribute` when the user is in a EU country.
Because Frontend does the same and even though there's server-side redirection taking the user to a localised page, we'd rather preempt this and spare the user that unnecessary delay.
This is more of an optimisation than a functional requirement, but it was mentioned to Tom in the Contributions team who agreed this adds value.
=> Support internationalisation of Epic CTA links

src/lib/tracking.ts
At the moment this is ignored by support-frontend, but the idea is it will be read and somehow forwarded to the Data Lake (probably by being converted into an ab-test).
=> Temp flag to indicate served by the Contributions Service

jest.config.js, package.json, src/api/contributionsApi.test.ts, src/api/contributionsApi.ts, src/components/Button.tsx, src/components/ContributionsEpic.stories.tsx, src/components/ContributionsEpic.testData.ts, src/components/ContributionsEpic.tsx, src/components/EpicButtons.test.tsx, src/components/EpicButtons.tsx, src/lib/variants.ts, yarn.lock
https://trello.com/c/ZrFcJ2Ds/114-make-primary-cta-optional-in-the-epic-component
Previously if a primary CTA wasn't specified, we'd always fall back to a default. To mirror the behaviour on frontend we now:
* Omit the primary CTA if none is provided
* If a CTA _is_ provided but any of the fields (`text`, `baseUrl`) are falsy, then do fall back on defaults (in terms of `epic-tests.json` this is the difference between no `cta` data, and a `cta` with empty strings for some/all values, e.g. `cta: { text: "", baseUrl: ""}`)
Also includes an update to omit all buttons (secondary, reminder) and related furniture (container, payment methods image) if no CTA is present. This mirrors the functionality in [acquisitions-epic-buttons.js](https://github.com/guardian/frontend/blob/master/static/src/java …
=> Make Epic CTA optional

src/components/EpicButtons.test.tsx, src/components/EpicButtons.tsx
Only render the reminder button if there's no secondary CTA. This reflects the current behaviour on frontend:
https://github.com/guardian/frontend/blob/23500ccc75b297db9e11e9027f65ac3d6dc9765b/static/src/javascripts/projects/common/modules/commercial/templates/acquisitions-epic-buttons.js#L72
=> Don't render reminder button when secondary CTA present

src/lib/variants.test.ts
A bit of refactoring off the back of some PR feedback from when we implemented the variants logic. The filter tests were a bit messy and hard to read due to:
- Several assertions per test
- Lots of comments explaining things as the test structure wasn't descriptive enough
- Some test data was repeated just to be available in the right scope
This refactor tries to address all of these and generally make that file more sane and easy to reason with. All tests still passing so hopefully I didn't break anything. Might need some tests for the tests 🤔
This PR doesn't add/delete/update any tests, this is just moving things around to make more sense.
https://trello.com/c/jxolLo9O/80-refactor-variant-tests-for-readability
=> Refactoring variant filter tests for readability

package.json, yarn.lock
Previously we were relying on @emotion/css being brought in indirectly via a storybook dependency. When that storybook dependency was removed in #116 it broke things. This makes the dependency explicit.
=> Add @emotion/core to deps

.gitignore, src/lib/variants.test.ts, src/lib/variants.ts
while we test this feature: https://github.com/guardian/frontend/pull/22546
we do not want to confuse things in the analysis
=> Temporarily disable 'articles viewed' epic tests

.eslintrc.js, src/components/ContributionsEpic.js.ts, src/components/ContributionsEpic.tsx, src/errors/validationError.ts, src/lib/cache.ts, src/lib/history.ts, src/lib/logging.ts, src/lib/validation.ts, src/lib/variants.ts, src/middleware/errorHandling.ts, src/server.test.ts, src/server.tsx
* remove default epic (now that we are ready to go all variants)
* tidyup server.tsx and controllers
* fix all eslint warnings
On the second, the controllers and server.tsx have got pretty cluttered, and some of the code was a bit hard to read. In general I've tried to do things like:
* move out logic from controllers and keep them higher-level and easy to read
* rename things for clarity and concision (lengthier names the further from point of use, shorter names when scoped only to a function/used locally, etc.)
* remove or reword unnecessary comments
Much of this is subjective, but I think in this case the file needed some love/got to the point where some pruning was required.
It's probably easier to check it out and see the overall picture than review line by line - although I have …
=> Remove default epic and tidyup controllers

src/lib/variants.ts
This is a rare case where a PR builds okay, but fails when in master. Because https://github.com/guardian/contributions-service/pulls?q=is%3Apr+is%3Aclosed fails a new lint config I added and my PR had not been rebased against it.
=> Remove unused var

src/server.test.ts, src/server.tsx
See https://github.com/guardian/frontend/blob/master/static/src/javascripts/projects/common/modules/commercial/contributions-utilities.js#L349 .
https://github.com/guardian/frontend/pull/22552 depends on this.
=> Prepend epic_ to campaign ID

package.json, src/amp-toolbox-cors.d.ts, src/server.tsx, src/tests/ampDefaultEpic.ts, yarn.lock
We're adding the epic to google AMP articles.
The AMP page will request the json for the epic from the contributions-service.
To begin with we're doing the same hard-coded epic across all articles. Later on we will implement targeted epics.
The currency symbol in the epic copy is determined using the fastly geo header, so that all the client has to do is render the copy.
=> New endpoint for AMP epic json

jest.config.js, package.json, src/components/EpicButtons.test.tsx, src/factories/index.ts, src/factories/targeting.ts, src/factories/test.ts, src/factories/tracking.ts, src/factories/variant.ts, src/lib/targeting.test.ts, src/lib/tracking.test.ts, src/server.test.ts, tsconfig.json, yarn.lock
Within our test suite the test data we use is a little spread out in some cases, and sometimes requires a bit of manual piecing together to create a valid object.
This PR introduces the [fishery](https://github.com/thoughtbot/fishery) library for defining factories for common types of data. Rather than go ahead and switch over wholesale I picked a single test file and migrated that to use a new variant factory I've defined. If we like it then we can migrate other test files (either in this or a separate PR).
I think the benefits of factories are:
* There's a single place where you can go to build objects for tests
* The factories provide sensible defaults and so you only have to specify the fields you care about in your test, reducing noise
Fishery itself is built with TypeScript in mind, …
=> Start defining and using factories

src/server.tsx, src/tests/ampDefaultEpic.ts
Also define a `AMPEpic` type, a stripped down version of the standard epic test type.
This endpoint does not return tests, as the client will not be able to select a variant from a test.
=> Add CTA to AMP epic response

src/tests/ampDefaultEpic.ts
Here's how they look in support-frontend's redux store:
I'm not sure it's going to be possible to include the `referrerUrl`, but this can be investigated later
=> Add tracking params to AMP url

src/server.tsx, src/tests/ampDefaultEpic.ts
Previously we returned the full epic link url, with tracking params, as `baseUrl` (which is not a very good name for it, but I used the existing cta model).
But we want the client to be able to insert a `referrerUrl` field into the tracking params. The proper way to do this is to have `contributions-service` return the parts that make up the tracking params, and let the client construct the url query string itself.
I've left `baseUrl` in for now, but it can be removed after the migration.
=> AMP epic: return tracking params as fields

src/server.tsx
Currently we're reporting that we rendered an epic 100% of the time, since here response is always truthy. The response value here now has the relevant epic data nested under a data property already, so it's that we need to inspect to determine if an epic was "rendered" (that term might need revisiting now we're switching to the data approach).
Correct reporting of `didRenderEpic` in Kibana.
=> Fix didRenderEpic value

src/components/ContributionsEpicButtons.test.tsx, src/server.test.ts
Re-introduces factories in the epic buttons component test which were lost in a previous PR. Also migrate the server test over to using a factory for the targeting data.
DevEx happiness/consistency 👩‍💻👨‍💻
=> Re-add factories to buttons test

rollup.config.js, src/components/modules/Banner.tsx, src/lib/env.ts, src/server.tsx
This adds a minimal version of a banner slot implementation, so that reader revenue banners can start to be built out from here.  It is only designed to be served as a module following @nicl's spike. It cuts corners in several ways which will need to be addressed:
- The banner is a skeleton design, with no props
- Validation has been removed for banner requests
- Response logging has been removed
- Tracking has been ignored
- I have avoided (re)defining any types in detail that I didn't need to e.g. `DataResponse`
Right now success is enabling a banner component to start being built out both in terms of component structure and logic.
=> Beginnings of a banner component

src/api/contributionsApi.test.ts, src/lib/cache.ts, src/server.tsx, src/tests/askFourEarning.ts, src/tests/banners/bannerSelection.tsx
Checks the `engagementBannerLastClosedAt` supplied by the client and compares it against the last deploy timestamp of the banner.
The deploy timestamps are cached per region.
TODO - this stuff really needs tests
=> Check last banner deploy timestamp

src/components/AusMomentContributionsBanner.stories.tsx, src/components/modules/contributionsBanners/AusMomentContributionsBanner.tsx
Alter the way the animation was implemented. Before we were using a radial gradient and animating it through js, now we use an svg and animate the clip-path property to achieve the growing effect. Had to duplicate quite a lot of css as we're not using emotion in a way that allows for composition. 
Had to tweak the svg across the four different breakpoints in the design. As this required changing svg attributes and not css properties this had to be done by hiding/showing svg elements based on the viewport size.
mobile: 
tablet:
desktop: 
wide:
=> Tp aus moment contribs banner

src/server.tsx
We can cache the component endpoints of this service.
They update infrequently (when we deploy changes) and the client does not send any data in its request.
More info - https://docs.fastly.com/en/guides/configuring-caching#surrogate-control
=> Cache the component

src/components/modules/contributionsBanners/AusMomentContributionsBanner.tsx, src/components/modules/contributionsBanners/SunriseBackground.tsx
Adds the 'pulsing' behaviour of the sunrise animation. Also cleans up the implementation by pulling it out into a separate file and removing repitition from the css.
=> Tp aus moment banner

src/components/BannerTypes.ts, src/schemas/bannerPayload.schema.json, src/tests/banners/bannerSelection.tsx
A number of requests to the banner data endpoint are missing the `isPaidContent` field. Presumably it's `undefined` on the client. It's not clear why some pages do not have this field at all.
We're currently rejecting over 2000 requests an hour with 400s because the field is missing.
Also, the bannerSelection logic wasn't even using this field!
=> Make isPaidContent optional

src/components/modules/contributionsBanners/AusMomentContributionsBanner.tsx
There are some issues with the way the SVG scales on some devices, notably iOS/Safari. This is fixes those issues.
Before (Safari/iOS)
After
=> Bug fix: scale SVG properly

src/components/modules/contributionsBanners/AusMomentContributionsBanner.tsx, src/components/modules/contributionsBanners/SocialLinks.tsx, src/components/modules/contributionsBanners/social-links.tsx
Fix the subscriber cta layout issues on mobile. This involved making the svgs display block to remove space that the browser was adding below them. Additionally, the copy is now changed to 15px on mobile. Also did a tiny refactor to tidy up the social links component file.
=> Tp aus moment banner bug fixes

src/components/modules/contributionsBanners/AusMomentContributionsBanner.tsx, src/components/modules/contributionsBanners/SunriseBackground.tsx
Implement two of the nice to haves for the banner:
- make the read more button 15px
- fix the position of the sun at the wide breakpoint
=> Tp aus moment banner nice to haves

src/components/modules/contributionsBanners/SocialLinks.tsx
This PR updates aus moment social share copy, per [this Trello card](https://trello.com/c/IYH3pt0e/2181-update-the-social-share-copy).
=> updates social share copy in  aus moment banner links

package.json, rollup.config.js, yarn.lock
Output rollup (module) bundle sizes.
Ideally we would fail the build if we exceed a certain budget. But this is a quick starting point at least.
=> Add rollup plugin to print file sizes

src/components/ContributionsEpic.tsx, src/components/modules/ContributionsEpic.tsx
Updates the `%%COUNTRY_NAME%%` placeholder to match frontend. When this functionality was added to the contributions service it looks like we used the wrong name.
This change ensures we correctly replace the country name placeholder. We should follow up and add a final check which ensures there are no unreplaced placeholders in the final output.
=> Fix incorrect placeholder name

src/components/modules/ContributionsEpic.tsx
Small tweak after I noticed this when looking over #177.
Ensure that we check the epic heading text for unreplaced placeholders. We were checking the highlighted text twice previously.
It shouldn't be possible for readers to be served an epic with unreplaced placeholders in the title, e.g. `%%COUNTRY_NAME%%`.
It's not disastrous it a user see's a placeholder, but it looks a bit messy.
=> Check the heading for unreplaced placeholders

src/server.tsx
Fixes issue with https://github.com/guardian/contributions-service/pull/182 where banner module is not found.
=> Fix banner module path in prod

.gitignore, package.json, rollup.config.js, src/components/Lines.tsx, src/components/modules/banners/subscriptions/subscriptionsBannerStyles.ts, src/components/modules/banners/weekly/weeklyBannerStyles.ts, src/components/modules/epics/ContributionsEpicReminder.tsx, src/components/modules/epics/ContributionsEpicTicker.tsx, yarn.lock
A few changes to reduce the epic module bundle size.
Initially:
after switching away from `cjs` src imports:
after inlining `Lines` and dropping `@guardian/src-ed-lines` for now:
See above: a ~30% reduction in gzipped size.
--
For a sense of what's left see below. Note, visualizer runs pre-minification so the actual numbers are not correct; what matters is the relevant sizes here.
=> Module size improvements

src/components/modules/banners/contributions/ausMomentThankYouBanner/AusMomentThankYouBanner.tsx
Add 'hear more' secondary cta to the non supporter version of the banner
=> Add hear more link

src/tests/banners/bannerSelection.tsx
The original moment banner is no longer in use.
Note - this does not remove the banner from the codebase, for now I'm just removing it from `bannerSelection` to simplify things for this PR https://github.com/guardian/contributions-service/pull/176
=> remove AusMomentContributionsBanner from test list

src/components/modules/epics/ArticleCountOptOut.tsx, src/components/modules/epics/ContributionsEpic.testData.ts, src/components/modules/epics/ContributionsEpic.tsx, src/components/modules/epics/ContributionsEpicTypes.ts, src/factories/targeting.ts, src/lib/cookies.ts, src/lib/placeholders.test.ts, src/lib/placeholders.ts, src/lib/variants.test.ts, src/lib/variants.ts, src/schemas/epicPayload.schema.json
Implement the article view opt out for epics. Additionally, instead of never serving epics with article counts, we only prevent serving them if the user has opted out (as provided by the client). 
header mobile:
header tablet and above:
body mobile:
body tablet and above: 
highlight mobile:
highlight tablet and above:
=> Add article count opt out

src/components/modules/epics/ContributionsEpic.tsx
Essentially a mirror of [this PR](https://github.com/guardian/frontend/pull/22820). Removes the fixed height of images in epics. It is now up to the designer to pick an image with the preferred aspec ratio.
desktop:
tablet:
mobile:
=> Update epic image styles

src/components/modules/banners/ausMomentContributionsBanner/AusMomentContributionsBanner.stories.tsx, src/components/modules/banners/ausMomentThankYouBanner/AusMomentThankYouBanner.stories.tsx, src/components/modules/banners/digitalSubscriptions/DigitalSubscriptionsBanner.stories.tsx, src/components/modules/banners/guardianWeekly/guardianWeeklyBanner.stories.tsx, src/components/modules/epics/ContributionsEpic.stories.tsx, src/components/modules/epics/ContributionsEpic.testData.ts, src/components/modules/epics/ContributionsEpicTypes.ts, src/factories/tracking.ts, src/server.test.ts, src/server.tsx, src/tests/banners/DigitalSubscriptionsBannerTest.ts, src/types/BannerTypes.ts
This PR is a tidy up following these PRs:
https://github.com/guardian/frontend/pull/22828
https://github.com/guardian/dotcom-rendering/pull/1741
https://github.com/guardian/contributions-service/pull/190
I'm removing `ophanComponentId` from the `tracking` object as this was temporarily left in to account for cached components that were expecting this in their `props`.
=> Remove ophanComponentId from tracking

src/components/modules/banners/digitalSubscriptions/DigitalSubscriptionsBanner.tsx, src/components/modules/banners/digitalSubscriptions/digitalSubscriptionsBannerStyles.ts
The task was a simple copy update of the banner heading and first paragraph to match the banner that is currently live.
When I was comparing the banner to the designs, it was clear that the image sizing wasn't correct across all breakpoints and that it was a bit hard to manage, so I have refactored it to make it easier to tweak in future.
Link to [trello card](https://trello.com/c/7IpRdyye/3187-update-copy-in-digital-subscriptions-banner-on-contributions-service)
Link to [designs](https://www.figma.com/file/rvS52COKyRnNEOL91I10sn/Subscriptions-Banner---Template-designs?node-id=0%3A1) (NB: out of date copy)
=> Update digital subscriptions banner copy

src/components/modules/banners/digitalSubscriptions/digitalSubscriptionsBannerStyles.ts, src/components/modules/banners/guardianWeekly/guardianWeeklyBannerStyles.ts
When testing the `contributions-service` I noted both the `DigitalSubscriptionsBanner` and the `GuardianWeeklyBanner`'s `contentContainer` styles weren't aligned to the the grid layout used on `frontend` and `dotcom-rendering`. I've applied a fix to address that.
`border: 1px solid red;` added to show `contentContainer`
`border: 1px solid red;` added to show `contentContainer`
`border: 1px solid red;` added to show `contentContainer`
`border: 1px solid red;` added to show `contentContainer`
=> Fix minor layout issues with subs banners

src/components/modules/banners/digitalSubscriptions/DigitalSubscriptionsBanner.tsx, src/components/modules/banners/guardianWeekly/GuardianWeeklyBanner.tsx, src/lib/tracking.ts
This PR updates the `DigitalSubscriptionsBanner` and `GuardianWeeklyBanner` components in the following ways:
- 4 new click handlers have been setup in each banner: `onSubscribeClick`, `onCloseClick`, `onNotNowClick` and `onSignInClick`.
- Each click handler has been bound to the corresponding elements `onClick` event.
- Each click handler takes the `tracking` prop and using this creates a `componentClickEvent` of type `OphanComponentEvent`, using the newly introduced function `createClickEventFromTracking` in `tracking.ts`.
- The `componentClickEvent` is then passed to the prop `submitComponentEvent` introduced in https://github.com/guardian/contributions-service/pull/196, which triggers a call to `Ophan`.
=> Add Ophan Tracking to Subscriptions Banners 

src/lib/variants.ts
It's currently ignoring the 'minimum article views' setting
=> enable ArticleViewedSettings

src/components/modules/banners/digitalSubscriptions/digitalSubscriptionsBannerStyles.ts, src/components/modules/banners/guardianWeekly/guardianWeeklyBannerStyles.ts
Whilst testing on firefox I found a layout issue with an oversized Guardian logo, this PR fixes that, I've tested across multiple browsers and this seems OK now.
**Before**
**After**
=> Subscriptions banners: Fix layout on firefox

src/components/modules/epics/ContributionsEpicButtons.tsx
We allow a secondary CTA in the epic.
For the primary CTA we automatically add tracking params for use by support.theguardian.com.
We do not do this for the secondary CTA because it has always been used for linking to articles on theguardian.com.
However, we are now testing linking to /subscribe and /contribute in the epic, and so it is necessary for the secondary CTA to have tracking params _only if_ it is linking to /contribute or /subscribe
**E.g. linking to article (no tracking is added):**
**E.g. linking to /subscribe (tracking is added):**
=> Add tracking params to secondary CTA

src/components/modules/banners/digitalSubscriptions/DigitalSubscriptionsBanner.tsx, src/components/modules/banners/digitalSubscriptions/digitalSubscriptionsBannerStyles.ts, src/components/modules/banners/guardianWeekly/GuardianWeeklyBanner.tsx, src/components/modules/banners/guardianWeekly/guardianWeeklyBannerStyles.ts
Whilst testing the banners I found the cursor wasn't the pointer on our CTA button and Sign In link on both the `DigitalSubscriptionsBanner` and the `GuardianWeeklyBanner`, this PR fixes that.
=> Use cursor:pointer on buttons in subs banners

src/components/modules/banners/digitalSubscriptions/digitalSubscriptionsBannerStyles.ts, src/components/modules/banners/guardianWeekly/guardianWeeklyBannerStyles.ts
The curly braces were unnecessary and prevented the build from completing on Teamcity, although validation passed on CI, and the build worked locally.
=> Fix cursor:pointer styles take 2

src/components/modules/banners/digitalSubscriptions/DigitalSubscriptionsBanner.tsx, src/components/modules/banners/guardianWeekly/GuardianWeeklyBanner.tsx
Since the recent switch to `@emotion/core` className shouldn't be used anymore, we should use the `css` prop instead.
=> Switch from className to css

babel.config.json
Restore preset-env for modules to fix experience for IE11 and other older browsers.
=> Restore preset-env

.gitignore, rollup.config.js, src/lib/placeholders.test.ts, src/lib/placeholders.ts
Various IE11 fixes :(
Browserstack. Remember to disable sourcemaps.
IE11 renders the epic okay.
=> More ie 11 fixes

src/tests/ampDefaultEpic.ts
- remove deprecated baseUrl field (unused by the client)
- update campaign code
- update copy
=> Update AMP epic

src/lib/variants.ts
Frontend equivalent: https://github.com/guardian/frontend/pull/22908
We're still updating this manually for now.
Also, we're not currently showing any reminder in DCR because there is no default. This PR adds a default reminder, with a cut off.
Before clicking:
After submitting:
Request:
=> Add epic reminder

src/components/modules/banners/contributions/ContributionsBannerStyles.ts
Fix banner overflow bug at 375-437px as per [this card](https://trello.com/c/87i425hX/2240-fix-dcr-banner-on-mobile)
original:
fix:
=> Change breakpoint to mobileLandscape

src/tests/banners/bannerSelection.tsx
Currently we put the user into the first variant.
Now that we're going to be running actual A/B tests we need to assign a variant based on the MVT cookie value
As with https://github.com/guardian/ab-testing/blob/d908567fa95d113a01f915c319ed27268e394eb1/packages/ab-core/src/core.ts#L62
=> Select variant using MVT cookie

src/components/modules/epics/ContributionsEpicReminder.tsx, src/components/modules/epics/ContributionsEpicTypes.ts, src/lib/env.ts, src/lib/history.ts, src/lib/variants.ts, src/schemas/bannerPayload.schema.json, src/tests/banners/ContributionsBannerTests.ts, src/tests/banners/bannerSelection.test.ts, src/tests/banners/bannerSelection.tsx, src/types/BannerTypes.ts, src/types/shared.ts
The banner tool sends an `articlesViewedSettings` field for restricting who is put in a test based on how many articles they have viewed.
This PR ensures the user's `weeklyArticleHistory` is correct if a test has the `articlesViewedSettings` field.
Moved `ArticlesViewedSettings` and `WeeklyArticleHistory` into a `shared.ts` file as they are used by epic + banner.
TODO:
=> Use articlesViewedSettings in banner tests

src/lib/params.ts, src/server.tsx, src/tests/banners/bannerSelection.test.ts, src/tests/banners/bannerSelection.tsx
We already have this for epics.
The client can add this to the url: `?force=test-name:variant-name`.
=> Allow client to force banner variant

src/components/modules/banners/contributions/ContributionsBanner.tsx, src/components/modules/banners/contributions/ContributionsBannerStyles.ts, src/components/modules/epics/ArticleCountOptOut.tsx, src/components/modules/epics/ContributionsEpic.tsx, src/lib/placeholders.test.ts, src/lib/placeholders.ts, src/lib/placeholders.tsx, src/lib/replaceArticleCount.tsx, src/server.tsx, src/tests/banners/ContributionsBannerTests.ts, src/types/BannerTypes.ts, src/types/shared.ts
We already exclude clients from tests based on their article view count.
This PR replaces the %%ARTICLE_COUNT%% template with the user's article count.
It re-uses the `replaceArticleCount` function from the epic's implementation of the same feature.
Also, renamed `header` -> `heading` for consistency with the banner tool (and the epic).
The following screenshot shows the count in the heading, body, and highlighted text parts of the banner:
Also, moved the popup above the link for banner:
But not for epic:
=> Display article count in contributions banner

src/components/modules/banners/digitalSubscriptions/DigitalSubscriptionsBanner.tsx, src/components/modules/banners/digitalSubscriptions/digitalSubscriptionsBannerStyles.ts
This PR update the Digital Subscriptions Banner's copy. It's pretty straightforward, I had to add some `padding-right` of `35px` to the `heading` styles, this prevents the heading copy running into the close button (which is `position: absolute`), `35px` is the width/height of this button.
Trello: https://trello.com/c/diKaVILO/3278-ds-banner-copy-update
=> Update the Digital Subscriptions Banner's copy

rollup.config.js, src/components/modules/banners/contributions/ContributionsBanner.tsx, src/components/modules/banners/contributions/ContributionsBannerStyles.ts, src/components/modules/epics/ArticleCountOptOut.tsx, src/tests/banners/ContributionsBannerTests.ts
The css change ensures that the text aligns with the article body in frontend (it wasn't required for DCR).
https://github.com/guardian/frontend/pull/22993
Edit: I've removed the feature that allows the user to close the popup if they click elsewhere on the page. It doesn't work with frontend because of shadow dom, and the fix is fiddly and will not work on all browsers.
=> Enable banner for frontend

.vscode/settings.json, src/components/modules/banners/digitalSubscriptions/DigitalSubscriptionsBanner.stories.tsx, src/components/modules/banners/digitalSubscriptions/DigitalSubscriptionsBanner.tsx, src/components/modules/banners/guardianWeekly/GuardianWeeklyBanner.tsx, src/components/modules/banners/guardianWeekly/guardianWeeklyBanner.stories.tsx, src/tests/banners/DigitalSubscriptionsBannerTest.ts, src/tests/banners/GuardianWeeklyBannerTest.ts
This adds the ability to pass heading and message copy as props to the Digital Subscriptions and Guardian Weekly banners, so their content can be managed via support-admin-console.
The CTA text remains hard-coded as it needs to be different at different breakpoints- we'll look at adding this to support-admin-console in future.
In CODE, changes made to the copy of any test variant which is using the Digital Subscriptions or Guardian Weekly template [here](https://support.code.dev-gutools.co.uk/) should be visible in the correct template on dotcom CODE.
Currently the second banner channel only gets retrieved on CODE. I've updated the existing hard-coded tests in src/tests/banners for the Digital Subs and Weekly banners to include the current heading and message copy to be passed as props …
=> Allow subs banners to accept content via props

package.json, src/lib/cache.test.ts, src/lib/cache.ts
We cache some data in memory, e.g. the epic and banner test data from the tools.
Currently we use `node-cache`. When a cached value expires it becomes `undefined`. Any reads will then re-trigger the loading function.
This is not appropriate for this server because we receive thousands of client requests per minute, and so if there is a delay in refreshing the cache then the server will attempt to make a request for the data for each incoming client request.
I suspect this is the cause of the intermittent problems we've been having, where a server becomes unable to make new http requests for a time (possibly because it reaches the open files limit), e.g.:
I've instead written a custom cache which periodically refreshes the value, but will continue to serve a stale value until it can be …
=> Re-implement cache

src/components/modules/banners/digitalSubscriptions/DigitalSubscriptionsBanner.tsx, src/components/modules/banners/digitalSubscriptions/digitalSubscriptionsBannerStyles.ts
This PR is about improving [cumulative layout shift](https://web.dev/cls/) (CLS) on the Digital Subs Banner. We can see in the filmstrip of the page loading that the text of the banner moves up when the packshot eventually loads.
This type of "layout shift" is pretty standard behaviour, and only this year did browsers roll out a new CSS feature to address it. This is explained [on web.dev](https://web.dev/optimize-cls/#modern-best-practice), and this PR is basically an implementation of their recommended solution.
Google scores pages based on CLS and 2 other metrics and uses that score to rank search results. Google calls this set of metrics "Core Web Vitals".
On July 29th, dotcom rendering started rendering reader revenue banners for the first time. And our Core Web Vitals for mobile web …
=> Subscriptions banner: Make space for packshot to avoid reflow on image load

src/components/modules/banners/contributions/ContributionsBanner.tsx
Fix some issues with whitespace in the contributions banner. This is coming from [this card](https://trello.com/c/muzZ8j5M/2281-epic-banner-manager-parent-card-of-bugs-and-fixes). It was reported as a bug with the banner manager, but I think it makes sense to fix it here. A user could easily leave some trailing whitespace in the tool without realising it.
=> Trim whitespace from tool and add it manually between sections

src/components/modules/banners/digitalSubscriptions/DigitalSubscriptionsBanner.tsx, src/components/modules/banners/digitalSubscriptions/digitalSubscriptionsBannerStyles.ts
In this PR https://github.com/guardian/support-dotcom-components/pull/231 we made a change to reserve space for the packshot image on the DigitalSubscriptionsBanner to avoid reflow on image load. We did this by adding a `padding-bottom` to the `packShot` element which wrapped the `<img>`. 
After releasing this issue an was raised by @jfsoul who had seen the `packshot` elements padding was unnecessarily high. This is because The `padding-bottom` on the `packShot` element is calculated relative to the width of it's containing element. In this case the containing element `bottomRightComponent` was wider than the image area. To resolve this we need an additional containing element around the `packshot` element, this new `packShotContainer` is the width of the image, so the `padding-bottom` …
=> Fix DigitalSubscriptionsBanner packshot issues

src/components/modules/banners/environmentMomentBanner/EnvironmentMomentBanner.tsx
Nothing slips by Hyuna! Now the close button is just 20px from the top from tablet onwards
=> Tweak close button position

src/components/modules/banners/contributions/ContributionsBanner.tsx, src/components/modules/banners/contributions/ContributionsBannerStyles.ts
Fix the aligment of the roundel and close button on the contributions banner as per [this card](https://trello.com/c/sjHX5sK7/2274-banner-design-bug-the-g-and-x-buttons-are-too-close-together). Also make some general tweaks to get everthing aligned better to the Guardian's grid. Also, fix the heading size on mobile (was slightly larger than the rest of the text).
TODO
- test in frontend
mobile
mobile landscape
tablet
desktop
leftcol
wide
=> Realign roundel and close and tweak heading size

src/lib/cache.test.ts, src/lib/cache.ts
The cache has retry logic if an attempt fails.
But this does not apply to the initial request. This PR ensures it retries if the initial request fails as well.
Also increased the retry period to 20 seconds to avoid making things worse.
It's possible this is the cause of the problems we're having with the banner deploy timestamps in PROD.
(If so, then we still need to establish why it's failing on the initial request)
=> handle failure of initial fetch in cache

src/components/modules/banners/ausMomentThankYouBanner/AusMomentThankYouBanner.stories.tsx, src/components/modules/banners/ausMomentThankYouBanner/AusMomentThankYouBanner.tsx, src/components/modules/banners/contributions/ContributionsBanner.tsx, src/components/modules/banners/digitalSubscriptions/DigitalSubscriptionsBanner.stories.tsx, src/components/modules/banners/digitalSubscriptions/DigitalSubscriptionsBanner.tsx, src/components/modules/banners/environmentMomentBanner/components/EnvironmentMomentBannerCtas.tsx, src/components/modules/banners/environmentMomentBanner/components/EnvironmentMomentSimpleBannerCtas.tsx, src/components/modules/banners/guardianWeekly/GuardianWeeklyBanner.tsx, src/components/modules/epics/ContributionsEpicButtons.tsx, src/lib/tracking.test.ts, src/lib/tracking.ts
Make a couple of fixes to links in epics/banners:
- update all banner links to the landing page to add region id if it's present - it saves a redirect!
- only add tracking params and region if the url is to the lp
- handle the case where the url in the tool already has a query string
=> Fix links in banners/epics

src/components/modules/banners/digitalSubscriptions/digitalSubscriptionsBannerStyles.ts
This fixes the height of the new digital subscriptions banner at the mobile breakpoint; it was previously taking up most of or the entirety of a user's screen.
**Before**
**After**
=> DS Editions banner mobile styling fix

src/tests/banners/bannerDeployCache.ts
Similarly to #249 this PR hardcodes the banner deploy times to 06th October 2020 to force a redeploy.
=> Hard code subscription banner deploy time

src/tests/banners/bannerDeployCache.ts
The endpoint we're currently using is behind some complicated caching.
This means the existing redeploy tool isn't working reliably.
Instead, I've moved the files into our own s3 bucket.
This service now requests the timestamps direct from there.
I've put it in the public bucket for simplicity (it's not secret)
Eventually this can be driven by a page in support-admin-console
=> get banner deploy times from s3

src/lib/cache.ts, src/tests/banners/bannerDeployCache.ts, src/tests/banners/bannerTests.ts
Bringing this change back, as it's best to fetch the data ASAP before requests start coming in
=> Cache warming

src/components/ResponsiveImage.tsx, src/components/modules/banners/digitalSubscriptions/DigitalSubscriptionsBanner.stories.tsx, src/components/modules/banners/digitalSubscriptions/DigitalSubscriptionsBanner.tsx, src/components/modules/banners/digitalSubscriptions/digitalSubscriptionsBannerStyles.ts, src/utils/StorybookWrapper.tsx
Adjusts the mobile styles further to reduce height on mobile, and adds a ResponsiveImage component in order to show different versions of the packshot at different breakpoints. Also adds a utility Storybook component to pin banners to the bottom of the iframe, which helps with device testing.
On iPhone 6, iOS 11
**Before**
**After**
=> Further Editions DS banner fixes for mobile

custom-cfn.yaml, nest.json
With nest, we have to provide an additional cloudformation stack for any additional features like permissions.
This PR make it possible for dotcom-components to fetch private s3 files for the banner deploy timestamps
=> custom cfn for s3 permission

Dockerfile, package.json, src/tests/banners/DigitalSubscriptionsBannerTest.ts, src/tests/banners/GuardianWeeklyBannerTest.ts, src/tests/banners/bannerDeployCache.ts, src/tests/banners/bannerSelection.test.ts, src/tests/banners/bannerSelection.tsx, src/tests/banners/bannerTest.test.ts, src/utils/S3.ts
Tool: https://github.com/guardian/support-admin-console/pull/164
We now store the timestamps in 2 files, for channel1 and channel 2.
These files are private and maintained by the tool
=> Fetch new banner deploy timestamps 

src/components/modules/banners/digitalSubscriptions/DigitalSubscriptionsBanner.tsx, yarn.lock
This PR introduces an Australian variant of the Digital Subs banners packshot:
**Australian variant (mobile, tablet and desktop)**
Mobile...
Tablet...
Desktop...
**Rest of World variant (mobile, tablet and desktop)**
Mobile...
Tablet...
Desktop...
=>  Australian variant of the Digital Subs banners packshot

src/components/modules/banners/environmentMomentBanner/EnvironmentMomentBanner.tsx, src/components/modules/banners/environmentMomentBanner/components/EnvironmentMomentBannerBody.tsx, src/components/modules/banners/environmentMomentBanner/components/EnvironmentMomentBannerCtas.tsx, src/components/modules/banners/environmentMomentBanner/components/EnvironmentMomentBannerHeader.tsx
Update the environment moment banner as per [this card](https://trello.com/c/5EcIi6Xo/2330-update-environment-moment-banner). We've changed the body + header copy, plus added some extra spacing between the paragraphs and the header lines.
mobile non-supporter
mobile supporter
tablet non-supporter
tablet supporter
desktop non-supporter
desktop supporter
wide non-supporter
wide supporter
=> Update the environment moment banner

src/components/modules/banners/digitalSubscriptions/digitalSubscriptionsBannerStyles.ts
The digital subscriptions banner has two packshot images, one used at the breakpoint `until.tablet` (w400px x h240px) and the other used at the breakpoints `from.tablet`(w500px x h407px). 
In `digitalSubscriptionsBannerStyles.ts` we use the image dimensions to reserve space at the correct aspect-ratio for the image until it loads. However before this PR we were only using the dimensions of the image used at the breakpoints `until.tablet`. This meant at the breakpoints `from.tablet` and up the aspect-ratio reserved for the image-container wasn't the correct size, and was in-fact too short, meaning the image's width was automatically restricted by the shortness of the image-container. This resulted in the packshot looking short and narrow...
This PR fixes that by using the correct …
=> Fix packshot on Digital Subs Banner at Tablet and above

src/tests/banners/DefaultContributionsBannerContent.ts, src/tests/banners/DefaultContributionsBannerTest.ts, src/tests/banners/bannerTests.ts
Deprecate Google Sheets for engagement banner copy, per [this Trello card](https://trello.com/c/Cx2HmtOJ/2276-deprecate-both-google-sheets-for-engagement-banner).
=> Deprecate Google Sheets for engagement banner copy

src/components/modules/banners/guardianWeekly/GuardianWeeklyBanner.tsx, src/components/modules/banners/guardianWeekly/guardianWeeklyBanner.stories.tsx, src/components/modules/banners/guardianWeekly/guardianWeeklyBannerStyles.ts, src/tests/banners/DigitalSubscriptionsBannerTest.ts, src/tests/banners/GuardianWeeklyBannerTest.ts, src/tests/banners/bannerSelection.test.ts, src/tests/banners/bannerTest.test.ts, yarn.lock
This is part of a larger piece of work to update the Guardian Weekly brand across the support site.
[Trello card](https://trello.com/c/1eR4UOQi/3360-gw-banner-updates)
**~We need to test the alignment of this banner against dcr before merging it in~**
=> Guardian Weekly brand refresh: banner

src/components/modules/epics/ContributionsEpicButtons.tsx, src/components/modules/epics/ContributionsEpicReminder.tsx, src/lib/cookies.ts, src/lib/reminderFields.test.ts, src/lib/reminderFields.ts, src/lib/variants.ts, yarn.lock
Implements the client-side logic for pre-contributions reminders, as per [this Trello card](https://trello.com/c/jrnqkXSl/2315-implement-the-pre-contribution-reminder-as-a-proper-feature-no-expiry-date). 
- If the selected Epic variant doesn't have a secondary CTA, the reminder button will be displayed instead.
- If the current date is before the 20th, the reminder will be set for the following month.
- If the current date is on, or after, the 20th, the reminder will be set for the month after next.
- If the user has a reminder set, they won't see a reminder button again until after they receive the email.
- Reminder emails will be sent on the 19th of each month, this is to differentiate them from post-contribution reminders (sent on the 15th of the month).
=> Mj implement pre contrib reminder

src/server.tsx, src/tests/banners/DigitalSubscriptionsBannerTest.ts, src/tests/banners/GuardianWeeklyBannerTest.ts, src/tests/banners/bannerSelection.test.ts, src/tests/banners/bannerTest.test.ts, src/types/BannerTypes.ts
When we first started using this Banner service we wanted to switch the Subscriptions Banners on/off via a switch in the Frontend admin tools. When the switch was ON we use the service, and when the switch was OFF we'd revert back to the old banners in frontend and not serve any subs banners from the service. The service has been running for a number of months now and this switch is no longer necessary.
This PR is the first step in removing it. The PR updates the `canRun` function in the `DigitalSubscriptionsBannerTest.ts` and `GuardianWeeklyBannerTest.ts` files to no longer check that whether this switch is turned ON. Peviously if the switch was OFF `canRun` would `return false;`.
The next steps are to stop sending the switch value un the payload from `frontend` and `dotcom-rendering`, …
=> Stop checking switches.remoteSubscriptionsBanner in Subs Banners canRun

src/components/modules/epics/ContributionsEpicReminder.tsx
Before this PR, the `reminderDateAsString` field is always prepended with the preposition "in", e.g. "Remind me in May". However, we want to use `reminderDateAsString="on Giving Tuesday"`. This then leads to the unfortunate "Remind me in on Giving Tuesday". To tackle this for now, we only add "in" if the string doesn't already start with "in" or "on". 
`reminderDateAsString="May"`
`reminderDateAsString="on Giving Tuesday"`
=> Update preposition handling

src/lib/reminderFields.ts, src/lib/variants.ts
Add a special pre-contribution reminder for the US EOY appeal
in the US, before 29/11
else
=> DO NOT MERGE: Add special US pre contribution reminder

src/server.tsx, src/tests/ampEpic.ts, src/tests/ampTicker.ts
Implements the logic and types for returning ticker data along with existing AMP epic data, for use with DCR AMP articles.
[See the related PR on DCR](https://github.com/guardian/dotcom-rendering/pull/2029)
=> Mj implement ticker for amp epics

src/components/modules/epics/ContributionsEpicReminder.tsx
Update the copy in the pre-contribution reminder, as per [this card](https://trello.com/c/VDVEcAbq/2406-update-the-reminders-copy-to-advertise-the-fact-were-going-to-send-up-to-2-emails-from-now)
=> Update pre-contribution reminder copy

src/lib/geolocation.ts, src/server.tsx, src/tests/amp/ampEpic.ts, src/tests/amp/ampEpicModels.ts, src/tests/amp/ampEpicTests.test.ts, src/tests/amp/ampEpicTests.ts
We now have a tool for configuring AMP epics.
This PR makes dotcom-components poll this configuration.
For now it only supports targeting by country.
I've left the hard-coded tests in as a fallback.
=> AMP epic: fetch configuration from the tool

src/tests/amp/ampEpicModels.ts, src/tests/amp/ampEpicTests.test.ts, src/tests/amp/ampEpicTests.ts, src/tests/amp/ampTicker.ts, src/tests/getAmpTicker.ts
- Uses the `tickerSettings` field if present.
- Changes the `AMPTicker` type, which is returned to the client. Now we simply tell the client what text to put in each of the 4 positions. We want to keep things simple in the client on AMP.
- Also refactored things a bit to use the existing `fetchTickerDataCached` function
=> AMP epic: get ticker settings

src/components/modules/banners/ausMomentThankYouBanner/AusMomentThankYouBanner.stories.tsx, src/components/modules/banners/ausMomentThankYouBanner/AusMomentThankYouBanner.tsx, src/components/modules/banners/hocs/withCloseable.tsx
Make banner closing logic more reuseable by factoring out a [higher order component](https://reactjs.org/docs/higher-order-components.html) (HOC). This HOC wraps our banner components with one that handles the showing/hiding state/logic and sets the state in localstorage after being dismissed. Essentially this removes the need to have some state in every banner e.g
```js
const [isOpen, setIsOpen] = useState(true);
const closeBanner = () => {
setChannelClosedTimestamp(bannerChannel);
setIsOpen(false);
}
```
and to have to make them always conditionally render based on that state e.g.
```js
return isOpen ? (
{/* actual banner code */}
) : null
```
This is the main redundancy that I wanted to remove - I think it's not super pretty and it adds a level of indentation to the entire banner which …
=> Make banner closing logic more reuseable

src/server.tsx, src/tests/amp/ampEpicTests.test.ts, src/tests/amp/ampTicker.ts
As per the linked Trello card, this allows tickers in AMP epics to handle the exceeding of our goal, in the same way that our tickers do elsewhere. See screenshots in the related DCR pull request [here](https://github.com/guardian/dotcom-rendering/pull/2090).
=> MJ - Add Goal Reached Behaviour to AMP Ticker

src/components/modules/banners/usEoyAppeal/components/UsEoyAppealBody.tsx, src/components/modules/banners/usEoyAppeal/components/UsEoyAppealHeader.tsx
Update mobile copy for US EOY banner
=> Update copy for mobile US EOY banner

src/lib/reminderFields.test.ts, src/lib/reminderFields.ts
As with the thankyou page sign-up: https://github.com/guardian/support-frontend/blob/main/support-frontend/assets/pages/contributions-landing/components/ContributionThankYou/ContributionThankYouSupportReminder.jsx#L143
It's currently off by one.
Also updated the tests to verify the payload is correct
Tested in CODE:
=> Fix reminder month

src/components/modules/shared/ArticleCountOptOutOverlay.tsx
Fix the spacing of the ctas in the mobile article count opt out. They didn't have any space between them on mobile.
=> Fix article count opt out ctas

src/components/modules/shared/ArticleCountOptOutOverlay.tsx
There was some [discussion](https://www.figma.com/file/igYtUxyn3TaGDMIoFcmDOT/US-EOY-Appeal-2020?node-id=2420%3A140) on the figma that the current copy is a little misleading. Here's the updated copy!
=> Update article count opt out copy

src/lib/ab.test.ts, src/lib/ab.ts, src/lib/variants.ts
To allow the epic tool to configure the size of the audience that should be put into the control.
The tool will ensure that the control is the smallest variant (or joint-smallest).
It's important to still use the mvt cookie value because it ensures a user remains in the same variant across page views.
If `controlProportionSettings` is set then we use this to define the range of mvt values for the control variant.
Otherwise we evenly distribute all variants across the mvt range (as before).
The tool also provides an `offset` value to avoid putting the same users in the control for each test.
The tool will randomly generate the offset (a value between 0-1000000) and this should not change during the lifetime of the test.
=> Support controlProportion in epic tests

src/lib/reminderFields.ts, src/lib/variants.ts
Remove the special US EOY appeal reminder, as per [this card](https://trello.com/c/vWpsFUEv/2434-mon-30-11-switch-pre-contribution-epic-reminder-copy-out-giving-tuesday-to-next-month-us-only).
This didn't technically need to be done, as we'd automated the reminder to stop showing. Having the trello card felt like a good excuse to remove some old logic though!
=> Remove us eoy appeal reminder

src/components/modules/banners/contributionsTemplate/ContributionsTemplate.tsx, src/components/modules/banners/contributionsTemplate/ContributionsTemplateWithVisual.tsx, src/components/modules/banners/contributionsTemplate/ExampleContributionsTemplate.tsx, src/components/modules/banners/contributionsTemplate/ExampleContributionsTemplateWithVisual.tsx, src/components/modules/banners/usEoyAppeal/UsEoyAppeal.tsx, src/components/modules/banners/usEoyAppeal/UsEoyAppealWithVisual.tsx, src/components/modules/banners/usEoyAppeal/components/UsEoyAppealBody.tsx, src/components/modules/banners/usEoyAppeal/components/UsEoyAppealCloseButton.tsx, src/components/modules/banners/usEoyAppeal/components/UsEoyAppealCta.tsx, src/components/modules/banners/usEoyAppeal/components/UsEoyAppealHeader.tsx, src/components/modules/banners/usEoyAppeal/components/UsEoyAppealTicker.tsx, src/components/modules/banners/usEoyAppeal/components/UsEoyAppealVisual.tsx, src/components/modules/banners/usEoyAppeal/helpers/ophan.ts, src/components/modules/shared/ArticleCountOptOutOverlay.tsx, src/server.tsx, src/tests/banners/UsEoyAppealBannerTest.ts, src/tests/banners/bannerTests.ts, src/types/BannerTypes.ts
Updates the banner for the special Giving Tuesday design
=> Update the US EOY banner for Giving Tuesday

cfn.yaml, nest.json
Nest generates the cloudformation for this app at build time.
We need to experiment with different instance types in our ASG, and do not want to implement this as a feature in nest.
So I've copied the cloudformation into this repo while we do this experiment.
The change to the nest.json here is telling nest not to generate a cfn file.
=> Override cloudformation from nest

src/components/modules/banners/usEoyAppeal/UsEoyAppealWithVisual.tsx, src/components/modules/banners/usEoyAppeal/components/UsEoyAppealBody.tsx, src/components/modules/banners/usEoyAppeal/components/UsEoyAppealHeader.tsx, src/components/modules/banners/usEoyAppeal/components/UsEoyAppealTicker.tsx, src/components/modules/banners/usEoyAppeal/components/UsEoyAppealVisual.tsx, src/tests/banners/UsEoyAppealBannerTest.ts, src/tests/banners/bannerTests.ts
We're going back to the previous US EOY banner, but keeping the "Read more" cta and article count.
From tablet we have new body copy.
The mobile banner does not have body copy.
=> Remove US giving tuesday banner

src/utils/S3.ts
So we do not have to set `AWS_PROFILE=membership` when running locally!
=> Set aws profile

src/lib/reminderFields.ts, src/lib/variants.ts
Adds a special reminder to the epic for the US end of year campaign.
This feature automatically finishes on 27/12/20.
The reminder email will be sent on 28/12/20.
=> US EOY epic reminder

src/components/modules/shared/ArticleCountOptOutOverlay.tsx
For some reason we weren't showing the note on mobile - now we are!
=> Show article count opt out note on mobile

src/components/modules/banners/contributionsTemplate/ContributionsTemplateWithVisual.tsx, src/components/modules/banners/contributionsTemplate/ExampleContributionsTemplateWithVisual.tsx, src/components/modules/banners/globalEoy/GlobalEoy.stories.tsx, src/components/modules/banners/globalEoy/GlobalEoy.tsx, src/components/modules/banners/globalEoy/components/GlobalEoyBody.tsx, src/components/modules/banners/globalEoy/components/GlobalEoyCloseButton.tsx, src/components/modules/banners/globalEoy/components/GlobalEoyCta.tsx, src/components/modules/banners/globalEoy/components/GlobalEoyHeader.tsx, src/components/modules/banners/globalEoy/components/GlobalEoyVisual.tsx, src/components/modules/banners/globalEoy/helpers/ophan.ts, src/components/modules/banners/usEoyAppeal/UsEoyAppealWithVisual.tsx, src/components/modules/shared/ArticleCountOptOut.tsx, src/components/modules/shared/ArticleCountOptOutOverlay.stories.tsx, src/components/modules/shared/ArticleCountOptOutOverlay.tsx, src/modules.ts, src/tests/banners/GlobalEoyBannerTest.ts, src/tests/banners/bannerTests.ts
We're A/B testing this against the control yellow banner. Because it has article count, we have to run it as 2 separate tests. This is ok because the dashboard will ignore anything after the `__` in the test name, so the data will be combined.
=> Global EOY banner

src/components/modules/banners/contributionsTemplate/ContributionsTemplateCta.tsx, src/components/modules/banners/globalEoy/components/GlobalEoyBody.tsx, src/components/modules/banners/globalEoy/components/GlobalEoyCta.tsx
The payment method logos are known to improve conversion, so we've added them below the ctas, as with the yellow banner.
Also made a small copy update to the global banner on desktop.
=> Add payment method icons to banner template

src/components/modules/epics/ContributionsEpicTicker.tsx, src/tests/banners/UsEoyAppealBannerTest.ts
(smallest desktop)
(smallest mobile)
(smallest mobile)
=> Epic ticker amount / shorter copy

src/server.tsx
Properly encode Ophan component event as valid URI.
=> encode ophan component event as valid URI

src/lib/tracking.ts, src/server.tsx, src/tests/amp/ampEpic.ts, src/tests/amp/ampEpicTests.ts
This adds `products`, `campaignCode`, and `id` to the Ophan component.
=> adjust open component event to better match equivalent non-AMP events

cfn.yaml
Currently, the ASG does not replace an instance if the load balancer health check fails (i.e. if the node server dies but the ec2 instance is still ok).
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#cfn-as-group-healthchecktype
=> Use LB for health checks

cfn.yaml
dotcom-components (node server) is sometimes reaching the socket limit and failing with:
```
Error: accept EMFILE
at TCP.onconnection (net.js:1536:24)
Emitted 'error' event on Server instance at:
at TCP.onconnection (net.js:1536:10) {
errno: 'EMFILE',
code: 'EMFILE',
syscall: 'accept'
```
The default value is 1024
=> Increase ulimit

src/server.tsx
If our endpoint received a browser id from the client, we forward it to Ophan when sending our view event.
=> MJ include original browser id from client in Ophan request

src/api/contributionsApi.ts, src/lib/cache.test.ts, src/lib/cache.ts, src/lib/fetchTickerData.ts, src/server.tsx, src/tests/amp/ampEpicTests.ts, src/tests/banners/ChannelBannerTests.ts
We've had a couple of instances failing to refresh the epic tests cache. We don't know what's caused this.
This PR hopefully makes it a bit more robust:
1. add a timeout for fetch requests
2. fix scheduling interval after a failure (it was using 20secs forever, rather than going back to the original interval)
I did try to change the epic tests cache to be pre-warmed on startup but it made the tests break in strange ways. So I've parked this for now
=> Fetch timeouts

src/components/modules/banners/contributionsTemplate/ContributionsTemplateCta.tsx, src/components/modules/banners/globalEoy/components/GlobalEoyCta.tsx, src/tests/banners/GlobalEoyBannerTest.ts
The only difference is that the US audience should not see the secondary CTA
=> Include US in global EOY banner

custom-cfn.yaml, src/api/contributionsApi.ts, src/tests/amp/ampEpicTests.ts, src/tests/banners/ChannelBannerTests.ts
Use s3 api to `getObject` the test json files instead of going via a regular fetch (we already do this for the banner deploy timestamps). 
A few things to think about:
- Are we happy with the default AWS timeout settings? (I'm currently trying to find what these are)
- Should we consolidate our buckets? I don't think we need gu-contributions-public anymore
I tested running locally with postman, but we should definitely test in CODE!
- stop admin-console making the files public
- remove the endpoints from fastly
=> Get tests using s3 api

src/server.tsx
Remove the `ophanJsonResponse` from the `epic_view` end point. This causes errors when ophan doesn't return a body (which it doesn't for valid responses!)
=> Remove json ophan response

src/api/contributionsApi.ts, src/components/modules/epics/ContributionsEpicTypes.ts, src/components/modules/epics/ContributionsLiveblogEpic.stories.tsx, src/components/modules/epics/ContributionsLiveblogEpic.testData.ts, src/components/modules/epics/ContributionsLiveblogEpic.tsx, src/lib/targeting.test.ts, src/lib/targeting.ts, src/lib/variants.test.ts, src/lib/variants.ts, src/modules.ts, src/server.tsx
Allows dotcom-components to serve liveblog epics. Adds data and module endpoints to the server as well as adding the new `ContributionsLiveblogEpic` component.
=> Add liveblog epics

src/components/modules/banners/globalEoy/GlobalEoy.tsx, src/components/modules/banners/globalEoy/components/GlobalEoyBody.tsx, src/components/modules/banners/globalEoy/components/GlobalEoyCta.tsx, src/components/modules/shared/ArticleCountOptOut.tsx, src/components/modules/shared/ArticleCountOptOutOverlay.tsx, src/tests/banners/GlobalEoyBannerTest.ts, src/tests/banners/bannerTests.ts, src/types/BannerTypes.ts
1. Adds a `mobileMessageText` field to the banner props to enable us to configure the copy for mobile widths
2. Removes the hardcoded copy from the global eoy banner and uses the props
3. Adds a variant to both global eoy banner tests (AC and non-AC). This is for copy testing.
4. Also made a quick fix to the issue of the article count opt-out popup dropping out of view. We do need a proper solution to this though
=> Update global eoy banner for inauguration

src/components/modules/epics/ContributionsLiveblogEpic.tsx, src/components/modules/epics/ContributionsLiveblogEpicSmallHeader.tsx, src/components/modules/epics/ContributionsLiveblogEpicYellowHeader.tsx, src/modules.ts, src/server.tsx, src/tests/liveblogEpicDesignTest.ts
This adds 2 hardcoded tests because we need different copy in the US. But they're both testing the same thing - the epic design.
Adds new endpoints for the 2 new component modules.
Introduces `ContributionsLiveblogEpicComponent`, so that the variant name can be passed in.
=> Liveblog epic design test

src/components/modules/epics/ContributionsLiveblogEpic.tsx
it turns out we can't reliably use titlepiece, so we're using headline instead:
=> use headline font

src/server.tsx
Adds an `/amp/set_reminder` endpoint for use with AMP epic reminders. See [this PR](https://github.com/guardian/dotcom-rendering/pull/2402) for more information.
=> Mj create amp set reminder endpoint

cfn.yaml, riff-raff.yaml
For comparison, 2 days on t3a.small:
CPU (10-13% during the day):
Autoscaling (always at 3 instances)
=> Use t4g instances

src/components/modules/epics/ContributionsLiveblogEpic.tsx, src/components/modules/epics/ContributionsLiveblogEpicWithCardIcons.tsx, src/modules.ts, src/server.tsx, src/tests/liveblogEpicCardIconsTest.ts
AB testing the card icon image. Implemented as separate modules.
Test name: `2021-02-05-LiveblogEpicCardIconsTest`
=> add payment method icons below cta

src/components/modules/banners/contributions/ContributionsBanner.tsx, src/components/modules/banners/contributions/ContributionsBannerWrapper.tsx, src/components/modules/banners/utils/storybook.ts
The only functional change here is to make the ContributionsBanner use `mobileMessageText` if it's set.
The other change is to add a wrapper for contributions banners.
This is because we're going to be testing designs and I want to avoid duplicating common logic.
So:
- `ContributionsBanner` is still the default yellow banner component, but with the logic moved out.
- `contributionsBannerWrapper` uses the existing `withClosable` wrapper, and passes just the necessary props into the actual banner component.
=> Refactor contribs banner

src/components/modules/epics/ContributionsEpic.stories.tsx, src/components/modules/epics/ContributionsEpic.tsx, src/components/modules/epics/ContributionsEpicButtons.tsx, src/components/modules/epics/ContributionsEpicReminder.tsx, src/lib/reminderFields.test.ts, src/lib/reminderFields.ts
Update Epic reminder to use new reminders API ([trello card](https://trello.com/c/P2olSwqR/2486-reminders-architecture-v2))
=> Update to new reminders API

src/components/modules/banners/contributions/variantB/ContributionsBannerVariantB.tsx
To better align with the front layout.
Before:
After:
=> fix alignment of banner

src/tests/banners/ContributionsBannerDesignTest.ts, src/tests/liveblogEpicCardIconsTest.ts
Remove AUDCountries from hardcoded tests from hardcoded tests to allow for testing in the tool in response to the FB situation in AU.
=> Remove AUDCountries from hardcoded tests

cfn.yaml
at the moment
we want them to be clearer what they are, in the same was as most of the other apps are now
=> use a more sensible name for the instances

src/components/modules/puzzles/puzzlesBanner/PuzzlesBanner.tsx, src/modules.ts, src/server.tsx
This adds a basic route and component with build process for the new puzzles banner component.
We're setting this up separately from the existing banner architecture because the puzzles banner is significantly different in appearance and behaviour- it has a very different copy structure and acts as a persistent part of the page rather than a dismissible banner.
=> Basic set up for the new puzzles banner component

src/components/modules/banners/digitalSubscriptions/DigitalSubscriptionsBanner.stories.tsx, src/components/modules/banners/digitalSubscriptions/DigitalSubscriptionsBanner.tsx
This is a small change to make the `%%ARTICLE_COUNT%%` variable available in the digital subscriptions banner heading as well as in the banner body text. This was missed in a previous PR: https://github.com/guardian/support-dotcom-components/pull/366
Put this branch on code and use the [code version of the banner tool](https://support.code.dev-gutools.co.uk/banner-tests2) to update the text.
The `%%ARTICLE_COUNT%%` variable is available in the digital subscriptions banner heading.
This is a very small change, incorporating code that is already live (implemented by the Contributions team).
=> Add article count functionality to banner heading

.eslintrc.js, src/components/modules/banners/contributions/ContributionsBanner.tsx, src/components/modules/banners/contributions/ContributionsBannerMobile.tsx, src/components/modules/banners/contributions/ContributionsBannerWrapper.tsx, src/components/modules/banners/contributions/variantA/ContributionsBannerVariantA.tsx, src/components/modules/banners/contributions/variantB/ContributionsBannerVariantB.tsx, src/server.tsx, src/tests/banners/ChannelBannerTests.ts, src/tests/banners/ContributionsBannerDesignTest.ts, src/types/BannerTypes.ts
Currently we allow banners to have mobile-only copy for the body (aka messageText) only.
This PR makes all mobile content optionally configurable.
I have left the `mobileMessageText` field in the `BannerContent` type for backwards-compatibility. This is so that cached versions of the banner components can still use it. It should be removed later.
But new versions of the banner components will use a new field for mobile copy. The banner props now contain a `mobileContent` field:
```
content?: BannerContent;
mobileContent?: BannerContent;
```
I have changed the following banners to use the new model:
`ContributionsBanner`
`ContributionsBannerVariantA`
`ContributionsBannerVariantB`
I have also refactored the `ContributionsBannerWrapper` (which is used for the above 3 banners) to construct …
=> Full support for mobile banner copy

src/lib/variants.test.ts, src/lib/variants.ts
this is for the 'thank you' epic, where we would like to include a cta but not a reminder signup
As a supporter and with no reminder signup cookie:
=> hide reminders for supporters

README.md, rollup.config.js
rollup takes a long time to compile each module. We need to solve this.
In the mean time, this PR enables us to specify which module we're working on when developing locally, e.g.
`yarn modules-dev --moduleName=epic`
=> Specify module with modules-dev

cfn.yaml
There's currently a major review of the guardian's security practices under the cyber security programme. One of the projects in this programme is to install a vulnerability scanner called Wazuh in guardian ec2 instances.
This patch enables Wazuh to work by
* Giving permission to the instance to call describe-tags,
so the agent can identify itself in a human readable way with 
the wazuh server.
Deploy to CODE and see if the wazuh agent successfully identifies itself with the central server 
Wazuh will start reporting vulnerabilities to infosec!
CFN could be wrong and cause downtime.
Works in code ✅
=> Add policy to allow instance to describe tags

src/server.test.ts
Currently when the server.tsx test runs it logs:
`Error: Failed to make initial request for ampEpicTests`
It doesn't cause the test to fail.
This change silences it by mocking the function that makes the request
=> Mock getAmpExperimentData in test

src/components/modules/epics/ContributionsEpicReminder.tsx
the logic for setting the url in the epic module broke here: https://github.com/guardian/support-dotcom-components/pull/381/files#diff-469af771aea54851d95ec44ef73613ac45100f0a2e151d76312fd97a6dd83212R168
This is because `isProd` only works server-side.
Quick fix for now is to hardcode it to the PROD url
We can worry about CODE later
=> fix reminder url

src/components/ResponsiveImage.tsx, src/components/hooks/useEscapeShortcut.ts, src/components/hooks/useTabDetection.ts, src/components/modules/puzzles/puzzlesBanner/PuzzlesBanner.tsx, src/components/modules/puzzles/puzzlesBanner/images.ts, src/components/modules/puzzles/puzzlesBanner/puzzlesBannerStyles.ts, src/components/modules/puzzles/puzzlesBanner/squares/ContentSquares.tsx, src/components/modules/puzzles/puzzlesBanner/squares/MinimisedBorderSquares.tsx, src/components/modules/puzzles/puzzlesBanner/squares/MinimisedContentSquare.tsx, src/components/modules/puzzles/puzzlesBanner/squares/MobileSquares.tsx, src/components/modules/puzzles/puzzlesBanner/squares/Square.tsx, src/components/modules/puzzles/puzzlesBanner/squares/SquareSide.tsx
This adds the minimised form of the puzzles banner, and the ability to toggle back and forth using the button.
I've also added, experimentally, the facility to minimise the banner by hitting the escape key. The banners end up at the bottom of the tab order on dotcom, so a user relying on the keyboard has to tab through the entire page to reach the minimise button, which is a profoundly annoying experience- and will be even more so on a crossword page as the crosswords have a _lot_ of focusable elements. Currently we aren't doing anything to tell users that this shortcut exists, so this needs some further thought, but this is primarily for testing once we have the banner showing up under the 0% A/B test on dotcom.
**iPhone SE 2020**
**OnePlus 8**
**iPad Pro**
**Google Nexus 9**
**Firefox - …
=> Minimised state for the puzzles banner

src/components/modules/banners/contributions/ContributionsBanner.tsx, src/components/modules/banners/contributions/ContributionsBannerCommonStyles.ts, src/components/modules/banners/contributions/ContributionsBannerCta.tsx
Make some tweaks to the contributions banner styles as per [this card](https://trello.com/c/TZcrf9qL/2569-contributions-banner-design-tweaks).
17px body copy on mobile
align card icons with CTA text + body copy
=> Tweak contribution banner styles

.github/workflows/snyk.yml
The snyk error on every PR is unhelpful because:
1. we have a snyk rota for addressing these issues
2. we very rarely add new dependencies
=> Remove snyk check from branches

src/components/modules/banners/contributions/ContributionsBannerCommonStyles.ts, src/components/modules/banners/contributions/ContributionsBannerCta.tsx
Small tweaks the the mobile contributions banner. We've increased the line height, and aligned the payment icons with the left edge of the CTA for mobile.
=> Tweak mobile contributions banner styles

artifact.json, cfn.yaml
The recent change to node-riffraff-artifact changed the file type, meaning we've been deploying an old build since.
=> Fix deploy

riff-raff.yaml
We'll soon be serving modules from S3.
This change aligns the caching headers with what we currently have [here](https://github.com/guardian/support-dotcom-components/blob/main/src/server.tsx#L386)
riff-raff change [here](https://github.com/guardian/riff-raff/pull/619)
=> Set cacheControl and surrogateControl on modules in S3

src/components/modules/epics/ContributionsEpic.tsx, src/components/modules/epics/ContributionsEpicReminder.stories.tsx, src/components/modules/epics/ContributionsEpicReminder.tsx, src/components/modules/epics/ContributionsEpicReminderSignedIn.stories.tsx, src/components/modules/epics/ContributionsEpicReminderSignedIn.tsx, src/components/modules/epics/ContributionsEpicReminderSignedOut.stories.tsx, src/components/modules/epics/ContributionsEpicReminderSignedOut.tsx, src/components/modules/epics/utils/reminders.ts
Update the `ContributionsEpicReminder` for signed in users. I decided to spend a little bit extra time on this to refactor the original component too. In the process I think I've stumbled across quite a nice pattern that helped out with building the components too. We now have a top level `ContributionsEpicReminder` which doesn't do a whole lot in it's JSX (just returns either the signed in or signed out component) but is responsible for passing the `reminderStatus` (e.g submitting/error) into the signed in/out component. By having this status as a prop, it makes it really easy to build/test the component in storybook - want to see the submitting (loading) state? just create a story with the status set to loading ! Before I was just submitting and relying on slow internet to see it 🙈 …
=> Update reminders for signed in users

src/components/hooks/useEscapeShortcut.ts, src/components/modules/puzzles/localStorage.ts, src/components/modules/puzzles/puzzlesBanner/PuzzlesBanner.stories.tsx, src/components/modules/puzzles/puzzlesBanner/PuzzlesBanner.tsx, src/components/modules/puzzles/puzzlesBanner/puzzlesBannerStyles.ts, src/components/modules/puzzles/puzzlesBanner/squares/MinimisedContentSquare.tsx, src/components/modules/puzzles/puzzlesBanner/squares/MobileSquares.tsx, src/components/modules/puzzles/puzzlesBanner/squares/TabletDesktopSquares.tsx, src/lib/tracking.ts, src/server.tsx, src/types/BannerTypes.ts, src/types/OphanTypes.ts
This adds Ophan tracking to the puzzles banner for the following events:
- Load (includes the expanded/minimised state)
- Banner expanded or minimised
- App store link clicked
This also adds the proper links to the Apple and Google app stores, code to save the banner state into local storage (so once minimised it will stay minimised on the next page load, or vice-versa), and makes the naming of variables and props relating to expanded/minimised state consistent.
=> Add tracking to puzzles banner

README.md, module-versions.md, src/api/contributionsApi.testData.ts, src/components/modules/epics/ContributionsEpicTypes.ts, src/lib/variants.ts, src/modules.test.ts, src/modules.ts, src/schemas/bannerPayload.schema.json, src/schemas/epicPayload.schema.json, src/server.tsx, src/tests/banners/ChannelBannerTests.ts, src/tests/banners/DefaultContributionsBannerTest.ts, src/tests/banners/bannerSelection.test.ts, src/tests/banners/bannerSelection.tsx, src/tests/epicArticleCountTest.ts, src/types/BannerTypes.ts
The modules are already uploaded to a public S3 bucket during the deploy, but are not currently used.
Fastly routes requests to `/modules/...` to this bucket.
This PR makes use of the S3 modules in CODE + PROD by telling the client to fetch them from `/modules/...`.
Locally, the modules are still served by the node server.
This required a bit of extra fastly configuration, to set the `Access-Control-Allow-Origin` header on responses from this s3 bucket.
This PR also introduces versioning.
A version applies to all modules. We will release a new modules version infrequently, for example for a backwards-incompatible upgrade of emotion.
The client can optionally send a `modulesVersion` string in its request. If this is present then we use it to build the url of the module. This means clients …
=> Use modules from S3, with versioning

src/components/modules/epics/ContributionsEpic.stories.tsx, src/components/modules/epics/ContributionsEpic.tsx, src/components/modules/epics/ContributionsEpicArticleCountAbove.stories.tsx, src/components/modules/epics/ContributionsEpicArticleCountAbove.tsx, src/components/modules/epics/ContributionsEpicArticleCountInline.stories.tsx, src/components/modules/epics/ContributionsEpicArticleCountInline.tsx, src/components/modules/epics/ContributionsEpicReminder.stories.tsx, src/components/modules/epics/ContributionsEpicReminderSignedIn.stories.tsx, src/components/modules/epics/ContributionsEpicReminderSignedOut.stories.tsx, src/components/modules/epics/ContributionsEpicWithArticleCountAbove.stories.tsx, src/components/modules/epics/ContributionsEpicWithArticleCountInline.stories.tsx, src/components/modules/shared/ArticleCountOptOut.tsx, src/components/modules/shared/ArticleCountOptOut2.tsx, src/components/modules/shared/helpers/ophan.ts, src/lib/replaceArticleCount.tsx, src/server.tsx, src/tests/epicArticleCountTest.ts, src/tests/epicArticleCountTestData.ts
Adds a second round of article count design tests. Additionally, we want to track how many users opt out of article counts. To do this the platform now passes in a `submitComponentEvent` function as a prop, much like for the banners. This requires https://github.com/guardian/dotcom-rendering/pull/2747 to be merged. I was thinking we wouldn't bother implementing this in frontend as so few (if any?) articles are rendered by frontend.
UK/AUS
- force-epic=EpicSeparateArticleCountTestR2__UK_AUS:control
- force-epic=EpicSeparateArticleCountTestR2__UK_AUS:above
- force-epic=EpicSeparateArticleCountTestR2__UK_AUS:inline
EU/ROW
- force-epic=EpicSeparateArticleCountTestR2__EU_ROW:control
- force-epic=EpicSeparateArticleCountTestR2__EU_ROW:above
- …
=> Article count design test round 2

src/components/modules/epics/ContributionsEpic.tsx, src/components/modules/epics/ContributionsEpicButtons.tsx, src/components/modules/epics/ContributionsEpicReminder.tsx, src/components/modules/epics/utils/ophan.ts
Add tracking the the epic reminder. This is primarily so we can work out a "conversion rate" for the component.
[Trello card](https://trello.com/c/QcMhp9hO/2591-adding-tracking-events-to-epic-reminders)
=> Add reminder tracking

src/server.tsx
After chatting with Jessie + Minna we've decided to reprioritse the design test over the weekend.
We also quickly chatted about a potential solution that would allow for us to quickly prioritise specific epics tests. Perhaps we could include hardcoded tests in the tool somehow? You wouldn't be able to edit them, but you would be able to move them around in the priority list like the other tests. Perhaps a dev would create the test in SDC and then create a "hardcoded" test (a new type of epic test) that references the name they gave it.
=> Reprioritise design test

src/components/modules/epics/ContributionsEpic.tsx, src/components/modules/epics/ContributionsEpicButtons.tsx, src/components/modules/epics/utils/ophan.ts
Along with recording a reminder view, we also want to know if a user is signed in/out. Now we send that data in the `value` field of the view component event.
=> Send signed in/out data on epic reminder view event

src/components/modules/puzzles/puzzlesBanner/PuzzlesBanner.tsx, src/components/modules/puzzles/puzzlesBanner/images.ts, src/components/modules/puzzles/puzzlesBanner/puzzlesBannerStyles.ts, src/components/modules/puzzles/puzzlesBanner/squares/TabletDesktopSquares.tsx
This addresses a number of small remaining issues before launch:
- Changes the side padding of the minimised state of the banner below the tablet breakpoint, and fixes a slight visual shift of the button position when switching between the expanded and minimised state at tablet and desktop breakpoints.
- Updates to a higher resolution version of the packshot
- Switches app store links to use the `<Link>` component from Source, for better focus styling
- Improves the accessibility hint shown to users navigating with a keyboard
**Mobile view, minimised**
**Keyboard shortcut hint on desktop**
=> Puzzles pre-launch fixes

src/lib/tracking.ts
This updates the tracking event creation functions to not include an `abTest` field when no test name and variant have been passed, as this may be causing issues with Ophan tracking for the puzzles banner.
=> Prevent passing an empty A/B test object in tracking

src/components/modules/puzzles/puzzlesBanner/puzzlesBannerStyles.ts
This bumps up the z-index of the app store links in the puzzles banner to fix an issue where they were not interactive at mobile breakpoints due to element overlap.
=> Fix issue with app store buttons not being clickable on mobile

src/components/modules/puzzles/puzzlesBanner/puzzlesBannerStyles.ts, src/payloads.ts, src/server.tsx, src/types/BannerTypes.ts
This addresses a couple of issues that have come up in the first few days of the puzzles banner being live.
* Users who printed the page to do the crossword with pen & paper found the banner, even when minimised, could obscure clues on the printed page. The banner now has a blanket `display: none` rule for the print media query.
* The banner was incorrectly being shown to digital subscribers and other supporters who should not see RR messaging, as we were not checking the value of `showSupportMessaging` server-side. This has now been amended so we return an empty payload for those users
As part of adding the exclusion for existing supporters, I've done a little refactoring of the `server.tsx` file as it was nearly 700 lines long and was making tiny baby kittens cry. I've extracted the …
=> Prevent display of puzzles banner to supporters, and hide it when printing the page

src/lib/variants.test.ts, src/lib/variants.ts, src/payloads.ts, src/tests/epicTargetingTest.ts, src/tests/epicTargetingTestData.ts
Add a special hardcoded tests that will compare different targeting strategies. Specifically, for 'highly engaged' users (>5 article count) we're testing ask4 vs ask6, and for 'less engaged' users (<5 article count) we're testing ask4 vs ask2.
Note: Users that have **opted out** of article count, won't be placed in either highly or less engaged tests. This is because the `respectArticleCountOptOut` filters out any test with `articlesViewedSettings`.
**>5 articles**
**<5 articles**
**>5 articles**
**<5 articles**
**>5 articles**
**<5 articles**
=> Add targeting test

src/tests/epicTargetingTestData.ts
Update highlighted text copy in US targeting test as this new line of copy hasn't performed as well in the US.
=> Update highlighted text copy in US targeting test 

src/components/modules/puzzles/puzzlesBanner/puzzlesBannerStyles.ts, src/components/modules/puzzles/puzzlesBanner/squares/ContentSquares.tsx, src/components/modules/puzzles/puzzlesBanner/squares/MobileSquares.tsx
This introduces a number of small tweaks to the puzzles banner below the mobileMedium breakpoint to make sure it's still readable and can be minimised on smaller devices.
This branch is currently deployed on CODE.
Taken with iPhone SE
**Before**
**After**
=> Fix issues with the puzzles banner on small screens

src/lib/variants.test.ts, src/lib/variants.ts
Remove hasNoZeroArticleCount filter. This filter seems to have been added to catch inconsitencies between the article views that counted towards test targeting, and those used when actually rendering the component. These are now the same value, so let's remove this filter.
=> Remove hasNoZeroArticleCount filter

src/components/modules/epics/ContributionsEpic.stories.tsx, src/components/modules/epics/ContributionsEpicButtons.tsx, src/components/modules/epics/utils/storybook.ts, src/lib/fetchTickerData.ts, src/lib/reminderFields.ts, src/lib/variants.test.ts, src/lib/variants.ts, src/payloads.ts, src/tests/epicTargetingTestData.ts
Update epic secondary cta model. The updated model is now explicit about the type of secondary cta: custom, contributions reminder, or none. 
The matching tooling change is here: https://github.com/guardian/support-admin-console/pull/202
=> Update epic secondary cta model

src/tests/epicTargetingTest.ts
We're turning off the non-US targeting tests as they're costing us quite a lot of money to run. This doesn't seem to be the case in the US, so we will leave them on to gather more data.
=> Turn off non US targeting tests

src/components/modules/banners/digitalSubscriptions/DigitalSubscriptionsBanner.tsx, src/components/modules/banners/digitalSubscriptions/digitalSubscriptionsBannerStyles.ts, src/components/modules/banners/guardianWeekly/GuardianWeeklyBanner.tsx, src/components/modules/banners/guardianWeekly/guardianWeeklyBannerStyles.ts
This overhauls the digital subscription and Guardian Weekly banners to make better use of Source components. It also switches to using props provided from the banner tooling for the CTA text and links, and adds the ability to dismiss the banner using the escape key in the same manner as the puzzles banner.
This branch is currently on CODE.
=> Upgrade subs banners to use Source buttons, links and layout components

src/components/modules/banners/contributions/ContributionsBanner.tsx, src/components/modules/banners/contributions/ContributionsBannerCta.tsx, src/components/modules/banners/contributions/ContributionsBannerMobile.tsx, src/components/modules/banners/contributions/ContributionsBannerSecondaryCta.tsx, src/components/modules/banners/utils/storybook.ts
Fix contributions banner secondary CTA. At the moment it shows a second primary CTA (payment icons included!) which doesn't look great. It's worth noting though that since the new banner design was rolled out, we haven't actually had a banner with a secondary CTA. 
This PR adds a new `ContributionsBannerSecondaryCta` component.
**mobile**
**wide**
=> Fix contributions banner secondary CTA

src/components/modules/epics/utils/ophan.ts
Update reminder event componentType. We have some queries that expect `VIEW` events on the `ACQUISITION_EPIC` to mean epic views. Currently those queries will be double counting those pageviews that also have a reminder view.
=> Update reminder event componentType

src/components/modules/banners/contributions/ContributionsBannerCta.tsx, src/components/modules/banners/contributionsTemplate/ContributionsTemplateCta.tsx, src/components/modules/banners/g200/components/G200BannerCtas.tsx, src/components/modules/epics/ContributionsEpicButtons.tsx
Fix CLS caused by payment icons in the epic and banners. By specifying the width + height on the `img` tag the browser knows the aspect ratio of the image and can remove the layout shift by reserving space. Here's a good article for more info: https://www.smashingmagazine.com/2020/03/setting-height-width-images-important-again/
=> Fix CLS caused by payment icons

src/components/modules/banners/guardianWeekly/guardianWeeklyBannerStyles.ts, yarn.lock
This fixes an issue with the Guardian Weekly banner at the tablet breakpoint where the image would overflow and cover the text.
=> Fix overflow issue with Guardian Weekly banner packshot

src/components/modules/banners/contributions/ContributionsBannerCommonStyles.ts, src/components/modules/banners/contributions/ContributionsBannerMobile.tsx
Tweak mobile banner styles to squeeze in some more copy.
**Changes**
- mobile body copy 17px -> 15px
- mobile header copy 24px -> 20px
=> Tweak mobile banner styles

src/components/modules/shared/ModuleWrapper.tsx
Upgrading to emotion 11 has caused the following warning to appear in the console (w.r.t `withParsedProps` wrapper): 
```
(!) Plugin typescript: @rollup/plugin-typescript TS2322: Type 'ModuleProps' is not assignable to type 'IntrinsicAttributes & WithConditionalCSSProp<PropsWithChildren<ModuleProps>> & ModuleProps & { ...; }'.
Type 'ModuleProps' is not assignable to type 'WithConditionalCSSProp<PropsWithChildren<ModuleProps>>'.
```
This 'fix' was found it here: https://github.com/emotion-js/emotion/issues/2169. It's not really a fix, but it keeps typescript happy. I'm not 100% sure what's going on with this issue. It's to do with the fact that we're no longer transforming our jsx to the `React.createElement` form, but instead using the `jsx` function from `emotion`.
=> Fix withParsedProps warning

src/components/modules/banners/contributions/ContributionsBannerCommonStyles.ts
Update the font size of the highlighted text at mobile
=> Fix banner highlighted text styles

src/components/modules/header/Header.tsx, src/types/HeaderTypes.ts, src/types/OphanTypes.ts
Currently the header module is only being used by DCR.
I'm working on making frontend use it as well.
The INSERT and VIEW events are currently sent by the platform (DCR). This is following the convention set by epic/banner. But actually there's no reason for the platform to do this. And in the case of the header it's problematic because frontend's view tracking requires the user to scroll first, even if it's in view.
So this PR moves the INSERT and VIEW events into the module in SDC.
I will disable the remote header in DCR temporarily before merging this, as it's a breaking change.
=> Send ophan header events from the module

riff-raff.yaml
Currently fastly caches modules for 5 mins, and the client for 2 mins.
=> Increase module max-age to 5mins

src/components/modules/epics/ContributionsEpic.tsx
DCR resets the styles of bold tags, this adds them back to the epic. This is a quick fix - perhaps we could think about how best to handle unwanted overrides caused by the platform more generally? 
**before**
**after**
=> Apply bold font to b tags

src/components/modules/epics/ContributionsEpic.tsx, src/components/modules/shared/helpers/stage.ts, src/lib/env.ts, src/types/EpicTypes.ts, src/types/shared.ts
We have a new stream for epic view events (https://github.com/guardian/support-analytics).
This is for the 'super mode' feature, which will use intraday conversion rate data to change the ask strategy of epics on specific articles.
This change makes the epic component send an event when it is viewed. The events api is behind fastly.
=> Send epic view events

src/components/modules/header/Header.stories.tsx, src/components/modules/header/Header.tsx, src/components/modules/header/HeaderSupportAgain.stories.tsx, src/components/modules/header/HeaderSupportAgain.tsx, src/modules.ts, src/payloads.ts, src/tests/header/headerSelection.ts, src/types/HeaderTypes.ts
Add "support again" header test. Currently the test is disabled (commented out). This is to allow us to merge this PR before we are ready to go live in order to make some parallel development on the header easier.
**mobile**
**tablet**
**desktop**
=> Add "support again" header test

src/tests/header/headerSelection.ts
Turn on the `support again` header test.
**TODO**
First we should deploy the platform changes: 
And the lp change:
=> Turn on support again test

src/components/modules/epics/ContributionsEpicButtons.tsx, src/components/modules/epics/utils/ophan.ts
Adds an additional Ophan event for when the epic CTA buttons enter the viewport. This is to allow us to assess the drop-off rate midway through the epic.
=> send ophan event when epic CTA buttons are viewed

src/components/modules/epics/ContributionsEpicArticleCountAboveWithOptOut.tsx
this was caused by intellij 'fixing' the formatting. Note to self - always check the jsx after using this feature!
=> Fix epic AC copy

src/components/modules/header/HeaderAusMomentNonSupporter.stories.tsx, src/components/modules/header/HeaderAusMomentNonSupporter.tsx, src/components/modules/header/HeaderAusMomentSupporter.stories.tsx, src/components/modules/header/HeaderAusMomentSupporter.tsx, src/hooks/useNumberOfSupporters.ts, src/lib/cookies.ts, src/lib/fetchTickerDataClient.ts, src/modules.ts, src/tests/header/headerSelection.ts, src/types/HeaderTypes.ts, yarn.lock
- Special header for Aus Moment 2021
- Renders different copies for recurring / one-off and non-supporters & mobile design
- Fetches supporter number data
**Non-supporter**
desktop
mobile 
**Supporter**
Recurring contributors
One-off contributors
mobile for both one-off and recurring
=> Aus Moment Header 

src/lib/superMode.ts, src/lib/tracking.ts, src/payloads.ts, src/server.test.ts, src/tests/epics/epicSelection.test.ts, src/tests/epics/epicSelection.ts, src/types/BannerTypes.ts, src/types/EpicTypes.ts, src/types/HeaderTypes.ts, teamcity.sh
Add "super mode" support. SDC will now poll an `articles.json` in s3 (produced by the super mode calculator) to get a list of articles currently in super mode. We have new logic when assigning a user to a test for a super mode article. First we do a regular pass through the tests. If there is a suitable test, the user will be assigned to. This **does not** count as a super mode test. If there are no suitable tests, we do a second, "super mode", pass through the tests. This time, we effectively treat all tests as "always ask". If there is a suitable test, the user will be assigned to it. This **does** count as a super mode test. In this manner, super mode tests are only ever **incremental** i.e we only consider it a super mode test if the user wouldn't have seen a test if not for super …
=> Add "super mode" support

src/lib/reminderFields.ts, src/payloads.ts, src/tests/banners/ChannelBannerTests.ts, src/tests/banners/DefaultContributionsBannerTest.ts, src/tests/banners/bannerSelection.test.ts, src/tests/banners/bannerSelection.ts, src/tests/epics/epicSelection.ts, src/types/BannerTypes.ts, src/types/EpicTypes.ts, src/types/HeaderTypes.ts, src/types/shared.ts
Co-authored-by: @TomPretty
A recent PR accidentally caused an indirect import of the aws sdk in the banner module.
This broke the rendering of the banner (and made the module huge).
The actual fix here is to remove the import of `epicSelection.ts` from `reminderFields.ts`.
This is because a field shared between client + server was importing from a server-specific file.
In the process we decided to unify the `Audience` and `UserCohort` types. We now use `UserCohort` everywhere, which is consistent with the admin-console.
This all points to something we already knew - *we need to properly separate client and server parts of this codebase*. It's far too easy to accidentally mess up the imports. @TomPretty has already been investigating this
Tested in CODE:
=> Fix banner module

src/components/modules/banners/digitalSubscriptions/DigitalSubscriptionsBanner.stories.tsx, src/components/modules/banners/guardianWeekly/guardianWeeklyBanner.stories.tsx, src/components/modules/banners/utils/storybook.ts, src/components/modules/epics/ContributionsEpic.stories.tsx, src/components/modules/epics/ContributionsEpic.tsx, src/components/modules/epics/ContributionsEpicButtons.tsx, src/components/modules/epics/ContributionsLiveblogEpic.stories.tsx, src/components/modules/epics/ContributionsLiveblogEpic.testData.ts, src/components/modules/epics/ContributionsLiveblogEpic.tsx, src/components/modules/epics/utils/storybook.ts, src/components/modules/puzzles/puzzlesBanner/PuzzlesBanner.stories.tsx, src/components/modules/shared/ModuleWrapper.tsx, src/factories/tracking.ts, src/lib/tracking.ts, src/payloads.ts, src/tests/banners/DefaultContributionsBannerTest.ts, src/tests/banners/bannerSelection.ts, src/types/BannerTypes.ts, src/types/EpicTypes.ts, src/types/HeaderTypes.ts, src/types/shared.ts
We already do this for the banner.
Validate the props client-side, to prevent backwards incompatible props changes. If validation fails then the epic is not displayed.
Also I refactored the tracking types, so epic/banner/header now all use the same `Tracking` type.
=> Epic props validation

src/components/modules/epics/ContributionsEpic.stories.tsx, src/components/modules/epics/ContributionsEpic.tsx, src/components/modules/epics/utils/storybook.ts, src/lib/history.ts, src/payloads.ts, src/types/EpicTypes.ts
Currently in the epic, both the Above and Inline versions of AC use the same count. This count is based on the 'period in weeks' set from the tool, defaulting to 52.
We need to decouple the Above AC from 'period in weeks', to enable them to display ACs for different periods.
This is a breaking change to the props, but now that we have props validation in the epic it means clients with older versions of the module will just not display an epic (while we wait for caches to clear).
It replaces the `numArticles` prop with an object containing both the count for the whole year, and the count based on the configured 'period in weeks'.
=> Decouple 'above' AC from targeting

src/components/modules/banners/ausMoment/components/AusBannerHeader.tsx
Make some small tweaks to the mobile Aus banner:
- increase heading size
- increase margin below heading
=> Aus banner mobile tweaks

src/modules.ts, src/tests/header/headerSelection.ts
we need to improve our targeting to prevent e.g. recent subscribers seeing the message. For now it only targets non-supporters
=> Remove aus supporter header

src/components/modules/banners/ausMoment/AusBanner.tsx, src/components/modules/banners/common/BannerWrapper.tsx, src/components/modules/banners/contributions/ContributionsBanner.tsx, src/components/modules/banners/digitalSubscriptions/DigitalSubscriptionsBanner.tsx, src/components/modules/banners/g200/G200Banner.tsx, src/components/modules/banners/guardianWeekly/GuardianWeeklyBanner.tsx, src/components/modules/banners/hocs/withCloseable.tsx
Fixes a bug with closing the banners. When we close a banner we store a timestamp in local storage to record when a user dismissed a banner: `gu.prefs.engagementBannerLastClosedAt` for channel 1, and `gu.prefs.subscriptionBannerLastClosedAt` for channel 2. However, at the moment all contributions banners set the channel 1 timestamp, and all subs banners se the channel 2 timestamp. This is **regardless** of which channel they are actaully in. The fix was straight forward - the `bannerChannel` is already passed as a prop to the banners, so we use this value in the `withCloseable` hoc instead (previously it was a second arg).
=> Fix banner closing bug

src/components/modules/puzzles/puzzlesBanner/PuzzlesBanner.tsx
This updates the url links on the puzzles banner for both the Apple App Store and Google Play Store.
=> Update puzzles banner url links

packages/modules/src/modules/puzzles/puzzlesBanner/squares/ContentSquares.tsx
This PR removes the QR code from the Puzzles Banner. I've commented this code out rather than removing it completely as we may want to restore it in time.
=> Puzzles Banner: Disable QR code square

packages/modules/src/modules/epics/ContributionsLiveblogEpic.stories.tsx, packages/modules/src/modules/epics/ContributionsLiveblogEpic.tsx
Fortunately we don't currently use article count in the liveblog.
But the prop for the liveblog epic component is wrong. This PR fixes it, in case we do want to use article count.
=> Fix liveblog article count

package.json, packages/modules/babel.config.json, packages/modules/jest.config.js, packages/modules/package.json, packages/modules/src/hooks/useHasBeenSeen.ts, packages/modules/src/modules/epics/ContributionsEpic.test.tsx, yarn.lock
Based on this PR: https://github.com/guardian/support-dotcom-components/pull/384 by @TomPretty 
But I started a new branch because too much has changed since the refactor.
This PR includes a very basic rendering test for the epic.
We can start adding more tests soon
=> Basic module tests

packages/modules/src/modules/shared/helpers/ophan.ts
We need to avoid using ACQUISITIONS_EPIC and ACQUISITIONS_BANNER for components _within_ the epic/banner, as they can get mixed up with the overall events (e.g. epic VIEW event).
Currently the old-style AC opt-out does send these componentTypes. So this PR replaces that with ACQUISITIONS_OTHER, as we do elsewhere. It would confuse things further to change the `component.id` field at this point, so I've added a `value` field which specifies the parent componentType and the fact that it's the AC opt-out popup.
=> Use 'ACQUISITIONS_OTHER' componentType for AC opt-out popup events

packages/server/src/tests/header/headerSelection.ts
Turn off the aus moment header. I've created a [card](https://trello.com/c/luC8oJOW/2776-remove-aus-moment-references) to clean up more thoroughly
=> Turn off aus moment header

cdk/lib/__snapshots__/dotcom-components.test.ts.snap, cdk/lib/dotcom-components.ts
Add ASG policy to new cloudformation stack. 
Inspecting the snapshot diff shows that it's generating cloudformation that's exactly what we've got in the original `cfn.yaml`.
=> Add ASG policy to new cloudformation stack

packages/server/src/channelSwitches.ts, packages/server/src/payloads.ts
this is set from the tool: https://github.com/guardian/support-admin-console/pull/232
=> Switch for hardcoded epic tests

packages/modules/src/modules/epics/ContributionsEpicChoiceCards.tsx
This `position: relative` is necessary to stop it jumping to the top of the page when a button is clicked.
The current solution (`visibility: hidden`) affects accessibility
=> make choice cards container relative

cdk/lib/__snapshots__/dotcom-components.test.ts.snap, cdk/lib/dotcom-components.ts
The existing alarm is not part of the cloudformation stack.
This change adds 2 alarms for:
- 5XX rate above 0.002%
- unhealthy instances
=> Add alarms to cdk

packages/server/src/tests/epics/choiceCards.ts, packages/server/src/tests/epics/choiceCardsTestData.ts
We need to run copy tests in the US.
We haven't yet tested in Aus
=> Disable choice cards test in US, add Aus

packages/server/src/middleware/logging.ts, packages/server/src/server.ts
For epic requests, log the first 4 weeks of `weeklyArticleHistory`. We want to see examples of the new tag counts.
We'll be able to see this in kibana
E.g.
```
{
status: 200,
method: 'POST',
path: '/epic',
didRenderEpic: false,
didRenderBanner: undefined,
clientName: 'dcr',
bannerTargeting: undefined,
epicTargeting: {
weeklyArticleHistory: [
'{"week":18882,"count":13,"tags":{"world/europe-news":1,"world/world":1}}'
]
}
}
```
=> Log article counts

packages/server/src/tests/banners/ChannelBannerTests.ts
This makes the component event type for banners derive from the banner channel, not the banner template.
[Trello card](https://trello.com/c/OpRVBm2O)
This should enable colleagues to better track click-through events relating to subscriptions banners even when the template used is for the contributions banner.
This fix still relies on making an assumption about what kind of banner a test variant is in order to send the correct component event, except this time based on the channel it belongs to rather than the template used. BRR colleagues have already run subscriptions banners in channel 1 and contributions banners in channel 2 in the past- this is not a perfect fix!
It would be worth considering in the near term either:
a) Adding another field to the banner tooling to explicitly state …
=> Base a banner variant's Ophan component type on the channel, not the template

packages/modules/src/modules/banners/common/BannerWrapper.tsx, packages/modules/src/modules/banners/common/types.tsx, packages/modules/src/modules/banners/investigationsMoment/InvestigationsMomentBanner.stories.tsx, packages/modules/src/modules/banners/investigationsMoment/InvestigationsMomentBanner.tsx, packages/modules/src/modules/banners/investigationsMoment/components/InvestigationsMomentBannerArticleCount.tsx, packages/modules/src/modules/banners/investigationsMoment/components/InvestigationsMomentBannerBody.tsx, packages/modules/src/modules/banners/investigationsMoment/components/InvestigationsMomentBannerCloseButton.tsx, packages/modules/src/modules/banners/investigationsMoment/components/InvestigationsMomentBannerCtas.tsx, packages/modules/src/modules/banners/investigationsMoment/components/InvestigationsMomentBannerHeader.tsx, packages/modules/src/modules/shared/ArticleCountOptOutOverlay.stories.tsx, packages/modules/src/modules/shared/ArticleCountOptOutOverlay.tsx, packages/modules/src/modules/shared/ArticleCountOptOutPopup.tsx, packages/server/src/tests/banners/ChannelBannerTests.ts, packages/shared/src/config/modules.ts, packages/shared/src/types/banner.ts
Add investigations moment banner [**Trello card**](https://trello.com/c/wz2hokoq/2788-design-build-investigations-moment-banner)
**mobile**
**tablet**
**desktop**
**leftcol**
**wide**
>
=> Add investigations moment banner

packages/modules/src/modules/banners/investigationsMoment/InvestigationsMomentBanner.tsx, packages/modules/src/modules/banners/investigationsMoment/components/InvestigationsMomentBannerCtas.tsx
Just a couple of tweaks for the banner as requested by Ellen:
1. Tweak top right shadow across mobile breakpoints
2. Make payment icons 20px at tablet+
=> Investigations banner tweaks

packages/server/src/lib/ab.test.ts, packages/server/src/lib/ab.ts
We had a couple of tests come through with only a control, but with `controlProportionSettings` set. This broke variant allocation.
This change ensures we have other variants.
We also need to change the epic tool to prevent this from happening.
=> Make selectVariant safer

packages/server/package.json, packages/server/src/lib/ab.test.ts, packages/server/src/lib/ab.ts, yarn.lock
This changes the logic for assigning a browser's mvt value to a variant.
It's based on the long-standing [logic in support-frontend](https://github.com/guardian/support-frontend/blob/9c7649f7758f68541ff3d292fe515fc02665d229/support-frontend/assets/helpers/abTests/abtest.js#L217), which uses a seed value for each test to keep tests independent.
It uses the [seedrandom](https://github.com/davidbau/seedrandom) library.
This will help us to run concurrent independent tests on dotcom, e.g. a banner message test + a banner targeting test.
=> Improve test variant allocation

packages/modules/src/modules/banners/contributions/ContributionsBannerSignInCta.tsx, packages/modules/src/modules/epics/ContributionsEpic.stories.tsx, packages/modules/src/modules/epics/ContributionsEpic.tsx, packages/modules/src/modules/epics/ContributionsEpicSignInCta.tsx, packages/modules/src/modules/epics/utils/ophan.ts, packages/shared/src/types/epic.ts
This adds a sign-in link to the epic, controlled by a prop for the variant. This is to enable an A/B test on impact of including a sign in option. See also #539. 
**Desktop**
**Tablet**
**Mobile**
=> Add the option to show a sign in link to the epic

packages/modules/src/modules/epics/ContributionsEpicArticleCountAboveWithOptOut.tsx
Adds a missing apostrophe to the article count opt-out option.
Co-authored-by: Tom Pretty <TomPretty@users.noreply.github.com>
=> Add missing apostrophe to article count opt-out

packages/server/src/tests/banners/bannerSelection.ts, packages/server/src/tests/banners/bannerTargetingTests.test.ts, packages/server/src/tests/banners/bannerTargetingTests.ts, packages/shared/src/types/banner.ts
Co-authored-by: Rik Roots KaliedaRik@users.noreply.github.com
This is a targeting test. We want to measure the impact of not displaying the banner on some low performing sections.
Dotcom must now send sectionId and tagIds:
https://github.com/guardian/frontend/pull/24325
https://github.com/guardian/dotcom-rendering/pull/3574
=> Test suppressing banner on some sections

packages/modules/src/modules/banners/common/BannerWrapper.tsx
Currently if a user clicks the primary or secondary cta (which typically take them to the support site or an article), the banner is not dismissed. This means they'll still see it on subsequent page views, which is a poor user experience.
With this PR any primary or secondary cta click will also dismiss the banner, meaning the user will not see it again until the next banner redeploy.
=> Any cta closes the banner

packages/modules/src/lib/replaceArticleCount.tsx
This was broken here: https://github.com/guardian/support-dotcom-components/pull/557/files#diff-21fed3afe7c219869438ed4902474a49427cf7ab5f0f4355f3ad8eb0d27d847fR51
Support for html in these messages was always a bit of an accidental 'feature'. The tools should offer proper support for creating links, but for now this PR will make it behave as before.
=> Re-enable html in messages

packages/server/src/server.ts
Currently the `Access-Control-Allow-Origin` header is a wildcard (`*`)
We're seeing some failed cors requests from the Apple Mail browser, so let's see if setting an origin helps.
=> set cors origin

packages/server/src/tests/epics/articleCountByTagTest.ts
The [first test](https://github.com/guardian/support-dotcom-components/pull/557) did not reach significance in a week.
The second test targets environment content only.
=> Restart AC-by-tag epic test

packages/modules/src/modules/header/EoYUSMomentHeader.stories.tsx, packages/modules/src/modules/header/EoYUSMomentHeader.tsx, packages/modules/src/modules/header/HeaderWrapper.tsx, packages/server/src/payloads.ts, packages/server/src/tests/header/headerSelection.ts, packages/shared/src/config/modules.ts, packages/shared/src/types/header.ts
This adds a variant of the header for the US end-of-year campaign, with specific text for both supporters and non-supporters.
**Non-supporters**
**Existing supporters**
=> US end-of-year campaign header

packages/server/src/tests/epics/singleContributorPropensityTest/singleContributorPropensityTest.ts
this querystring is not required, as the choice cards add it
=> fix cta on single contributor test

packages/server/src/tests/header/headerSelection.ts
This fixes an issue with the start date for the special end-of-year copy being in December rather than November.
=> Fix US EOY copy start date

packages/server/src/tests/header/headerSelection.ts
We don't want to show users in the US who have contributed during the moment the 'make a year end gift' messaging. Additionally I noticed that those CTAs were currently pointing to the subscribe page - I've updated them to point the contribute page with `One off` selected
=> Update us eoy header

packages/modules/src/modules/epics/ContributionsEpic.tsx
we can now set the default frequency per variant: https://github.com/guardian/support-dotcom-components/pull/545/files#diff-f61d94af1bff9403a86eff24d9e0740db6b9d1cf3607a47286ddc847dc1af6aaR273
But this currently breaks selection of the default amount.
With this PR, it now correctly selects a default amount for single:
=> Fix default value in epic when default frequency is set

packages/server/src/tests/banners/bannerDeploySchedule.test.ts, packages/server/src/tests/banners/bannerDeploySchedule.ts
For the first hour after a scheduled banner deploy, users will keep seeing a banner.
This is because the `previousDay` function does not set the minutes + seconds to 0.
E.g.
- the last redeploy was 2021-11-26 08:00:00
- the user last closed the banner at 2021-11-26 08:30:00
Currently this function returns 2021-11-26 08:30:00, when it should return 2021-11-26 08:00:00.
I've added a test case to cover this.
=> Fix banner deploy bug

packages/server/src/tests/banners/bannerSelection.ts
because of the EOY campaign. This will last until the new year
=> Exclude US from scheduled banner deploys

packages/modules/src/modules/header/EoYUSMomentHeader.stories.tsx, packages/modules/src/modules/header/EoYUSMomentHeader.tsx, packages/server/src/tests/header/headerSelection.ts
This PR hides the Subscribe CTA on Giving Tuesday. This change only affects breakpoints above Phablet as the Subscribe CTA doesn't appear below this.
This also adds a line-height to the container for the header, to attempt to override the base styling on dotcom.
[**Trello Card**](https://trello.com/c/YxjXnb0R/157-%E2%9A%A1-remove-subscriptions-from-the-us-header-on-giving-tuesday)
Run Storybook locally.
Outside of Giving Tuesday:
On Giving Tuesday:
=> Hide subscribe in header on Giving Tuesday

packages/modules/src/modules/banners/common/BannerWrapper.tsx, packages/shared/src/lib/reminderFields.ts
Updating the US reminder in the Epic & Banner from Giving Tuesday (today) -> to NYE.
=> Update US reminders

README.md, packages/server/package.json
this seems to be the convention, to avoid clashing with DCR locally.
So now we can just run `yarn server start`.
Does not affect CODE/PROD
=> Use port 8082 when run locally

packages/server/src/lib/targetingTesting.ts, packages/server/src/tests/banners/bannerDeploySchedule.test.ts, packages/server/src/tests/banners/bannerDeploySchedule.ts, packages/server/src/tests/banners/bannerSelection.ts, packages/server/src/tests/banners/bannerTargetingTests.ts
Does showing the subs banner less often impact conversions?
Control: the subs banner is deployed on monday and friday (existing behaviour).
Variant: the subs banner is deployed on monday only.
If overall conversions are not significantly lower then we can improve user experience on the site without harming revenue.
We should run this test for at least a month. The US is currently excluded from auto deploys.
This PR ends the `2021-11-04_BannerTargeting_SectionExclusions` targeting test. We're still waiting for a Data Tech change before impressions become available, so we don't yet know if this logic will become a permanent part of banner targeting.
It's a bit clunky, but I've added a `deploySchedule` field to the `TargetingTestVariant` type. This means a variant can override the default …
=> AB test showing subs banner once per week

packages/modules/src/modules/banners/usEoyMoment/UsEoyMomentBanner.stories.tsx, packages/modules/src/modules/banners/usEoyMoment/components/UsEoyMomentBannerTicker.tsx, packages/modules/src/modules/header/EoYUSMomentHeader.tsx
This PR updates the existing overfunded ticker UI in line with the approved design as well as the US EOY header following a design review.
Header
| mobileMedium (Default) | Desktop (Default) | mobileMedium (Supporters) | Desktop (Supporters) |
|------------------------|-------------------|---------------------------|------------|
|  <img width="170" alt="Screenshot 2021-12-03 at 17 08 45" src="https://user-images.githubusercontent.com/44685872/144644926-296fd1ec-70d1-4789-a004-cb6f2f35bb20.png">   |  <img width="294" alt="Screenshot 2021-12-03 at 17 09 03" src="https://user-images.githubusercontent.com/44685872/144645013-c9d5b13c-e202-4428-8725-fab8c16d1732.png">   |    <img width="143" alt="Screenshot 2021-12-03 at 17 09 32" src="https://user-images.githubusercontent.com/44685872/14464508 …
=> Update US EOY header and overfunded ticker

packages/server/src/server.ts, packages/server/src/tests/amp/ampEpicModels.ts, packages/server/src/tests/amp/ampEpicTests.ts
Allows per variant configuration of default contribution amount choice card.
=> enable default choice card frequency to work with amp epic

packages/modules/src/modules/header/EoYUSMomentHeader.tsx, packages/modules/src/modules/header/Header.tsx, packages/modules/src/modules/header/HeaderSupportAgain.tsx
Make the heading text into `h2` in the following components:
- Header
- HeaderSupportAgain
- EOYUSMoment
Screen reader users are able to discover the "Support" and "Thank you" messaging in the list of headings
=> Make heading text in header more semantic

packages/server/src/tests/banners/bannerTargetingTests.ts
We think the existing test is really testing day-of-week + proximity to the contributions banner deploy. We know the subs banner performs well at weekends, and in the variant we only deploy at the start of the week, close to the contribs banner.
What happens if we change it to:
- Sat morning subs
- Mon morning contribs
In general, decoupling frequency of banner views and day of the week is tricky. In future we could change the logic to deploy every N days, per user. Though this all becomes simpler when we eventually move away from having 2 banners...
=> Subs banner deploy test v2

packages/server/src/tests/banners/bannerSelection.ts, packages/server/src/tests/banners/bannerTargetingTests.ts
users in the US were previously excluded from scheduled banner deploys
=> Include US in banner auto-deploys

packages/modules/src/modules/banners/common/BannerWrapper.tsx, packages/server/src/payloads.ts, packages/shared/src/lib/reminderFields.ts
Turn off NYE reminder sign up from the US TY page.
**NB: Merge this on the 30th**
[**Trello Card**](https://trello.com/c/Z9QdKsbu/215-revert-new-years-eve-reminder-ctas-in-the-us-to-the-standard-reminder-cta-before-nye)
=> Turn off NYE reminder (MERGE ON 30th DEC)

riff-raff.yaml
The riffraff default is changing to false - see https://github.com/guardian/riff-raff/pull/664.
The modules need to be publically readable in S3
=> Set module publicReadAcl to true

packages/server/src/channelSwitches.ts, packages/server/src/payloads.ts
Use new header switch set in the admin console. Admin console PR: https://github.com/guardian/support-admin-console/pull/272
=> Add header switch

packages/server/src/tests/banners/bannerTargetingTests.ts
I ended this earlier in the week because it was again performing poorly.
But I just looked again with Jesse and May and while total £AV was down, the £AV/impression isn't too bad. We've decided to give this test more time now that things have returned to normal after christmas. We're also interested to see how it performs in the US, where subs performs worse.
=> Resume subs banner deploy frequency test

packages/modules/src/modules/banners/globalNewYear/GlobalNewYearBanner.stories.tsx, packages/modules/src/modules/banners/globalNewYear/components/GlobalNewYearBannerBody.tsx, packages/modules/src/modules/banners/globalNewYear/components/getGlobalNewYearBanner.tsx
Enables bold text in Global New Year Moment banner copy, configurable in RRCP by wrapping in `<strong>` tags.
_Example_
=> enable strong html tag in global new year banner copy

packages/modules/src/modules/epics/ContributionsEpic.tsx, packages/modules/src/modules/epics/ContributionsEpicACByTag.tsx, packages/shared/src/config/modules.ts
Remove the `ContributionsEpicACByTag` module. This was recently used in an AB test, and the variant was not significant.
I've left the `aboveArticleCountByTag` functionality in for now, I suspect we'll be revisiting this in some form later
=> Remove AC-by-tag epic

packages/modules/src/modules/banners/guardianWeekly/GuardianWeeklyBanner.tsx
This updates the packshot images on the Guardian Weekly banner for the duration of the Jan 22 campaign. 
| Before | After |
| -- | -- |
| <img width="319" alt="Screenshot 2022-01-21 at 10 39 02" src="https://user-images.githubusercontent.com/44685872/150522894-9cddd4c3-cb76-4594-a34d-7321f34e10cc.png"> | <img width="319" alt="Screenshot 2022-01-21 at 10 38 44" src="https://user-images.githubusercontent.com/44685872/150523087-0bf21b6c-fb5a-4b66-8ca6-f377b957c5f5.png"> | 
| <img width="766" alt="Screenshot 2022-01-21 at 11 59 48" src="https://user-images.githubusercontent.com/44685872/150523635-51228e7c-7361-4c5a-8a8a-1f8d8d927b35.png"> | <img width="769" alt="Screenshot 2022-01-21 at 10 38 30" src="https://user-images.githubusercontent.com/44685872/150523139-17e2c05a-d19e-4e3c-a15a-00707426 …
=> Update GW banner images

packages/modules/src/modules/banners/guardianWeekly/GuardianWeeklyBanner.tsx
This reverts the date/time based conditional rendering of the Guardian Weekly banner image.
=> Revert conditional rendering of GW banner img

packages/shared/src/lib/tracking.ts
Back in October we migrated to sending all ophan events from the modules (rather than the client) - https://github.com/guardian/support-dotcom-components/pull/546
The existing logic for sending events to ophan didn't include the `labels` field, which unfortunately means we haven't been tracking `SUPER_MODE` impressions since. We _have_ been tracking `SUPER_MODE` acquisitions however.
This PR adds `labels` to ophan componentEvents:
For reference, here's how DCR sends events:
https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/web/browser/ophan/ophan.ts#L71
=> Include labels in componentEvents to ophan

packages/server/src/payloads.ts, packages/server/src/server.ts, packages/server/src/tests/header/headerSelection.test.ts, packages/server/src/tests/header/headerSelection.ts, packages/shared/src/types/abTests/header.ts
The epic + banner already support this, as does the client.
e.g. `?force-header=TEST_NAME:VARIANT_NAME`
=> Enable forcing the header test/variant

packages/modules/src/modules/header/Header.stories.tsx, packages/modules/src/modules/header/Header.tsx
There is an optional `mobileContent` field on the header model, but currently the component doesn't use it.
On mobile only the primary cta is displayed in the header (no heading/subheading/2nd cta).
Also, currently we hide the arrow svg in the cta below `mobileMedium` (375px).
With this change:
1. Below `mobileLandscape` (480px) we use the primary cta from the `mobileContent`.
2. Below `mobileLandscape` we hide the arrow svg. This means we now hide it up to 480px, not 375px. I think it's preferable to have this and the cta text change at the same breakpoint, otherwise you might get weird widths between 375-480 where the cta is too long
=> Enable custom mobile cta in header

packages/modules/src/modules/epics/ContributionsEpic.tsx, packages/modules/src/modules/epics/ContributionsEpicWithCheckout.stories.tsx, packages/modules/src/modules/epics/ContributionsEpicWithCheckout.tsx, packages/modules/src/modules/epics/checkout/ContributionsEpicCheckout.tsx, packages/modules/src/modules/epics/checkout/useIframedCheckout.ts, packages/server/src/payloads.ts, packages/server/src/tests/epics/inEpicPaymentTest.ts, packages/server/src/tests/epics/inEpicPaymentTestData.ts, packages/shared/src/config/modules.ts, packages/shared/src/lib/geolocation.ts
Add support to the Epic for embedding the new `contribute-in-checkout` checkout page from the support site. Additionally, it adds a "draft" test that is only viewable by forcing with a query parameter. This way we can do some testing in PROD before going live with the actual test (will be a follow up PR).
We have a [go-live plan](https://docs.google.com/document/d/1FbnjdkntdUhvYNOP8VLYdWaHNSFV0tOKsjSOjipr5nE/edit#) for releasing the A/B test. The first stage involves merging the [support site PR](https://github.com/guardian/support-frontend/pull/3403). After that is live and tested, we can merge this PR and then do some further testing.
=> In Epic checkout + draft test

packages/modules/src/modules/banners/common/BannerText.tsx, packages/modules/src/modules/banners/common/BannerWrapper.tsx, packages/modules/src/modules/banners/common/types.tsx, packages/modules/src/modules/banners/contributions/ContributionsBanner.tsx, packages/modules/src/modules/banners/contributions/ContributionsBannerMobile.tsx, packages/modules/src/modules/banners/utils/storybook.ts, packages/server/src/payloads.ts, packages/server/src/tests/banners/ChannelBannerTests.ts, packages/shared/src/types/abTests/banner.ts, packages/shared/src/types/props/banner.ts
Based on design here: https://www.figma.com/file/MHJFoREcjTbQuaNakm8VIV/Generic-Banner?node-id=1756%3A28624
The PR enables us to A/B test putting article count (AC) in a subheading of the banner. Currently the AC goes in the heading or body. The subheading would only be displayed if AC >= 5, which means we'd no longer have to create AC and non-AC versions of each banner test.
- Rather than doing a hardcoded test I'm going to add a new "Separate article count" checkbox to the tool, so the test can be configured from the banner tool. I suspect this toggle will be useful even if we decide a subheading isn't the right place for AC.
- This new feature behaves like the epic AC "badge" in that it's automatically hidden if the user's AC is below 5. But - for this AB test only users with AC of 5 …
=> Banner AC subheading

packages/modules/src/modules/epics/ContributionsEpic.stories.tsx, packages/modules/src/modules/epics/ContributionsEpic.tsx, packages/modules/src/modules/epics/ContributionsEpicWithCheckout.stories.tsx, packages/modules/src/modules/epics/checkout/ContributionsEpicCheckout.tsx
Use `stage` for epic checkout. This allows us to iframe in the correct domain, which is important as the CSP on the support site only allows it to be embedded in the same stage (e.g PROD support site can only be embedded in a PROD epic)
=> Use stage for epic checkout

packages/server/src/tests/banners/ChannelBannerTests.ts, packages/shared/src/types/abTests/banner.ts, packages/shared/src/types/props/banner.ts
The `BannerVariant` model has an optional seperate field for mobile content:
```
bannerContent: BannerContent;
mobileBannerContent?: BannerContent;
```
Historically this was not the case, and in the migration to support both we left some legacy fields in the model.
This PR removes them - they've not been used for a while.
TODO - remove these fields from support-admin-console as well
=> Remove deprecated banner fields

packages/modules/src/modules/banners/guardianWeekly/GuardianWeeklyBanner.tsx
The Guardian Weekly 50% off campaign is over, we can restore the packshot to the previous version without the roundal. The re-introduced images can be seen below...
PR that added the current image with the roundal: https://github.com/guardian/support-dotcom-components/pull/613
=> restore old GW banner images

packages/dotcom/package.json, packages/server/src/lib/targetingTesting.test.ts, packages/server/src/tests/banners/bannerSelection.test.ts, packages/server/src/tests/banners/bannerTargetingTests.test.ts, packages/server/src/tests/banners/bannerTargetingTests.ts, packages/shared/src/types/targeting/banner.ts, packages/shared/src/types/targeting/shared.ts
Currently for existing browsers we show the banner on the first page view after a redeploy.
For most users that means their first page view of the day.
This means we don't currently have the data to explore whether it's best to wait for the `nth` page view of the day before showing a banner. E.g. it's possible the 1st page view has a terrible conversion rate because most users just want the headlines.
We don't currently have a daily page view count in the browser. But we do have an _article_ view count for the day.
- control - show banner on first page view after redeploy (existing behaviour)
- variant 1 - show if today's AC >= 1.
- variant 2 - if network front, show if AC >= 1. If article, show if AC >= 2.
In the example of a user visiting the network front on a monday morning:
- in the …
=> Test impact of showing banner on different pageviews

packages/server/src/lib/ab.ts
For the SFD test we wanted consistent variant allocation across channels. We're going to be doing this again, so this PR adds a more general solution.
We already use `__` in the test name to group together different tests in the AB test dashboard.
With this change, we'll also coordinate variant allocation across channels for tests with the same prefix (before the `__`).
Note - any existing tests with `__` in the name will be affected by this change. It effectively shuffles the variant allocation for existing browsers.
=> Remove suffix from test name for variant allocation

packages/modules/src/modules/banners/contributions/ContributionsBanner.stories.tsx, packages/modules/src/modules/banners/contributions/ContributionsBannerCta.tsx, packages/modules/src/modules/epics/ContributionsEpic.stories.tsx, packages/modules/src/modules/epics/ContributionsEpicButtons.tsx, packages/modules/src/modules/epics/ContributionsLiveblogEpic.stories.tsx, packages/modules/src/modules/epics/ContributionsLiveblogEpic.tsx, packages/shared/src/lib/tracking.ts
Sometimes we don't link to the support site, and so it doesn't make sense to display the credit card icons.
E.g. an upcoming test to link to mobile apps instead.
This PR affects:
- contributions banner
- epic
- liveblog epic
=> Hide credit card icons if no support link

packages/modules/src/modules/banners/common/BannerText.tsx
A [recent PR](https://github.com/guardian/support-dotcom-components/pull/632) introduced paragraphs for banners.
But this has added margin above and below the body.
This PR removes it.
=> Fix banner paragraph margins

packages/server/src/lib/targeting.ts, packages/server/src/payloads.ts, packages/server/src/server.ts, packages/server/src/tests/banners/ChannelBannerTests.ts, packages/server/src/tests/banners/bannerSelection.test.ts, packages/server/src/tests/banners/bannerSelection.ts, packages/server/src/tests/epics/epicSelection.test.ts, packages/server/src/tests/epics/epicSelection.ts, packages/server/src/tests/header/headerSelection.test.ts, packages/server/src/tests/header/headerSelection.ts, packages/shared/src/types/abTests/banner.ts, packages/shared/src/types/abTests/shared.ts
Introduces a `deviceType` field to the `Test` type:
`type DeviceType = 'Mobile' | 'Desktop' | 'All';`
I've implemented support for deviceType targeting on the epic/banner/header.
This will be used for targeting mobile-only banners which advertise the mobile apps. We plan to A/B test this against normal reader revenue messages.
It uses the user-agent string, and I've copied the [regexes from frontend](https://github.com/guardian/frontend/blob/main/static/src/javascripts/lib/detect.js#L187).
PR to add this to the tools: https://github.com/guardian/support-admin-console/pull/289
I've added unit tests to `epicSelection.test.ts`, which effectively covers the same logic used by the banner/header.
I've tested in CODE by making POST requests with different user-agents.
=> Mobile targeting

packages/modules/src/modules/epics/ContributionsLiveblogEpic.stories.tsx, packages/modules/src/modules/epics/ContributionsLiveblogEpic.tsx
On DCR, we only have 60 pixels of padding to the left of liveblog content, not 80. This PR introduces the ability to vary this padding value based on `platformId` to allow for this
=> Vary `ContributionsLiveblogEpic` padding for DCR

packages/server/src/lib/targeting.ts
This removes the hardcoded audience size for the single front door ab test
=> Remove hardcoded single front door ab test audience size

packages/modules/src/modules/header/Header.stories.tsx, packages/modules/src/modules/header/Header.tsx, packages/modules/src/modules/header/HeaderWrapper.tsx
The header tool enables us to define a custom primary cta at mobile (for shorter copy than desktop).
However, there's currently no way to show nothing at mobile. This feature has been requested by Marketing - they only want a cta at desktop, because it needs the main copy for context.
=> Header: do not render cta if not defined for mobile

packages/server/src/tests/banners/bannerTargetingTests.ts
this was blocked by an issue with daily article count which has now been fixed by:
https://github.com/guardian/dotcom-rendering/pull/4312
https://github.com/guardian/frontend/pull/24784
=> Run banner page view targeting test

packages/dotcom/package.json, packages/shared/src/types/targeting/banner.ts
We previously added [browserId for epic targeting](https://github.com/guardian/support-dotcom-components/blob/main/packages/shared/src/types/targeting/epic.ts#L29), for the single contributor propensity test.
We will soon be using propensity models for banner targeting, which means the client needs to send a browserId if the user has consented.
TODO - update DCR + frontend to send browserId
=> Add browserId to banner targeting

packages/modules/src/modules/header/Header.stories.tsx, packages/modules/src/modules/header/Header.tsx, packages/modules/src/modules/header/HeaderWrapper.tsx
Reverts guardian/support-dotcom-components#642
This is removing the cta on mobile when we do want it
Needs a closer look
=> Revert "Header: do not render cta if not defined for mobile"

packages/server/src/tests/banners/bannerTargetingTests.test.ts, packages/server/src/tests/banners/bannerTargetingTests.ts
variant1 is doing very well, but variant2 is doing poorly and losing money.
This PR removes variant2, so we can focus on gathering data for control vs variant1
=> Remove variant2 from banner deploy test

packages/modules/src/modules/epics/ContributionsEpic.stories.tsx, packages/modules/src/modules/epics/ContributionsEpic.tsx, packages/server/src/factories/variant.ts, packages/shared/src/types/abTests/epic.ts, packages/shared/src/types/props/epic.ts, packages/shared/src/types/props/shared.ts
The existing `backgroundImageUrl` field hasn't been used for a long time. The name is a bit misleading because it appears at the top.
This PR proposes replacing it with an `image` field - we leave it to the component to decide how/where an image should be rendered.
And it defines an `Image` type which requires an alt-text (credit to @KaliedaRik for pointing out that this is missing).
The `Image` type can be reused elsewhere (e.g. for the upcoming author profile test in the epic, or in the banner)
TODO - add the new field to the epic tool
=> Add image field to epic model

packages/server/src/channelSwitches.ts, packages/server/src/payloads.ts, packages/server/src/tests/banners/ChannelBannerTests.ts, packages/server/src/tests/banners/DefaultContributionsBannerTest.ts, packages/server/src/tests/banners/bannerSelection.test.ts, packages/server/src/tests/banners/bannerSelection.ts, packages/shared/src/types/abTests/banner.ts
this is to enable us to quickly disable hardcoded tests from the RRCP, in an emergency. We already have this for epics.
I initially tried to do the filtering in [bannerTests.ts](https://github.com/guardian/support-dotcom-components/blob/main/packages/server/src/tests/banners/bannerTests.ts#L14), but it's messy because different hardcoded tests may need different positions in the array. So I've just added an `isHardcoded` field to the `BannerTest` model
admin-console PR: https://github.com/guardian/support-admin-console/pull/302/files
=> hardcoded banner tests switch

packages/server/src/middleware/logging.ts
We've been investigating a spike in 500 responses from dotcom components. It's tricky to tell where these requests are coming from so we've decided to start logging the user agent string to see if that can provide any clarity. The step change in 5xxs and the regularity of them is leading us to think it might be coming from something internal.
=> Log user-agent string.

packages/server/src/middleware/bodyContainsAllFields.ts, packages/server/src/middleware/index.ts, packages/server/src/server.ts
This change adds a `bodyContainsAllFields` middleware that we can use on the /header endpoint. This provides a minimal amount of validation that should be sufficient to address an on going alarm. This alarm has been caused by POST requests to /header without a valid request body. The proper solution is to add zod for validation but that will require a refactor to the packages to avoid the dotcom package pulling in zod as an unrequired dependency. This change is just temporary and can be removed after implementing proper valid.
I originally tried to just check that `req.body` was defined, but express will still provide us with an empty object when making a request without a body.
=> Add temporary 'validation' to /header endpoint.

packages/modules/src/modules/epics/BylineWithHeadshot.tsx, packages/modules/src/modules/epics/ContributionsEpic.stories.tsx, packages/modules/src/modules/epics/ContributionsEpic.tsx, packages/shared/src/types/abTests/epic.ts, packages/shared/src/types/props/epic.ts, packages/shared/src/types/props/shared.ts
This PR adds the ability to include a message byline with a profile picture to the end of the Epic body copy. The design of the component is very similar to the bylines that get added at the top of main site opinion articles.
**Screenshots:**
Desktop
Tablet
Mobile:
=> Add a profile picture to the Epic

packages/server/src/tests/epics/topReaderArticleCountBadge/build.ts
This change adds `australia-news/australian-politics` and `australia-news/australian-election-2022` to the exclude tags of the top reader test.
=> Update top reader test exclude tags.

package.json
As part of an npm audit, I'm adding gh links to package jsons that don't already include them if this repo is being published. This makes it easier to work out which repos are "in production" in one way or another.
=> fix: Include repo url in package.json

packages/shared/src/lib/placeholders.test.ts, packages/shared/src/lib/placeholders.ts, packages/shared/src/types/prices.ts
We now have a number of placeholders (aka templates), e.g. `%%COUNTRY_NAME%%`.
These are substituted on the client when rendering the component.
The existing logic is getting quite inefficient as it scans the same text for each placeholder.
This PR uses the [replace](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) string method to scan the string for placeholders just once.
A set of rules is defined to substitute each placeholder in the string.
=> Refactor placeholder substitution

packages/modules/src/modules/banners/contributions/ContributionsBannerReminderSignedIn.stories.tsx, packages/modules/src/modules/banners/contributions/ContributionsBannerReminderSignedOut.stories.tsx, packages/modules/src/modules/banners/contributions/ContributionsBannerSecondaryCta.tsx, packages/modules/src/modules/banners/environmentMoment/EnvironmentMomentBanner.tsx, packages/modules/src/modules/epics/ContributionsEpicArticleCountAboveWithOptOut.tsx, packages/modules/src/modules/header/Header.stories.tsx, packages/modules/src/modules/header/Header.tsx
We've moved on from `@emotion/core` in favour of the newer `@emotion/react`. However, we still had some references in the code to `@emotion/core` which was causing it to get bundled. By removing it, our gzipped epic bundle goes from 43.29kb to 36.72kb. We've actually removed `@emotion/core` from our `package.json` but it was being pulled in by storybook so these old references went unnoticed (i.e it didn't cause a build error).
The biggest contributor to our bundle (outside of our own code) is `zod`. Removing it shaves of 10kb, which is pretty significant. It might be worth looking into any more lightweight validation libraries, but as it stands `zod` has really great DX and I think it adds a lot of value to have the props validated given our architecture.
**Original**
**After removing …
=> Remove references to @emotion/core

packages/modules/src/modules/banners/common/BannerText.tsx
Currently if `highlightedText` is not set, an element with a background colour is still rendered at the end of the body:
This PR ensures it is not rendered if `highlightedText` is either undefined or an empty string.
After the fix -
=> Fix banner bug when no highlightedText

packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.stories.tsx, packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx, packages/modules/src/modules/banners/momentTemplate/buttonStyles.ts, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerArticleCount.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerBody.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerCloseButton.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerCtas.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerHeader.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerVisual.tsx, packages/modules/src/modules/banners/momentTemplate/settings.ts, packages/modules/src/modules/shared/ResponsiveImage.tsx, packages/shared/src/types/props/shared.ts
This change adds the `MomentTemplateBanner` component. The idea with this component is to allow for quickly putting together moment banners in the future. 
The ultimate goal here is to hook this up to the RRCP to allow configuring moment banners without any dev involvment. That probably means adding the new `BannerTemplateSettings` type to the `BannerProps` and then adding the corresponding fields to the RRCP.
For now, a dev will have to create moment banners using this template. We can see an example of that [here](https://github.com/guardian/support-dotcom-components/pull/691/files#diff-fab4c18cd160490fbf12df2f444e6da0bb0e66b4377b7c52b6d60e65a20bfb7aR14). It involves importing the `getMomentTemplateBanner` function and passing in some hardcoded `BannerTemplateSettings` to set the right …
=> Moment banner template

packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.stories.tsx, packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerCtas.tsx, packages/modules/src/modules/banners/momentTemplate/settings.ts
This change just makes a couple of small tweaks to the MomentTemplateBanner:
- sets the CTA size always to small (as per designs)
- fixes a typ0 with `imageSetings` (should be `imageSettings`)
=> Small tweaks to the MomentTemplateBanner

packages/server/src/tests/banners/bannerSelection.ts, packages/server/src/tests/banners/bannerTests.ts, packages/server/src/tests/banners/propensityModelTest/propensityModelTest.ts, packages/server/src/tests/banners/propensityModelTest/propensityModelTestData.ts, packages/server/src/tests/banners/propensityModelTest/propensityModelTestDigisubCopy.ts, packages/server/src/tests/banners/propensityModelTest/propensityModelTestGWCopy.ts
This replaces v1 of the test - see https://github.com/guardian/support-dotcom-components/pull/657
We're still using the high-GW / low-DS segment.
But this time the entire banner channel 2 audience is put into the test.
In the control:
- all European browsers see GW
- all other browsers see DS
In the variant:
- all high-GW/low-DS browsers see GW
- all other browsers see DS
It's a slightly hacky implementation. This is because we decide what to show *after* assigning the browser to a variant. This doesn't fit with how our existing logic works, so I've hacked a special case for this test into `bannerSelection.ts`. If this becomes a common way of doing AB tests then we can think about how to support it properly.
=> ML propensity model banner test v2

packages/server/src/tests/banners/propensityModelTest/propensityModelTest.ts
Currently impressions + conversions within a variant are indistinguishable, e.g. in the variant a user who sees DS and a user who sees GW are tracked the same.
But we can set the `products` field in the tracking data, which [ophan will accept](https://github.com/guardian/support-dotcom-components/blob/main/packages/shared/src/types/ophan.ts#L5).
=> Track product in GW ML test

packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerArticleCount.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerArticleCountOptOut.tsx
This change adds an article count opt out component specific to the moment template banner (MomentTemplateBannerArticleCountOptOut).
This did involve a lot of copy and pasting from the existing opt out (ArticleCountOptOutPopup) which is a shame but I think having some duplication is probably the simplest solution for now. The issue is that the existing component takes a `type` parameter which it then uses to decide on the styles for the component. This doesn't quite fit with moment template banner which we want to be able to fully customise just through the `BannerTemplateSettings` that we provide. The settings already specify everything that we need to style the opt out (background colour, primary cta, secondary cta, and close button) so it was quite simple to create a new component that …
=> Add specific moment template banner article count opt out.

packages/modules/src/modules/banners/postElectionAuMoment/PostElectionAuMomentAlbaneseBanner.tsx, packages/modules/src/modules/banners/postElectionAuMoment/PostElectionAuMomentBanners.stories.tsx, packages/modules/src/modules/banners/postElectionAuMoment/PostElectionAuMomentHungBanner.tsx, packages/modules/src/modules/banners/postElectionAuMoment/PostElectionAuMomentMorrisonBanner.tsx, packages/modules/src/modules/banners/postElectionAuMoment/settings.ts, packages/server/src/tests/banners/ChannelBannerTests.ts, packages/shared/src/config/modules.ts, packages/shared/src/types/abTests/banner.ts
This PR adds the 3 possible post Australian election banners. We will make all three of these [available in the RRCP](https://github.com/guardian/support-admin-console/pull/334), which will allow us to quickly update the messaging on the site after the election is called.
**Albanese win**
**Hung parliament**
**Morrison win**
=> Post Australian Election banners

packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.stories.tsx, packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerBody.tsx, packages/modules/src/modules/banners/momentTemplate/settings.ts, packages/modules/src/modules/banners/postElectionAuMoment/settings.ts
This change adds `HighlightedTextSettings` to the `BannerTemplateSettings` type. This allows specifying the text colour & highlight colour. I've implemented the highlight using a box-shadow and `box-decoration-break` which is slightly different to how we've done it previously. This allows for the begining and end of wrapped lines to still have some padding. In older browsers that don't support `box-decoration-break` it falls back to having the start and end of lines tight with the end of the highlight. This looks less good visually, but it's in line with how our highlighted text currently looks in the main contribs banner. I found this method [here](https://css-tricks.com/multi-line-padded-text/#aa-fabien-doirons-box-shadow-method).
**`box-decoration-break` is supported (96.83% of …
=> Allow highlighted text to be customised in the moment template banner

packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerCloseButton.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerHeader.tsx, packages/modules/src/modules/banners/postElectionAuMoment/PostElectionAuMomentAlbaneseBanner.tsx
This change makes some tweaks to the moment template banner layout given we've now had design feedback from Jade & Alex.
I also updated the Albanese banner to simplify it given that we now need just a single image that works at all breakpoints. We should be able to do the same with the two other post election banners, but we just need some creatives with a slightly different aspect ratio to make them play nicer with the new layout. I'll raise a separate PR to address those changes.
|mobile|mobile medium|tablet|desktop|leftCol|wide|
|------|-------------|------|-------|-------|----|
|<img width="331" alt="Screenshot 2022-05-18 at 15 40 54" src="https://user-images.githubusercontent.com/17720442/169069316-c8dfdd4c-6129-4e4c-a643-599f859e8317.png">|<img width="384" alt="Screenshot 2022-05-18 …
=> Moment template layout tweaks

cdk/lib/__snapshots__/dotcom-components.test.ts.snap, cdk/lib/dotcom-components.ts, packages/server/src/lib/superMode.ts, packages/server/src/utils/cloudwatch.ts
This PR introduces the use of cloudwatch metrics for alarms.
This is to alert us to internal errors, e.g. if it fails to fetch super mode data but can still serve requests.
For now it's just writing a metric for super mode failures (and alerting when an error happens), but in follow up PRs we can add more.
In particular, we're about to start fetching channel tests data from dynamodb - this can be a new metric/alarm.
=> Cloudwatch metrics/alarms

packages/modules/src/modules/banners/postElectionAuMoment/PostElectionAuMomentHungBanner.tsx, packages/modules/src/modules/banners/postElectionAuMoment/PostElectionAuMomentMorrisonBanner.tsx
Update post Australian election banner images, specifically the hung Parliament & Morrison win variants (we updated the Albanese win image in #700). We now have an established aspect ratio (370 x 310) for the image from tablet upwards. This means we only need a single image for all the breakpoints and the template should always work provided the image is the correct size.
=> Update post election aus banner images (hung parliament & morrison win)

packages/modules/src/modules/banners/contributions/ContributionsBannerReminderSignedIn.tsx, packages/modules/src/modules/banners/contributions/ContributionsBannerReminderSignedOut.tsx, packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.stories.tsx, packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerCtas.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerReminder.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerReminderSignedOut.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerVisual.tsx, packages/modules/src/modules/banners/momentTemplate/settings.ts, packages/modules/src/modules/banners/postElectionAuMoment/settings.ts, packages/modules/src/modules/shared/Reminders.tsx
This change adds support for `ContributionsReminder` secondary cta type to the moment template banner. It's a slightly simplified version of the one in the main contributions  banner as it doesn't yet support showing a simplified version for signed in users. We can add that as a follow up, here's the [wip branch](https://github.com/guardian/support-dotcom-components/tree/tp-moment-banner-template-with-reminders-signed-in).
|Closed|Open|
|------|----|
|![Screenshot 2022-05-23 at 09 48 20](https://user-images.githubusercontent.com/17720442/169783002-85e7d1c2-5ee7-4ce8-ac21-12dde7a0821f.png)|![Screenshot 2022-05-23 at 09 48 28](https://user-images.githubusercontent.com/17720442/169782943-205289a5-2a19-4951-8421-343c040e4bf7.png)|
|Without image|With image|
|-------------|----------| …
=> Add reminder sign ups to the moment template banner

packages/server/src/tests/banners/bannerSelection.ts
We want automatic redeploys again
Reverts guardian/support-dotcom-components#703
=> Revert "Disable scheduled banner deploys in AU"

packages/modules/src/lib/replaceArticleCount.tsx, packages/modules/src/modules/banners/common/types.tsx, packages/modules/src/modules/banners/signInPrompt/SignInPromptBanner.stories.tsx, packages/modules/src/modules/banners/signInPrompt/SignInPromptBanner.tsx
Added a new type of banner which is intended to prompt users to sign in / register so they can benefit from a contribution they have made.
In draft until /pull/665 is merged
I couldn't link this PR to the trello card correctly, so here's a link instead: https://trello.com/c/u0L4ZDqF/3956-sign-in-after-checkout-visual-aspect-of-the-banner-s
Using Storybook
=> Sign in after checkout banner (Storybook only)

packages/server/src/factories/test.ts, packages/server/src/lib/ab.test.ts, packages/server/src/lib/targetingTesting.test.ts, packages/server/src/tests/amp/ampEpicModels.ts, packages/server/src/tests/amp/ampEpicSelection.test.ts, packages/server/src/tests/amp/ampEpicSelection.ts, packages/server/src/tests/banners/DefaultContributionsBannerTest.ts, packages/server/src/tests/banners/bannerSelection.test.ts, packages/server/src/tests/banners/bannerSelection.ts, packages/server/src/tests/banners/bannerTests.ts, packages/server/src/tests/banners/channelBannerTests.ts, packages/server/src/tests/banners/propensityModelTest/propensityModelTest.ts, packages/server/src/tests/epics/epicSelection.test.ts, packages/server/src/tests/epics/epicSelection.ts, packages/server/src/tests/epics/fallback.ts, packages/server/src/tests/epics/inEpicPayments/build.ts, packages/server/src/tests/headers/headerSelection.test.ts, packages/server/src/tests/headers/headerSelection.ts, packages/server/src/tests/testsStore.ts, packages/shared/src/factories/test.ts, packages/shared/src/types/abTests/banner.ts, packages/shared/src/types/abTests/epic.ts, packages/shared/src/types/abTests/header.ts, packages/shared/src/types/abTests/shared.ts
The `isOn` field has been deprecated in favour of `status` - https://github.com/guardian/support-admin-console/pull/345
This PR migrates SDC to use `status`.
It also excludes tests with a status of `Archived`, as we will soon be using this field for archiving of tests.
=> Use status field instead of isOn

packages/modules/src/modules/banners/signInPrompt/SignInPromptBanner.stories.tsx, packages/modules/src/modules/headers/SignInPromptHeader.stories.tsx, packages/modules/src/modules/headers/SignInPromptHeader.tsx, packages/server/src/tests/headers/headerSelection.ts
Follow up to #665 and #710, minor copy and design updates
Can test in storybook for design changes, I don't feel it's worth manually testing the copy changes.
(same as above, there wasn't a difference previously)
=> Sign in after checkout copy changes

packages/modules/src/modules/banners/guardianWeekly/GuardianWeeklyBanner.tsx
**Do not merge until ML test is over and Marketing is ready! (expected date 08/06)**
This updates the images for the Guardian Weekly banner to reflect a 50% off offer.
(disregard copy mentioning 30% off)
**Mobile**
**Tablet**
**Desktop**
=> Updating images for GW banner

packages/modules/src/modules/banners/common/types.tsx, packages/modules/src/modules/banners/contributions/ContributionsBanner.tsx, packages/modules/src/modules/banners/researchSurveyBanner/ResearchSurveyBanner.stories.tsx, packages/modules/src/modules/banners/researchSurveyBanner/ResearchSurveyBanner.tsx, packages/server/src/tests/banners/bannerSelection.ts, packages/server/src/tests/banners/bannerTests.ts, packages/server/src/tests/banners/channelBannerTests.ts, packages/server/src/tests/banners/researchSurveyBannerTest.ts, packages/shared/src/config/modules.ts, packages/shared/src/types/abTests/banner.ts
A 'test' with just a control variant, linking to a research survey. We want to find out if we can use banners for this purpose.
The test is in banner channel 2. It targets 5% of the audience. It is only enabled from tues-thurs, to avoid the banner redeploy times, as we don't want users to see it more than once.
=> Research survey banner

packages/server/src/tests/epics/usTopReaderCopy/index.ts
the auto-merge introduced a type error, causing the build to fail
Edit - I've also set the `usTopReaderCopyTest` test to `Draft` for now while there's some uncertainty about AB tests
=> Fix top reader config

packages/shared/src/types/props/banner.ts, packages/shared/src/types/props/epic.ts, packages/shared/src/types/props/header.ts
Add `.nullable()` calls to the props schemas for epics, banners, and headers. A change on the admin console ([pr](https://github.com/guardian/support-admin-console/pull/358)) made it so `null`s were explicitly written to the dyanmo table. This is causing our prop parsing to fail. As a quick fix, we're updating the components to allow `null`s in the props data. We can revisit for a better fix next week.
=> Add nullable to props parsing

packages/server/src/tests/epics/usTopReaderCopy/index.ts
Turn on hardcoded `usTopReaderCopyTest` on the Epic.
=> Turn on usTopReaderCopyTest

packages/server/src/tests/epics/epicProfileWithImageTest_eu-row.ts, packages/server/src/tests/epics/epicProfileWithImageTest_uk-aus.ts, packages/server/src/tests/epics/epicProfileWithImageTest_us.ts
Following on from the hardcoded test to use an image and byline in a targeted Epic, Marketing have asked that we push forward to show the V2 variant (image + byline) to all users reading articles concerning the Ukraine war.
This PR removes the CONTROL and V1 variants from all three regionally targeted hardcoded tests to make this happen.
=> Update the Harding hardcoded epic tests

packages/modules/src/modules/banners/guardianWeekly/GuardianWeeklyBanner.tsx
This updates the images for the Guardian Weekly banner. The new images do not have a roundel for savings/offers, these can be included in the copy of the banner so that we do not need to change the images too often until we add tooling for changing images.
**Mobile**
**Tablet**
**Desktop**
=> Replace GW image in banner

packages/server/src/lib/targeting.test.ts, packages/server/src/lib/targeting.ts, packages/server/src/payloads.ts, packages/server/src/tests/epics/epicSelection.test.ts, packages/server/src/tests/epics/epicSelection.ts
This condition isn't necessary. It was originally intended to target specific epic tests to LIVEBLOG and ARTICLE types.
But for liveblogs, the client hits a different endpoint which uses a separate tests list.
=> Do not check epicType in epic selection

packages/modules/src/modules/banners/common/BannerWrapper.tsx, packages/modules/src/modules/banners/contributions/ContributionsBanner.stories.tsx, packages/modules/src/modules/banners/contributions/ContributionsBannerTopReaderArticleCountV1.tsx, packages/modules/src/modules/banners/contributions/ContributionsBannerTopReaderArticleCountV2.tsx, packages/server/src/tests/banners/bannerTests.ts, packages/server/src/tests/banners/topReaderArticleCount/content.ts, packages/server/src/tests/banners/topReaderArticleCount/index.ts, packages/shared/src/config/modules.ts
Adds the top reader article count test for banners. The test is in 'Draft' status. We can create a follow up PR to set the test live (will happen after upcoming investigation banner).
[**Trello card**](https://trello.com/c/xWhZsLrt/524-top-reader-banner-test)
|CONTROL|V1_AC_LEAD|V2_CONGRATS_LEAD|
|-------|----------|----------------|
|<img width="992" alt="Screenshot 2022-07-04 at 16 17 38" src="https://user-images.githubusercontent.com/17720442/177183031-098b5eae-b5e0-425b-b546-9e983ce6d275.png">|<img width="992" alt="Screenshot 2022-07-04 at 16 17 45" src="https://user-images.githubusercontent.com/17720442/177183039-c7b96b16-5624-4f2d-8ed6-a8456087ef51.png">|<img width="992" alt="Screenshot 2022-07-04 at 16 17 49" src="https://user-images.githubusercontent.com/17720442/177183042-037b31e3 …
=> Top reader banner test

packages/server/src/tests/epics/epicProfileWithImageTest_eu-row.ts, packages/server/src/tests/epics/epicProfileWithImageTest_uk-aus.ts, packages/server/src/tests/epics/epicProfileWithImageTest_us.ts
Adds the `news/series/uber-files` tag to each hardcoded test's excludedTagIds array
We don't want the Herding message appearing under uber stories
=> Exclude tests from articles tagged news/series/uber-files

packages/dotcom/package.json, packages/modules/src/modules/banners/localStorage.ts, packages/modules/src/modules/banners/signInPrompt/SignInPromptBanner.tsx, packages/server/src/lib/targetingTesting.test.ts, packages/server/src/tests/banners/bannerSelection.test.ts, packages/server/src/tests/banners/bannerSelection.ts, packages/server/src/tests/banners/bannerTests.ts, packages/server/src/tests/banners/channelBannerTests.ts, packages/server/src/tests/banners/signInPromptTests.ts, packages/server/src/tests/headers/headerSelection.ts, packages/shared/src/config/modules.ts, packages/shared/src/types/abTests/banner.ts, packages/shared/src/types/abTests/header.ts, packages/shared/src/types/abTests/shared.ts, packages/shared/src/types/props/banner.ts, packages/shared/src/types/purchaseInfo.ts, packages/shared/src/types/targeting/banner.ts, packages/shared/src/types/targeting/header.ts, packages/shared/src/types/targeting/shared.ts
[Trello card](https://trello.com/c/KbfJbwmK/4035-sign-in-after-checkout-banner-new-banner-to-prompt-recent-new-supporters-to-sign-in-s) for extra context.
Added a new type of banner which is intended to prompt users to sign in / register so they can benefit from a contribution they have made.
Can be tested with DCR by sending the appropriate values in the banner request payload.
Tested locally
=> Implement selection logic for sign in prompt banner

packages/modules/src/modules/banners/signInPrompt/SignInPromptBanner.stories.tsx, packages/modules/src/modules/banners/signInPrompt/SignInPromptBanner.tsx, packages/modules/src/modules/headers/SignInPromptHeader.stories.tsx, packages/modules/src/modules/headers/SignInPromptHeader.tsx, packages/server/src/tests/banners/signInPromptTests.ts, packages/server/src/tests/headers/headerSelection.ts
- Updates the copy of the Sign In Prompt header and banner
- Updates the header animation to end statically on the main perceived strongest benefit. 
- Design updates on the header
**Banner:**
**>Desktop Header**
**Tablet Header**
**Banner:**
**>Desktop Header**
**Tablet Header**
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/peo …
=> Update copy and design of Sign In Prompt header/banner

packages/modules/src/modules/epics/ContributionsEpic.stories.tsx, packages/server/src/tests/epics/epicLenoreWithImageTest_aus.ts
This PR updates the image used in the hardcoded Lenore Epic test, which is currently live.
The updated image has been tested in Storybook. Screenshots:
=> Lenore Aus hardcoded Epic test - update byline image

packages/server/src/payloads.ts
A small PR to disable the US top reader copy hardcoded test
=> Disable US-top-reader-copy hardcoded epic test

packages/modules/src/modules/banners/common/BannerWrapper.tsx, packages/modules/src/modules/banners/signInPrompt/SignInPromptBanner.tsx, packages/modules/src/modules/headers/HeaderWrapper.tsx, packages/modules/src/modules/headers/SignInPromptHeader.tsx, packages/shared/src/lib/tracking.test.ts, packages/shared/src/lib/tracking.ts
The new Sign In Prompt Header and Banner redirect users to profile.theguardian.com.
This PR adds:
- CTA click tracking for both components. 
- `componentEventParams` as query params on redirects to profile subdomain so that we can track how many users actually complete registration or sign in via the check out sign in prompt header/banner
**_Note:_** the code could be dryer, but I think best to keep support vs profile code separate for easy removal/deletion
-   [ ] [Colour contrast …
=> Add tracking to Sign In Prompt Banner / Header

packages/server/src/payloads.ts
Marketing have asked us to suspend the currently running Harding and Lenore Epic-with-profile-images tests until further notice.
This PR removes the tests from the Epic hardcoded tests array, but does not clean out any of the code/files associated with creating the tests
=> Remove hardcoded profile epic tests from payloads file

packages/modules/src/modules/epics/ContributionsEpic.tsx, packages/modules/src/modules/epics/ContributionsEpicArticleCountAboveWithOptOut.tsx, packages/server/src/lib/history.ts, packages/server/src/payloads.ts, packages/server/src/tests/epics/environmentArticleCountTest.ts, packages/server/src/tests/epics/epicSelection.test.ts, packages/server/src/tests/epics/epicSelection.ts, packages/shared/src/types/abTests/epic.ts, packages/shared/src/types/abTests/shared.ts, packages/shared/src/types/props/epic.ts
Last year we ran [a test](https://github.com/guardian/support-dotcom-components/pull/557) to display article count based on the environment tag.
This PR adds a similar hardcoded test.
It's simpler because it only has 1 variant (the original test had an extra variant for showing the environment count in the body copy as well as the main count above).
I've also done some refactoring, as the "above" article count logic has evolved since the last test:
1. removed the `aboveArticleCountByTag` field. This hasn't been used since the original test, and was specifically to enable the two variants (one of which put the count in the body).
2. adds the `separateArticleCount.countType` field to decide which article count (`for52Weeks` vs `forTargetedWeeks`) to use, per variant. This enables us to show …
=> Epic environment article count test

cdk/lib/__snapshots__/dotcom-components.test.ts.snap, cdk/lib/dotcom-components.ts
SDC failed to scale-out during high traffic after a big news event.
We do have autoscaling enabled, but for some reason it did not scale-out. Instead, instances intermittently failed health checks and were replaced.
Scale-out should happen at 50% cpu utilization but didn't - perhaps because instances kept failing health checks.
Here's the period where service was degraded and instances were being replaced:
Average cpu utilization is typically in the 20s, so a 40% threshold should only trigger scale-out during high traffic moments -
=> Lower autoscaling threshold to 40% cpu

packages/modules/src/modules/epics/ContributionsEpic.tsx, packages/modules/src/modules/epics/ContributionsEpicButtons.tsx, packages/modules/src/modules/epics/ContributionsEpicCtas.tsx, packages/modules/src/modules/epics/ContributionsLiveblogEpic.stories.tsx, packages/modules/src/modules/epics/ContributionsLiveblogEpic.tsx
Marketing have requested the ability to add a Reminder CTA button to Liveblog Epics. This PR enables the reminder CTA button, form and accompanying functionality work in Liveblog Epic messages.
To make this work, I've refactored the Contributions CTA+Reminder buttons into their own component which can be shared between classic Contributions epics, and Liveblog Epics
A second PR in the SAC repo makes the functionality available to Marketing in RRCP - https://github.com/guardian/support-admin-console/pull/387
**Screenshots**
=> Add reminder CTA option to Liveblog Epic variants

packages/modules/src/modules/banners/climateCrisisMoment/visual/ThermometerMercury.tsx
With @michaelbjacobson 
On pages rendered by frontend (i.e fronts) the close button doesn't work because of a javascript error originating from the spring animation library.
```
Uncaught (in promise) TypeError: e is undefined
Ns react-spring-core.esm.js:1831
```
As a quick fix we're disabling animation, using the svg from the animation's end state.
=> disable animation in climate banner

packages/modules/src/modules/epics/ContributionsEpicArticleCountAboveWithOptOut.tsx
I'm not sure why but safari adds `margin-top: 2px` to the article count cta:
Fixed:
=> Fix article count button margin on safari

packages/dotcom/package.json, packages/server/src/lib/targeting.test.ts, packages/server/src/lib/targeting.ts, packages/server/src/tests/banners/bannerSelection.ts, packages/server/src/tests/epics/epicSelection.test.ts, packages/server/src/tests/epics/epicSelection.ts, packages/server/src/tests/headers/headerSelection.ts, packages/shared/src/types/targeting/banner.ts
We never want recent single contributors to see a message.
This PR uses the `lastOneOffContributionDate` provided by the client (dotcom).
- epic and header - already have `lastOneOffContributionDate` in the targeting payload (for targeting old contributors)
- banner did not already have `lastOneOffContributionDate`
Header and banner shared targeting logic (the `audienceMatches` function), but the epic targeting logic is separate. We should really consolidate them, but now is not the time!
This will require an npm release, as DCR/frontend will need to include `lastOneOffContributionDate` in the payload for banners.
=> Exclude recent single contributors from all messaging

packages/server/src/server.ts
when running locally we serve the modules from the node server. My recent refactor broke this
=> Fix modules when running locally

packages/server/src/api/bannerRouter.ts, packages/server/src/channelSwitches.ts, packages/server/src/tests/banners/bannerSelection.test.ts, packages/server/src/tests/banners/bannerSelection.ts
We've been asked to disable scheduled deploys temporarily.
This is the second time, so I'm adding a switch (`enableScheduledBannerDeploys`) which can later be controlled from the RRCP channel switches page.
=> Switch to disable scheduled banner deploys

cdk/lib/__snapshots__/dotcom-components.test.ts.snap, cdk/lib/dotcom-components.ts
Most of the time when this alarm is triggered, the 5XX % is barely over 0.1%. During times with lower traffic this means a single 5XX can trigger the alarm.
Last week we had a genuine issue (an instance became unresponsive) and the alarm was triggered with 5XXs at 2.47%.
5XX counts over the last week (note the genuine issue on 5/10) -
=> Raise 5xx alarm threshold to 0.5%

packages/modules/src/modules/epics/ContributionsEpic.stories.tsx, packages/modules/src/modules/epics/ContributionsEpic.tsx, packages/shared/src/lib/tracking.test.ts, packages/shared/src/lib/tracking.ts
Marketing would like to run a test around including links to the support site in the body of the epic. In order to evaluate the performance we need to be able to track these links.
This PR augments links to the support site in the body of the epic, adding the same tracking params we add to the CTA(s). We also add an additional `body-link` label, in order to be able to distinguish click throughs on these links from the CTA.
`$ yarn test`
Also add a link to the epic body in storybook and hover to see tracking params added.
- …
=> Epic body link tracking

packages/modules/src/modules/banners/common/BannerWrapper.tsx, packages/modules/src/modules/banners/common/types.tsx, packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx
Currently the moment banner ignores the flag for enabling the article count under the heading.
Tested in CODE
=> Use separateArticleCount toggle in moment banner

packages/shared/src/lib/geolocation.ts
Marketing have asked that we remove Israel from the list of country names that can be displayed in the channels
=> Change country names list

packages/modules/src/modules/banners/auBrandMoment/components/getAuBrandMomentBanner.tsx, packages/modules/src/modules/banners/environmentMoment/EnvironmentMomentBanner.tsx, packages/modules/src/modules/banners/globalNewYear/components/getGlobalNewYearBanner.tsx, packages/modules/src/modules/banners/investigationsMoment/InvestigationsMomentBanner.tsx
Some banners have a "separate article count" feature, typically appearing as a subheading, and separate from the rest of the copy. This feature is toggled from RRCP.
Some of the Moment banners with this feature do not respect the toggle. This PR changes them to check the `separateArticleCount` field.
=> Use separateArticleCount prop in banners

packages/modules/src/modules/epics/ContributionsEpic.tsx, packages/modules/src/modules/epics/ContributionsEpicCtas.tsx
This bug was introduced during a refactor to share the ctas component with the liveblog epic (https://github.com/guardian/support-dotcom-components/pull/751)
The url querystring is supposed to include info about which choice cards were chosen.
=> Fix epic choice cards

packages/dotcom/package.json, packages/server/src/tests/headers/headerSelection.test.ts, packages/shared/src/types/targeting/header.ts
This field has not been used since we integrated SDC with RRCP for headers. We use countryCode instead.
There are follow-up changes to remove the field from DCR + frontend.
(this change was prompted by a new edition - https://github.com/guardian/support-dotcom-components/pull/778)
=> Remove edition field from header targeting

packages/modules/src/modules/banners/hocs/withCloseable.tsx
A small change that should ensure that when a user closes a marketing banner (by whatever means) the tabbing focus returns to the top of the page
https://user-images.githubusercontent.com/5357530/198039755-72d63f7b-1075-4681-9e94-9a48558ef4ee.mov
[close-banner-demo_2022-11-04.webm](https://user-images.githubusercontent.com/5357530/199939339-82cc61e8-5fd7-4da7-ab1a-d45691d94bbe.webm)
=> Refocus on document.body when banner closes

packages/modules/src/modules/banners/environmentMoment/EnvironmentMomentBanner.tsx, packages/modules/src/modules/banners/environmentMoment/components/EnvironmentMomentBannerHeader.tsx
Marketing want to test this old banner against the new "climate banner", for Cop27.
We haven't committed to making this configurable yet.
=> Change hardcoded environment banner heading

packages/modules/src/modules/banners/common/BannerWrapper.tsx, packages/server/src/api/epicRouter.ts, packages/shared/src/lib/reminderFields.ts
This changes adds reminder fields to be used for US readers in the period leading to Giving Tuesday (November 29).
The Epic and Banner reminder cta now says 'Remind me on Giving Tuesday'
Has been tested on CODE.
For Epic and Banner with reminders, change geolocation and confirm US shows the Giving Tuesday reminder message, other countries will see the generic 'Remind me in {month}'.
**Epic**
| US | UK (also tested in CA and FR) |
| ---- | ---- |
| ![Screenshot 2022-11-07 at 09 24 37](https://user-images.githubusercontent.com/99180049/200277315-532b57de-8686-429e-8354-eaa5f2223e6e.png) | ![Screenshot 2022-11-07 at 09 23 58](https://user-images.githubusercontent.com/99180049/200277365-6f51c8a7-bd81-41a4-9235-aab3d2f68d54.png) |
| ![Screenshot 2022-11-07 at 09 24 …
=> Giving Tuesday 2022 reminders

riff-raff.yaml
Removes bucket names from Riff Raff config as recommended by DevX. By default the bucket will be discovered by looking it up in parameter store.
Deploy to CODE via Riff Raff.
=> Removes bucket names from Riff Raff config

packages/modules/src/modules/epics/ContributionsEpic.tsx
Currently it only underlines on hover, so it's not obvious it's a link.
Before:
After:
=> Underline links in epic body

.github/workflows/snyk.yml
Removes the Snyk schedule, which is unnecessary and will cause the workflow to become suspended after 60 days of inactivity on the repo!
=> Remove Snyk Schedule

packages/server/src/lib/targeting.test.ts, packages/server/src/lib/targeting.ts, packages/server/src/tests/banners/bannerSelection.ts, packages/server/src/tests/epics/epicSelection.test.ts, packages/server/src/tests/epics/epicSelection.ts, packages/server/src/tests/headers/headerSelection.ts
- Reverts changes done in #757 by removing `isRecentOneOffContributor`.
- The `lastOneOffContributionDate` in the banner is not removed.
=> Re-enable targeting of recent single contributors

packages/modules/src/modules/banners/utils/storybook.ts, packages/modules/src/modules/epics/ContributionsEpic.stories.tsx, packages/server/src/lib/fetchTickerData.ts, packages/server/src/tests/amp/ampEpicSelection.test.ts, packages/server/src/tests/amp/ampEpicSelection.ts, packages/shared/src/types/props/shared.ts
For the first time we want to run two tickers concurrently.
We're creating a separate ticker stack for the 2nd ticker. The 2 stacks will output to different files. (Changing the ticker calculator to handle multiple campaigns would be a bigger change).
SDC needs to poll both ticker files and use the correct one when returning channel message data to a client.
The RRCP will require users to select which ticker to use for each channel AB test.
This PR:
1. adds a `name` field to the `TickerSettings` type. These settings come from RRCP, so we'll need to add the name field there as well. (Note - in future we could link this name to a campaign, but let's keep it simple for now)
2. Updates the `TickerDataProvider` to poll both ticker files. The `name` field corresponds to a .json file. These are …
=> US + AU ticker data

packages/server/src/tests/banners/channelBannerTests.ts, packages/shared/src/types/abTests/banner.ts
There's some extra wiring required to get `tickerSettings` from the banner config.
I also added `signedInStatus`, which I noticed was missing as well.
I'll create a card to look into getting rid of this logic, I'm not sure it adds anything.
=> Fix banner ticker

packages/shared/src/types/props/banner.ts
dynamodb stores `tickerSettings` as a null, but the validation in SDC only allows it to be undefined.
We need a better way of handling optional fields!
=> Fix banner tickerSettings validation

packages/modules/src/modules/banners/climateCrisisMoment/ClimateCrisisMomentBanner.stories.tsx, packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerTicker.tsx, packages/modules/src/modules/banners/momentTemplate/settings.ts, packages/modules/src/modules/banners/postElectionAuMoment/PostElectionAuMomentBanners.stories.tsx, packages/modules/src/modules/banners/usEoyMoment/UsEoyMomentBanner.stories.tsx
Following a recent PR to add a ticker to the moment template https://github.com/guardian/support-dotcom-components/pull/796. This PR allows for the ticker styling to be configurable via props.
=> Add moment template ticker styling settings

packages/modules/src/modules/banners/usEoyMoment/UsEoyMomentBanner.tsx
This adds the required ticker styling settings following https://github.com/guardian/support-dotcom-components/pull/802, in order to display the ticker on the US EOY banner
=> Fix - add ticker styling settings to US EOY banner

packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerTicker.tsx
=> Fix banner ticker progress bar

packages/modules/src/modules/epics/ContributionsEpic.tsx
DCR overrides `strong` tag styling
=> fix bold in epic

packages/server/src/tests/banners/DefaultContributionsBannerTest.ts, packages/server/src/tests/banners/bannerSelection.test.ts, packages/server/src/tests/banners/bannerSelection.ts, packages/server/src/tests/banners/channelBannerTests.ts, packages/server/src/tests/banners/signInPromptTests.ts, packages/shared/src/lib/tracking.ts, packages/shared/src/types/abTests/banner.ts
The model fetched from SAC differs from the internal SDC model. This is fine - the SDC model contains data and functions that are not relevant to SAC.
Currently there's some logic for transforming between these two models that needs to be updated any time we add a field. It's easy to forget ([recent example](https://github.com/guardian/support-dotcom-components/pull/800)).
This PR simplifies things to avoid this.
1. renames `minPageViews` to `minArticlesBeforeShowingBanner`, to be consistent with SAC
2. renames `moduleName` to `template`, to be consistent with SAC
3. Replaces the `RawTestParams` and `RawVariantParams` types with `BannerTestFromTool` and `BannerVariantFromTool` - hopefully a better name. I've also defined these in terms of the SDC `BannerTest` + `BannerVariant` models by …
=> Simplify banner test config processing

packages/shared/src/types/props/banner.ts, packages/shared/src/types/props/epic.ts, packages/shared/src/types/props/header.ts, packages/shared/src/types/props/shared.ts
We've had a couple of instances ([e.g.](https://github.com/guardian/support-dotcom-components/pull/801)) of client-side validation of props failing because a field is stored as `null` in dynamodb, but the zod validator only defines it as `optional` (which allows `undefined` but not `null`).
This PR changes all optional fields to `nullish`, which allows both undefined and null:
`nullish: <This extends this = this>() => ZodNullable<ZodOptional<This>>;`
This isn't perfect - it's still possible for a dev to add a new field as `optional()` and cause validation to fail. But now that all other fields are defined as `nullish`, it should be pretty obvious what the convention is.
If we're still not happy with this then I think the solution is to strip out nulls at the point of querying dynamodb …
=> Use nullish in zod validators

packages/shared/src/lib/reminderFields.test.ts, packages/shared/src/lib/reminderFields.ts
Reverts guardian/support-dotcom-components#813
=> Revert "replaces the normal reminder month logic that decides on either 1 or …"

packages/modules/src/modules/banners/common/types.tsx, packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx, packages/modules/src/modules/banners/momentTemplate/buttonStyles.ts, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerBody.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerCtas.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerHeader.tsx, packages/modules/src/modules/banners/momentTemplate/settings.ts, packages/modules/src/modules/banners/usEoyMomentV3/UsEoyMomentBannerV3.stories.tsx, packages/modules/src/modules/banners/usEoyMomentV3/UsEoyMomentBannerV3.tsx, packages/modules/src/modules/banners/usEoyMomentV3/UsEoyMomentBannerVisualV3.tsx, packages/server/src/tests/banners/channelBannerTests.ts, packages/shared/src/config/modules.ts, packages/shared/src/types/abTests/banner.ts
This adds v3 of the US EOY moment banner.
| mobileMedium | tablet | desktop | Wide |
|----------|--------|---------|------|
| <img width="278" alt="Screenshot 2022-12-09 at 05 15 08" src="https://user-images.githubusercontent.com/44685872/206629341-32a92fde-4f7f-4239-b76e-913e28302f71.png"> | <img width="440" alt="Screenshot 2022-12-09 at 05 15 39" src="https://user-images.githubusercontent.com/44685872/206629346-d99b22a6-4c45-4779-a6f9-c4d2730cba53.png"> | <img width="586" alt="Screenshot 2022-12-09 at 05 16 08" src="https://user-images.githubusercontent.com/44685872/206629349-9a2c4967-9a67-4207-a63b-b57dd3c9ef28.png"> | <img width="815" alt="Screenshot 2022-12-09 at 05 16 33" src="https://user-images.githubusercontent.com/44685872/206629355-b16340c7-35b0-44e8-8ae5-f16e3c8c1d17.png"> |
=> Add US EOY banner v3

packages/modules/src/modules/banners/momentTemplate/buttonStyles.ts, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerBody.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerCtas.tsx, packages/modules/src/modules/banners/momentTemplate/settings.ts, packages/modules/src/modules/banners/usEoyMomentV3/UsEoyMomentBannerV3.stories.tsx, packages/modules/src/modules/banners/usEoyMomentV3/UsEoyMomentBannerV3.tsx
Following https://github.com/guardian/support-dotcom-components/pull/821 this adds highlighted text to the US EOY v3 banner and wraps banner ctas inside their flex container on smaller breakpoints. 
This also reverts some changes made in the previous PR around optional types as it would be best to tackle this separately. 
- To fulfil a request to add highlighted text to this banner
- The original requirement for the ctas on the moment template banner to be on one line has since changed
- Changes around optional and required types were made to tackle some inconsistencies in which template styling settings are optional or required. For example we require styling `secondaryCtaSettings` to always be defined but the `secondaryCta` element is optional. This would be best to handle separately
=> Add highlighted text to US EOY v3 banner

packages/modules/src/modules/banners/contributions/ContributionsBanner.tsx, packages/modules/src/modules/banners/contributions/ContributionsBannerMobile.tsx, packages/modules/src/modules/banners/contributions/ContributionsBannerSecondaryCta.tsx
Addresses a request from Marketing for the yellow contributions banner's CTA buttons to align horizontally beneath the messaging copy for screen widths below tablet, rather than stacking vertically as they currently do.
__Existing layout (LIVE site)__
__New layout (Storybook)__
For small screen sizes which need to fit in CTAs with longer copy, we will still stack the CTA buttons. Marketing have the ability to set shorter CTA copy for mobile screens, should the need to maintain horizontal alignment arise
=> Update yellow contributions banner mobile CTA positioning

packages/modules/src/modules/banners/auBrandMoment/components/AuMomentTemplateBannerArticleCount.tsx, packages/modules/src/modules/banners/auBrandMoment/components/AuMomentTemplateBannerArticleCountOptOut.tsx, packages/modules/src/modules/banners/auBrandMoment/components/AuMomentTemplateBannerBody.tsx, packages/modules/src/modules/banners/auBrandMoment/components/AuMomentTemplateBannerCloseButton.tsx, packages/modules/src/modules/banners/auBrandMoment/components/AuMomentTemplateBannerCtas.tsx, packages/modules/src/modules/banners/auBrandMoment/components/AuMomentTemplateBannerHeader.tsx, packages/modules/src/modules/banners/auBrandMoment/components/AuMomentTemplateBannerReminderSignedOut.tsx, packages/modules/src/modules/banners/auBrandMoment/components/AuMomentTemplateBannerVisual.tsx, packages/modules/src/modules/banners/auBrandMoment/components/getAuBrandMomentBanner.tsx
This renames the Australia brand moment banner files and variables within those files so as not to conflict with the moment template banner. 
The Australia brand moment is currently unused but may be needed in future and was first introduced in https://github.com/guardian/support-dotcom-components/pull/729. We'd attempted to build this banner using the moment template but it did not fit all of the requirements. So, the approach taken was to duplicate the moment template files and tailor them to the specific moment. This had left us with a fair few files that are similarly named, albeit in different folders e.g. `.../banners/auBrandMoment/components/MomentTemplateBannerBody.tsx` vs `.../banners/momentTemplate/components/MomentTemplateBannerBody.tsx`
=> Rename Australia brand moment banner files

packages/server/src/tests/banners/bannerDeploySchedule.test.ts, packages/server/src/tests/banners/bannerDeploySchedule.ts
Marketing have requested a change to the automated deployment times for banner channels, as follows:
```
Banner 1 (== channel 1 conversions banner): Sunday + Thursday (9:00AM)
Banner 2 (== channel 2 subscriptions banner): Tuesday (9:00 AM)
```
Question: how do we test this?
=> Update automated banner deploy times

packages/server/src/api/epicRouter.ts
Currently SDC includes a `variant` field in the response. This is [not used by the client](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/web/components/SlotBodyEnd/ReaderRevenueEpic.tsx#L128), and duplicates data that's already under the `props` field
After:
=> Remove redundant data from epic response

packages/modules/src/modules/epics/ContributionsEpic.stories.tsx, packages/modules/src/modules/epics/ContributionsEpic.tsx, packages/modules/src/modules/epics/ContributionsEpicChoiceCards.tsx, packages/shared/src/types/abTests/epic.ts
We've added a boolean `hideChooseYourAmount` attribute to the Contributions Amounts model generated by RRCP and stored in S3. This PR updates the Epic amounts choice card component to adapt its display accordingly.
The component has also been updated to display the appropriate number of amount choice buttons, dependant on the number of amount data points supplied to the component for a given particular region and contribution frequency
NOTE: this PR **must not be merged** until Marketing colleagues have been informed and given us the go-ahead to do so!
This PR is one of three PRs across three repos, all of which need to be merged at the same time:
+ PR in `support-admin-control` - https://github.com/guardian/support-admin-console/pull/428
+ PR in `support-dotcom-components` - …
=> Hide 'Other amount' button in Epic amounts choice card component

packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx
A sizing issue visible from tabletUrl width onwards, the background image (around certain breakpoints) can overlay the the CloseCta, making it not available to press.
Note: Check all affected template banners.
Before ->
After (button highlightable in green box when overlayed with image below it) ->
[Trello]
https://trello.com/c/bqPFo5Y5/1074-moment-banners-close-button-fix
=> Moment banner, close button raise above banner visual

packages/modules/src/modules/banners/ukraineMoment/UkraineMomentBanner.stories.tsx, packages/modules/src/modules/banners/ukraineMoment/UkraineMomentBanner.tsx, packages/server/src/tests/banners/channelBannerTests.ts, packages/shared/src/types/abTests/banner.ts
This PR corrects the 'Ukraine One Year On Banner Moment' enabling the RRCP Web Preview
[Trello]
https://trello.com/c/5Z1LPDKV/1042-ukraine-war-1-year-anniversary-campaign-build
Post->
| 375px | 740px | 980px | 1300+px 
|--------|---------|---------|---------|
| ![Screenshot 2023-02-13 at 10 13 01](https://user-images.githubusercontent.com/76729591/218431367-7bcb199b-ba01-4994-b9aa-3a85013f4430.jpg) | ![Screenshot 2023-02-13 at 10 18 13](https://user-images.githubusercontent.com/76729591/218432885-f3c12901-a574-449f-a7a4-85cfc6a2c88c.jpg) | ![Screenshot 2023-02-13 at 10 19 25](https://user-images.githubusercontent.com/76729591/218432029-b776ccd7-892f-4d1e-a9b3-3d42788351be.jpg) | ![Screenshot 2023-02-13 at 10 20 52](https://user-images.githubusercontent.com/76729591/218432289-0596ee3d-586d- …
=> Ukraine template banner web preview hi-res wide image 

packages/modules/src/modules/banners/ukraineMoment/UkraineMomentBanner.stories.tsx, packages/modules/src/modules/banners/ukraineMoment/UkraineMomentBanner.tsx
This PR corrects the 'Ukraine One Year On Banner Moment', higher resolution images and primary cta hover colour
[Trello]
https://trello.com/c/JVglKX6P/1088-update-images-and-hover-button-in-ukraine-banner
Post->
| 375px | 740px | 980px | 1300+px 
|--------|---------|---------|---------|
| ![Screenshot 2023-02-13 at 10 13 01](https://user-images.githubusercontent.com/76729591/218431367-7bcb199b-ba01-4994-b9aa-3a85013f4430.jpg) | ![Screenshot 2023-02-13 at 10 18 13](https://user-images.githubusercontent.com/76729591/218432885-f3c12901-a574-449f-a7a4-85cfc6a2c88c.jpg) | ![Screenshot 2023-02-13 at 10 19 25](https://user-images.githubusercontent.com/76729591/218432029-b776ccd7-892f-4d1e-a9b3-3d42788351be.jpg) | ![Screenshot 2023-02-13 at 10 20 …
=> Ukraine template banner change to hires images and primary hover color

packages/modules/src/modules/banners/globalNYMoment/GlobalNYMomentBanner.stories.tsx, packages/modules/src/modules/banners/globalNYMoment/GlobalNYMomentBanner.tsx, packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerVisual.tsx
This PR amends the 'Global New Year Banner Moment'
- 980px+ the image is aligned with the bottom of the banner
- 740px-979px the image is centred vertically.
- Non-confetti images used
[**Trello Card**](https://trello.com/c/ImZG9p6U/1086-new-year-banner-updates)
Pre->
| 320px | 375px | 740px | 980px | 1300+px 
|----------|--------|---------|---------|---------|
| ![Screenshot 2022-12-19 at 14 12 01](https://user-images.githubusercontent.com/76729591/208445896-7d674d27-76c9-4c75-9bc3-224217337a1f.png) | ![Screenshot 2022-12-19 at 14 12 12](https://user-images.githubusercontent.com/76729591/208445875-0e0892a2-8d9d-4292-85f0-f6f825afe825.png) | ![Screenshot 2022-12-19 at 14 12 28](https://user-images.githubusercontent.com/76729591/208445853-5fea2a24-3f2a-4989-91c4-fb00006a6b69.png) | …
=> New Year template banner image re-alignment re-size

packages/modules/src/hooks/useContributionsReminderEmailForm.ts, packages/modules/src/modules/utils/reminders.ts
Identity errors when email addresses are longer than 100 characters. This has been causing some alerts, so we’re adding server-side validation to handle long email addresses. This is the client-side counterpart to that validation.
See https://github.com/guardian/support-reminders/pull/61 for server-side validation.
On PROD, find a support reminder form and request a reminder to an email address longer than 100 characters – after some delay while the backend processes, an error will be returned. On this branch, the email address should be rejected immediately. 
This should decrease the number of errors we get from reminder signups.
If Identity change to support these long email addresses in future, our code will prevent them setting reminders even though they have an account – we will have …
=> Limit email address length for reminders

packages/modules/src/modules/banners/auElectionMoment/AusElectionMomentBanner.stories.tsx, packages/modules/src/modules/banners/ausEoyMoment/AusEoyMomentBanner.stories.tsx, packages/modules/src/modules/banners/ausEoyMoment/AusEoyMomentBanner.tsx, packages/modules/src/modules/banners/climateCrisisMoment/settings.ts, packages/modules/src/modules/banners/globalNYMoment/GlobalNYMomentBanner.stories.tsx, packages/modules/src/modules/banners/globalNYMoment/GlobalNYMomentBanner.tsx, packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerArticleCountOptOut.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerCloseButton.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerVisual.tsx, packages/modules/src/modules/banners/momentTemplate/settings.ts, packages/modules/src/modules/banners/postElectionAuMoment/settings.ts, packages/modules/src/modules/banners/ukraineMoment/UkraineMomentBanner.stories.tsx, packages/modules/src/modules/banners/ukraineMoment/UkraineMomentBanner.tsx, packages/modules/src/modules/banners/usEoyGivingTuesMoment/UsEoyGivingTuesMomentBanner.stories.tsx, packages/modules/src/modules/banners/usEoyGivingTuesMoment/UsEoyGivingTuesMomentBanner.tsx, packages/modules/src/modules/banners/usEoyMoment/UsEoyMomentBanner.stories.tsx, packages/modules/src/modules/banners/usEoyMoment/UsEoyMomentBanner.tsx, packages/modules/src/modules/banners/usEoyMomentV3/UsEoyMomentBannerV3.stories.tsx, packages/modules/src/modules/banners/usEoyMomentV3/UsEoyMomentBannerV3.tsx
This pulls up any conditional styling we had within child components of the `MomentTemplateBanner.tsx` up into the banner itself.  Some child components previously received a `bannerId` prop which has now been removed as it was used solely for conditional styling. The styles previously defined within these child components are now either configurable and have been added to the `BannerTemplateSettings` type or are now defined within the top-level banner component and passed down as props.
This change is a necessary first step towards the eventual transition to banners being configurable in the RRCP.
- Compare the moment template banner stories in this branch with the stories on the main branch
- Compare live banners on this branch on CODE with the main branch on PROD
No visual regressions …
=> Remove conditional styling in moment banner child components in favour of props

packages/modules/src/modules/banners/investigationsMoment/components/InvestigationsMomentBannerPolygon.tsx
This PR amends the 'Investigations Moment Banner'.
FIREFOX WIDTH/HEIGHT:AUTO AMMENDMENT
The JSX used to render the polygonal shapes on the Investigations Banner is repetitive and can be simplified  by creating two reusable react components for polygons in the top left and bottom right. These components are reactive based upon the breakpoints specified.
[**Trello Card**](https://trello.com/c/uA21eZ3Z/1154-investigative-banner-refactor-minimise-multiple-polygon-vector-components)
=> Investigations Moment Banner re-factor - browser fix

packages/modules/src/modules/banners/choiceCardsBanner/components/ChoiceCardAmountButtons.tsx, packages/modules/src/modules/banners/choiceCardsBanner/components/ChoiceCards.tsx
Following https://github.com/guardian/support-dotcom-components/pull/859 this alters the default padding for the choice card amount buttons from source. Between tablet and desktop padding is removed from the left and right to ensure the button copy remains on one line.
=> Choice card banner amounts buttons padding fix

packages/server/src/tests/banners/bannerSelection.test.ts, packages/server/src/tests/banners/bannerSelection.ts
Don't show banner messages on Taylor Report pages. This is a temporary change and will be reverted in future.
=> Don't show banner messages on Taylor Report pages

packages/modules/src/modules/banners/choiceCardsBanner/ChoiceCardsBanner.stories.tsx, packages/modules/src/modules/banners/choiceCardsBanner/ChoiceCardsBanner.tsx, packages/modules/src/modules/banners/choiceCardsBanner/ChoiceCardsBannerBlue.tsx, packages/modules/src/modules/banners/choiceCardsBanner/ChoiceCardsBannerYellow.tsx, packages/modules/src/modules/banners/choiceCardsBanner/choiceCardsBannerStyles.ts, packages/modules/src/modules/banners/choiceCardsBanner/components/ChoiceCardAmountButtons.tsx, packages/modules/src/modules/banners/choiceCardsBanner/components/ChoiceCards.tsx, packages/modules/src/modules/banners/choiceCardsBanner/components/ChoiceCardsBannerArticleCount.tsx, packages/modules/src/modules/banners/choiceCardsBanner/components/SupportCta.tsx, packages/modules/src/modules/banners/choiceCardsBanner/components/paymentFrequencyTabs/PaymentFrequencyTabsBox.tsx
Add customisable border top line for the choice banner. Blue has a line, Yellow does not. Colour matches header colour.
[**Trello Card - PriceCard Banner Keyline**](https://trello.com/c/YvEj4iYh/1182-add-keyline-to-choice-cards-in-banner)
Visual Alterations To Banner
- Close CTA & SVG colour to Brand400 (blue)
- Continue CTA colour to BrandAlt400 (yellow)
- Remove lower grey tab on selected tab
- Round corners of (10px) price buttons
- Spacing 12px between buttons except 1st -> 2nd row 8px
- Text Spacing 16px->Title>12px->ArticleCount->4px->Paragraph>16px
- Price Card responsive up to tablet (740px)
- Price Card 340px up to 980px, 380px beyond
- Head font change at 740px->980px
[**Trello Card - PriceCard Banner Review**](https://trello.com/c/RiFRoHBg/1179-engineering-design-review-for-in-b …
=> Price Card Banner Keyline & Design Review Tweaks

packages/modules/src/modules/banners/choiceCardsBanner/choiceCardsBannerStyles.ts
Based on the designs, this logo should be visible in the tablet breakpoint and not in the mobile medium breakpoint: looks like we made a mistake with the breakpoint when we made this in the first place.
Interestingly, this is a change from some other banners: the guardian weekly and print, for example. Those both display the logo from mobileMedium. Not having seen the designs, I don’t know whether that’s correct, but it has been that way for a long time so I assume so – I’ll check, but I think we can merge this in the meantime.
Run `yarn modules storybook`, find the choice cards banner in the left hand menu under Subscriptions, use the button at the top to change the display size to check the break points.
Mobile medium:
Tablet:
Mobile medium:
Tablet:
-   [ ] [Tested with screen …
=> Display logo from tablet in choice cards banner

packages/modules/src/modules/banners/choiceCardsBanner/ChoiceCardsBanner.stories.tsx, packages/modules/src/modules/banners/choiceCardsBanner/ChoiceCardsBanner.tsx, packages/modules/src/modules/banners/choiceCardsBanner/components/ChoiceCards.tsx, packages/modules/src/modules/banners/common/BannerWrapper.tsx
The [PR for choice cards amounts](https://github.com/guardian/support-dotcom-components/pull/859) introduced a new `submitComponentEvent` prop for tracking extra events with ophan. This isn't currently working because the BannerWrapper doesn't pass it in
Ophan events:
Banner insert:
Choice cards view:
Banner view:
=> Fix banner tracking

packages/modules/src/modules/banners/choiceCardsBanner/choiceCardsBannerStyles.ts, packages/modules/src/modules/banners/choiceCardsBanner/components/ChoiceCardAmountButtons.tsx, packages/modules/src/modules/banners/choiceCardsBanner/components/ChoiceCardFrequencyTabs.tsx, packages/modules/src/modules/banners/choiceCardsBanner/components/ChoiceCards.tsx, packages/modules/src/modules/banners/choiceCardsBanner/components/ChoiceCardsBannerArticleCount.tsx, packages/modules/src/modules/banners/choiceCardsBanner/components/SupportCta.tsx, packages/modules/src/modules/banners/choiceCardsBanner/components/paymentFrequencyTabs/PaymentFrequencyTabButton.tsx, packages/modules/src/modules/banners/choiceCardsBanner/components/paymentFrequencyTabs/PaymentFrequencyTabs.tsx, packages/modules/src/modules/banners/choiceCardsBanner/components/paymentFrequencyTabs/PaymentFrequencyTabsBox.tsx
Reverts guardian/support-dotcom-components#873
Change of plan: Rather than release we'd now like to AB test this against the old design.
=> Revert "Choice cards banner design update"

packages/modules/package.json, yarn.lock
React is only listed in `optionalDependencies`, for storybook. This PR updates it to react 18.
It also removed two unused dependencies:
1. preact, from `dependencies`. This is provided by the platform (DCR/Frontend) and so should not be included here.
2. `@guardian/automat-deps`. This is very old and deprecated, and not used.
Testing:
- storybook
- deployed to CODE and tested against main branches of dcr/frontend
=> react 18 v2

packages/server/src/api/epicRouter.ts, packages/server/src/server.ts, packages/server/src/tests/epics/epicTests.ts
Marketing no longer want this feature.
Still to do - remove the holdback tool from support-admin-console
=> Remove epic holdback tests

packages/modules/src/modules/banners/auElectionMoment/AusElectionMomentBanner.stories.tsx, packages/modules/src/modules/banners/aus10yrAnniversaryMoment/Aus10yrAnniversaryMomentBanner.stories.tsx, packages/modules/src/modules/banners/aus10yrAnniversaryMoment/Aus10yrAnniversaryMomentBanner.tsx, packages/modules/src/modules/banners/common/types.tsx, packages/server/src/tests/banners/channelBannerTests.ts, packages/shared/src/config/modules.ts, packages/shared/src/types/abTests/banner.ts
This PR updates the references to the AUS Anniversary Banner in this repo so they match those used in  `support-admin-console`: https://github.com/guardian/support-admin-console/pull/448
There was a bug blocking the Banner from showing in the preview in RRCP that was down to a naming mismatch.
I suspect it could be the named export https://github.com/guardian/support-dotcom-components/pull/888/files#diff-e12d0f2d4ac300b36fd853f0feae026eab1fdcb888d01a88d81401a559f9dfb7R65 here. Previously it was named `Aus10yrAnniversaryMomentBanner` and support-admin-console was looking for a banner `AusMomentBanner`, now in both repos the banner's reference is `AusAnniversaryBanner` - I need to confirm this was the issue.
=> AUS Anniversary Banner: Naming Changes

packages/modules/src/modules/banners/choiceCardsBanner/choiceCardsBannerStyles.ts
Close button overwrites header below mobile medium (see screenshot below) ->
**Trello Card**]( https://trello.com/c/xQ0hpsfv/1267-banner-layout-issue-on-mobile)
=> Banner Choice Card at mobile CTA overwrites header

packages/modules/src/hooks/useReminder.ts, packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.stories.tsx, packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx
This adds a new stories file dedicated to the moment template banner, including an example of how to configure reminders using the `getMomentTemplateBanner` helper. This also creates a new separate helper for moment template reminders.
=> Add moment template with reminder storybook example

packages/modules/src/hooks/useMediaQuery.ts, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerBody.tsx
This adds a media query hook using `matchMedia` which makes it possible to check for media query matches and change the UI based on results. 
The approach taken thus far within banner components, to display or hide different content across breakpoints, has been to make use of the `<Hide>` component from Source. This is not ideal as it has knock-on effects for css determination, any event listeners that may need to be applied as well as generally polluting the JSX. 
The `useMediaQuery` hook takes a `breakpoint` as it's argument (e.g `from.tablet`). Although, in order to get the string into the desired format (e.g. `"(min-width: 740px)"`), there's a little string manipulation necessary. So, an intermediate `query` variable is created. The …
=> Add moment template media query hook

packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerCtas.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerHeader.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerReminder.tsx
Following https://github.com/guardian/support-dotcom-components/pull/895 which added a `useMediaQuery` hook. This makes use of the new hook, for dynamically rendering content within moment template banner components based on device width. 
Removal of the remaining _content-based_ JSX duplication (this PR) and _css-based_ JSX duplication will be split into two PRs. PR for removing remaining css-based duplication to follow.
There should be no change in the UI for the moment template banner:
- header
- banner ctas
- banner reminder (alternate cta)
=> Moment template content refactor

packages/modules/src/hooks/useMediaQuery.ts, packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerCloseButton.tsx
In order to remove the remaining css & jsx duplication in the moment template banner, the top level component has been refactored. 
The UI for the banner should be the same.
Locally - could create a before and after version of the moment template banner, then use both in stories for comparison.
=> Refactor `MomentTemplateBanner.tsx`

packages/modules/src/hooks/useChoiceCards.ts, packages/modules/src/modules/banners/choiceCardsBanner/components/Button.tsx, packages/modules/src/modules/banners/choiceCardsBanner/components/ChoiceCardAmountButtons.tsx, packages/modules/src/modules/banners/choiceCardsBanner/components/ChoiceCards.tsx, packages/modules/src/modules/banners/choiceCardsBanner/components/SupportCta.tsx, packages/modules/src/modules/banners/choiceCardsButtonsBanner/components/Button.tsx, packages/modules/src/modules/banners/choiceCardsButtonsBanner/components/ChoiceCardAmountButtons.tsx, packages/modules/src/modules/banners/choiceCardsButtonsBanner/components/SupportCta.tsx, packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.stories.tsx, packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerHeader.tsx, packages/modules/src/modules/banners/momentTemplate/settings.ts, packages/modules/src/modules/banners/worldPressFreedomDay/components/Button.tsx, packages/modules/src/modules/banners/worldPressFreedomDay/components/ChoiceCardAmountButtons.tsx, packages/modules/src/modules/banners/worldPressFreedomDay/components/SupportCta.tsx
Following https://github.com/guardian/support-dotcom-components/pull/901 this adds an optional header image and the choice cards component to the moment template banner.
| With Header Image | With Choice Cards |
| -- | -- |
| <img width="1113" alt="Screenshot 2023-05-22 at 15 42 38" src="https://github.com/guardian/support-dotcom-components/assets/44685872/a2a8e831-c707-4605-8d62-03b790dc2060"> | <img width="1115" alt="Screenshot 2023-05-22 at 15 42 57" src="https://github.com/guardian/support-dotcom-components/assets/44685872/b8d9142a-0076-45ea-b723-42ecb3291843"> |
When the choice cards are added to the template, the banner ctas willl be removed. This follows the functionality of the existing ~~moment template~~ choice cards banner.
=> Add choice cards and header image to moment template

packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerCloseButton.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerTicker.tsx, packages/modules/src/modules/banners/momentTemplate/styles/buttonStyles.ts, packages/modules/src/modules/banners/momentTemplate/styles/templateStyles.ts
This updates the moment template close button in line with the design guidelines. 
This enlarges the button from 36px to 40px for improved a11y.
=> Update moment template close button

packages/modules/src/modules/banners/common/types.tsx, packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerArticleCount.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerArticleCountOptOut.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerBody.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerCloseButton.tsx, packages/modules/src/modules/banners/momentTemplate/settings.ts, packages/modules/src/modules/banners/usSupremeCourt2023/Scotus2023MomentBanner.stories.tsx, packages/modules/src/modules/banners/usSupremeCourt2023/Scotus2023MomentBanner.tsx, packages/server/src/tests/banners/channelBannerTests.ts, packages/shared/src/config/modules.ts, packages/shared/src/types/abTests/banner.ts
We have an ask to create a new Template Banner for the upcoming US Supreme Court Moment. 
To complete the work, we will merge 2 PRs in the following repos:
+ https://github.com/guardian/support-dotcom-components/pull/907
+ https://github.com/guardian/support-admin-console/pull/455
+ A Storybook story has been created for this template banner, which we can use to make sure it conforms with design (see Trello card for link to Figma file)
+ We will test the banner by deploying both PRs and creating a new banner test using the template and reviewing its presentation and functionality in both `live` and `web` views in RRCP
Marketing have defined success criteria in their scoping document for this work
We judge the risk to be low for this work as we are building the template on top of moment …
=> US supreme Court 2023 moment banner

yarn.lock
Ensure we're using minimist >= 1.2.6. Dependabot flagged a vulnerability on versions older than 1.2.6.
=> Upgrade minimist to 1.2.8

packages/modules/src/modules/banners/common/BannerWrapper.tsx, packages/modules/src/modules/banners/common/FadeIn.tsx, packages/modules/src/modules/banners/common/SlideIn.tsx
This adds a fade-in animation to the render delay banner branch
- Deploy this branch to CODE
- On the web preview scroll to at least 25% down the page
The banner fades in as expected, instead of appearing immediately
The current implementation has an unintended side effect on the "live preview" of banners in the RRCP.
=> Test of scroll depth render delay for banners - animation

packages/server/src/tests/banners/bannerSelection.test.ts, packages/server/src/tests/banners/signInPromptTests.ts, packages/server/src/tests/headers/headerSelection.test.ts, packages/server/src/tests/headers/headerSelection.ts, packages/shared/src/types/purchaseInfo.ts
Updates the Sign In Prompt Header and Banner to perssonlise for the new SupporterPlus product that replaced the DigitalPack
Tested in Code
=> Update DigitalPack to SupporterPlus PurchaseInfo

packages/modules/src/hooks/useScrollDepth.ts
This fixes an issue where the `useScrollDepth` hook was passing a scroll depth of `NaN` when banners were rendered in a Storybook iframe, causing the banner to never be rendered.
=> Fix Storybook issue caused by rendering based on scroll depth

packages/modules/src/modules/banners/choiceCardsButtonsBanner/ChoiceCardsButtonsBanner.tsx, packages/modules/src/modules/banners/choiceCardsButtonsBanner/choiceCardsButtonsBannerStyles.ts, packages/modules/src/modules/banners/choiceCardsButtonsBanner/components/ChoiceCardFrequencyTabs.tsx, packages/modules/src/modules/banners/choiceCardsButtonsBanner/components/ChoiceCards.tsx, packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerArticleCount.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerCloseButton.tsx
This pr is a refactor of the moment template banner layout. It now uses flex for breakpoints up to tablet and then grid for anything greater.
Alignment issues with the choice cards have been fixed
Before            |  After
:-------------------------:|:-------------------------:
The article count font size has been changed to match the body copy:
=> [RB PD] Moment template banner css grid refactor

packages/modules/src/modules/epics/ContributionsEpic.stories.tsx, packages/modules/src/modules/epics/ContributionsEpic.tsx
Move the sign in prompt to be below all of the payment CTA’s on the epic. We feel the journey seems disjointed as is: going from support → sign in → support again.
DRR are running a test launching this sign in feature in AUS only (as shown in attachment), and ASAP. However, conversions and personalisation feel like to give the sign in prompt the best chance in this test (without harming the conversion rate) we would like to move the position of the sign in CTA.
- Affects all Epic's with SignIn link enabled.
[Existing] ->
[New Variant] ->
=> move Epic Sign-In to bottom

packages/modules/src/modules/banners/choiceCardsButtonsBanner/components/SupportCta.tsx, packages/modules/src/modules/banners/common/types.tsx, packages/modules/src/modules/banners/europeMomentLocalLanguage/EuropeMomentLocalLanguageBanner.stories.tsx, packages/modules/src/modules/banners/europeMomentLocalLanguage/EuropeMomentLocalLanguageBanner.tsx, packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx, packages/modules/src/modules/banners/momentTemplate/stories/WithChoiceCards.tsx, packages/modules/src/modules/banners/momentTemplate/stories/WithChoiceCardsHeaderImage.tsx, packages/modules/src/modules/banners/supporterMoment/SupporterMomentBanner.stories.tsx, packages/modules/src/modules/banners/supporterMoment/SupporterMomentBanner.tsx, packages/server/src/tests/banners/channelBannerTests.ts, packages/shared/src/config/modules.ts, packages/shared/src/types/abTests/banner.ts
Marketing would like a matching separate moment choice card banner with header text (template3) for all regions EXCEPT Europe which has its own local language banner. 
Modify primaryCTA colour BannerTemplate settings to change the CTA button colour (currently it cannot be changed from yellow).
[Support-Admin-Console Supporter Moment Banner PR] https://github.com/guardian/support-admin-console/pull/484
[Trello] https://trello.com/c/jRwJkWGV/1516-supporter-moment-choicecard-banner-create
=> Supporter Banner moment

packages/modules/src/modules/banners/supporterMoment/SupporterMomentBanner.stories.tsx, packages/modules/src/modules/banners/supporterMoment/SupporterMomentBanner.tsx
Colour change to background and hover as shown ->
=> Supporter Banner moment background and hover color changes

cdk/lib/__snapshots__/dotcom-components.test.ts.snap, cdk/lib/dotcom-components.ts, packages/server/src/tests/banners/channelBannerTests.test.ts, packages/server/src/tests/store.ts, packages/server/src/utils/cloudwatch.ts
To be consistent with other Dynamo loading, add an alarm for banner design loading failures.
I've also made a change to the existing test loading so that instead of swallowing Dynamo errors and returning an empty array we now re-throw the error which results in a failed Promise being returned. This means if we already have previously successfully loaded test data we'll continue to use it (rather than wiping out existing test data with the empty array). If the failure is on the initial load the deployment will fail which I think is fine (gives visibility to the error).
Deploy to CODE.
-   [ ] [Navigable with …
=> Add an alarm for banner design loading failures

packages/server/src/api/epicRouter.ts, packages/shared/src/lib/localLanguage.test.ts, packages/shared/src/lib/localLanguage.ts
Marketing would like to target users' in specific countries viewing the Epic, altering the Epic headline, paragraph and highlightedtext copy to be a message in 3 regional language. It will fallback to RRCP defaults in all other cases.
Countries to target:
- Germany
- France
- Netherlands
On the '/epic' endpoint if the user is in the EUR test and in the subset of countries adjust response to return hardcoded copy. This way we don't have to edit the template. We include the reader's country code in the payload sent to /epic. We will need to know the Europe Moment Banner test / variant names to do this targeting, as we only want to do the swap for users' in the correct test.
Epic Test Name: LOCAL-LANGAUGE
Epic Variant Name: CONTROL
| Country | Epic | 
|--------|--------| …
=> Europe local language Epic translation V2

packages/modules/rollup.config.js
Extracting out common config in the rollup configuration seems to have a good effect. On my local machine:
Before:
```
✨  Done in 264.07s.
NODE_ENV=production NODE_OPTIONS="--max-old-space-size=16384" yarn modules   312.63s user 130.41s system 167% cpu 4:24.19 total
```
After:
```
✨  Done in 69.38s.
NODE_ENV=production NODE_OPTIONS="--max-old-space-size=16384" yarn modules   125.94s user 17.37s system 206% cpu 1:09.49 total
```
The speedup is also seen in GHA:
Before:
After:
I've tested this in CODE and have seen banners and epics render as expected. I also diffed the output of the build process before and after this change and confirmed it was identical.
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader …
=> Speed up rollup module build process

packages/modules/src/modules/banners/choiceCardsButtonsBanner/choiceCardsButtonsBannerStyles.ts
At small Mobile breakpoints and below the close button overflows across the banner header. This occurs on the original Choice Cards banner only (Moment version is fine). 
Font has already been reduced from 24px to 22px below MobileMedium.
[Trello]
https://trello.com/c/y0l6bigp/1538-bespoke-choice-card-banner-mobile-breakpoint-close-button-overlays-header
=> Choice cards banner below mobile medium close button stop overflowing header

packages/server/src/tests/banners/bannerSelection.ts
Marketing have requested a temporary halt on showing Banner messages on the new Europe edition front.
- Once the new Europe edition launches, attempt to force a banner to display on the front. No banner should display
- Then go to an article and repeat - a banner should display
- As a sanity check, check on a different edition front - again, a banner should display
=> Suppress banners on the new Europe edition front

packages/modules/src/hooks/useChoiceCards.ts, packages/modules/src/modules/banners/europeMomentLocalLanguage/EuropeMomentLocalLanguageBanner.stories.tsx
Fallback changed from 'Contribute' to 'Continue' for Moment Choice Card banners (Europe Local Lnaguage and Supporter).
A separate PR will be created to ensure RRCP CTA setting are passed through to this banner type (Moment Choice Cards).
| Before | After | 
|--------|--------|
|<img width="1026" alt="image" src="https://github.com/guardian/support-dotcom-components/assets/76729591/0b645d92-539e-4466-8187-14917386db58">|<img width="1026" alt="image" src="https://github.com/guardian/support-dotcom-components/assets/76729591/bafea35f-8e4a-4c34-b78e-8400592692f7">|
|<img width="1026" alt="image" src="https://github.com/guardian/support-dotcom-components/assets/76729591/f170183a-23b9-4cf1-9df8-44e4f340b7ff">|<img width="1026" alt="image" …
=> Europe and Supporter Moment Banner CTA correction

packages/server/src/tests/banners/bannerSelection.ts
Reverts guardian/support-dotcom-components#962
The requirement to suppress banners on the new Front was always temporary. This PR will revert the changes once the requirement completes
=> Revert "Suppress banners on the new Europe edition front"

packages/modules/src/hooks/useChoiceCards.ts, packages/modules/src/modules/banners/designableBanner/DesignableBanner.tsx, packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx, packages/modules/src/modules/banners/supporterMoment/SupporterMomentBanner.stories.tsx
Moment Choice Card banners (Europe Local Language and Supporter) pull RRCP CTA settings through to banner.
Note: This is a wider fix supercedes the fix described in this PR -> 
https://github.com/guardian/support-dotcom-components/pull/964
| Before | After | 
|--------|--------|
|<img width="1026" alt="image" src="https://github.com/guardian/support-dotcom-components/assets/76729591/0b645d92-539e-4466-8187-14917386db58">|<img width="1026" alt="image" src="https://github.com/guardian/support-dotcom-components/assets/76729591/bafea35f-8e4a-4c34-b78e-8400592692f7">|
|<img width="1026" alt="image" src="https://github.com/guardian/support-dotcom-components/assets/76729591/f170183a-23b9-4cf1-9df8-44e4f340b7ff">|<img width="1026" alt="image" …
=> Moment Choice Card Banner CTA pulled from RRCP

packages/server/src/tests/store.ts
The RRCP prevents draft banner designs from being used in test variants.
SDC can safely ignore them
=> Exclude draft banner designs

packages/server/src/lib/targeting.test.ts, packages/server/src/lib/targeting.ts
Currently if a test has required tagIds and required sectionIds set, then these expressions are AND'ed, i.e. a page must have both a matching tag and a matching section.
This isn't the desired behaviour.
With this PR, the logic becomes:
`(target tags match OR target sections match) AND NOT (excluded tags match OR excluded sections match)`
=> Improve context targeting logic

packages/modules/src/modules/banners/designableBanner/DesignableBanner.tsx, packages/modules/src/modules/banners/designableBanner/stories/DesignableBanner.stories.tsx, packages/server/src/factories/bannerDesign.ts, packages/shared/src/types/props/banner.ts, packages/shared/src/types/props/design.test.ts, packages/shared/src/types/props/design.ts, packages/shared/src/types/props/index.ts
This introduces two new colour properties to the design prop of the `DesignableBanner` component: the `background` and `bodyText` colours.
This change will need to go hand-in-hand with guardian/support-admin-console#499 where we add the UI to configure these new values in a banner design.
-   [ ] [The change doesn't use only colour to convey …
=> Add new designable banner fields

packages/modules/src/modules/banners/choiceCardsButtonsBanner/components/ChoiceCardAmountButtons.tsx, packages/modules/src/modules/banners/choiceCardsButtonsBanner/components/ChoiceCardFrequencyTabs.tsx, packages/modules/src/modules/banners/choiceCardsButtonsBanner/components/ChoiceCards.tsx, packages/modules/src/modules/banners/choiceCardsMoment/ChoiceCardsMomentBanner.stories.tsx, packages/modules/src/modules/banners/choiceCardsMoment/ChoiceCardsMomentBanner.tsx, packages/modules/src/modules/banners/environmentMoment/EnvironmentMomentBanner.stories.tsx, packages/modules/src/modules/banners/environmentMoment/EnvironmentMomentBanner.tsx, packages/modules/src/modules/banners/europeMomentLocalLanguage/EuropeMomentLocalLanguageBanner.stories.tsx, packages/modules/src/modules/banners/europeMomentLocalLanguage/EuropeMomentLocalLanguageBanner.tsx, packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx, packages/modules/src/modules/banners/momentTemplate/settings.ts, packages/modules/src/modules/banners/momentTemplate/stories/WithChoiceCards.tsx, packages/modules/src/modules/banners/momentTemplate/stories/WithChoiceCardsHeaderImage.tsx, packages/modules/src/modules/banners/supporterMoment/SupporterMomentBanner.stories.tsx, packages/modules/src/modules/banners/supporterMoment/SupporterMomentBanner.tsx
- Add white fill (neutral.100) to unselected choice cards buttons
- This change would be across ALL ChoiceCard Moment banners
We have been starting to do more colour customisation on banners with choice cards, however, in order to maintain enough contrast between the unselected buttons and the background we have to use lighter/pale colours which is quite limiting - by adding a white fill to those unselected buttons we will be able to have more freedom with background colours.
| RRCP Name | Before | After | 
|--------|--------|--------|
|Choice Cards Moment 2023|<img width="978" alt="image" src="https://github.com/guardian/support-dotcom-components/assets/76729591/f5f87b0c-df9e-48d1-b4ef-efe3818e00c6">|<img width="978" alt="image" …
=> choice card moment banner buttons colour white

packages/modules/src/modules/banners/designableBanner/DesignableBanner.tsx, packages/modules/src/modules/banners/designableBanner/components/DesignableBannerCloseButton.tsx, packages/modules/src/modules/banners/designableBanner/settings.ts, packages/modules/src/modules/banners/designableBanner/stories/DesignableBanner.stories.tsx, packages/server/src/factories/bannerDesign.ts, packages/shared/src/types/props/design.ts
Expands the `ConfigurableDesign` model to support more colours.
I've made all fields required as I'm not sure it makes sense to have defaults for these.
Current storybook -
Corresponding SAC PR: https://github.com/guardian/support-admin-console/pull/503
=> Designable banner: more colours

packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerCtas.tsx, packages/modules/src/modules/banners/momentTemplate/settings.ts, packages/modules/src/modules/banners/momentTemplate/stories/MomentTemplateBanner.stories.tsx, packages/modules/src/modules/banners/momentTemplate/stories/WithBackDrop.tsx
- Image background colours removed
- Backdrop tiled image added to banner (image can be breakpoint dependent)
- Story 'MomentTemplate/With Backdrop' to demonstrate
- Bugfix: Single CTA (non-choice card) moment banners, bottom spacing corrected to card icons
Moment template banner cleanup
[Trello] https://trello.com/c/i5kQWfNy/1564-momenttemplate-banner-sub-components-background-change-backcolour-to-transparent
=> Backdrop enabled Moment banners

packages/modules/src/modules/banners/designableBanner/DesignableBanner.tsx, packages/modules/src/modules/banners/designableBanner/stories/DesignableBanner.stories.tsx, packages/server/src/factories/bannerDesign.ts, packages/shared/src/types/props/design.ts
this enables the new banner design tool to configure the ticker colours
SAC PR - https://github.com/guardian/support-admin-console/pull/504
=> Banner ticker design

packages/modules/src/modules/banners/guardianWeekly/GuardianWeeklyBanner.tsx, packages/modules/src/modules/banners/guardianWeekly/guardianWeeklyBannerStyles.ts
Banner Centre cross of close button, Guardian log and primary CTA arrow SVG's hidden when in front of European Pollution Interactive Map. Affects 'Guardian Weekly'.
Style are bleeding from the interactive map into our banners (offending style highlighted in red). The style appear to be looking through the page for a 'DIV SECTION DIV SVG' then disabling the display (display:none). This appears to affect our SVG's in banners.
A longer term fix in the interactive map has been requested (Anna Leach / Antonio Voce)
CSS: 'DIV SECTION DIV SVG'  ->
| Applied | Removed |
|--------|--------|
|![image](https://github.com/guardian/support-dotcom-components/assets/76729591/39af0bf0-8885-41df-b547-6cd8caf76acf)|![image](https://github.com/guardian/support-dotcom-components/assets/76729591/91c37358-6b63- …
=> Guardian Weekly Banner SVG's hidden (over European Interactive Map)

packages/modules/src/modules/banners/designableBanner/components/DesignableBannerCtas.tsx
Already fixed for the moment template [here](https://github.com/guardian/support-dotcom-components/commit/b87e7a83ee4d2ef85e25fbfab02cd2467f89cedd).
Before:
After:
And with 2 ctas it's unchanged:
=> Fix banner cta margin

packages/server/src/api/bannerRouter.ts
recently a [change to this code](https://github.com/guardian/support-dotcom-components/commit/8198d09cc7c1eae9a9cf788aebbb5c30186fcd9f#diff-fef75acb8a32b2c4c5efd89fc20b6844f30ffbf95b508e757707b953386ac983R146) caused an issue with banners with no `mobileContent` defined. Specifically, it affected the default hardcoded test, which we've [now removed](https://github.com/guardian/support-dotcom-components/pull/985).
We get away with it for (all?) RRCP tests because the tool sets `mobileContent` explicitly to `null` in dynamodb (rather than being undefined).
This PR tries to make the logic it a bit more robust to avoid this happening again.
Tested in CODE -
French:
English:
=> Improve banner content logic

packages/modules/src/modules/banners/utils/storybook.ts, packages/modules/src/modules/epics/ContributionsEpic.stories.tsx, packages/server/src/lib/fetchTickerData.ts, packages/server/src/server.ts, packages/server/src/tests/amp/ampEpicSelection.test.ts, packages/shared/src/types/props/shared.ts
Rather than create a new ticker for each year, it seems sensible to
reuse them each year (if necessary). Therefore, let’s remove the year
from the name. Co-ordinated with changes to support-admin-console and
contributions-ticker-calculator.
=> Remove _2022 from ticker names

packages/modules/src/modules/banners/common/BannerWrapper.tsx, packages/server/src/api/epicRouter.ts, packages/shared/src/lib/reminderFields.test.ts, packages/shared/src/lib/reminderFields.ts
In the US we want to use different reminders logic in the epic for two distinct periods:
November 10th - November 27th inclusive: `Remind me on Giving Tuesday`
November 28th - December 30th inclusive: `Remind me on New Years Eve`
This PR adds logic to support this. Braze canvases/campaigns will need to be created to support the two new reminder option fields:
`giving-tuesday-2023`
`new-years-eve-2023`
I'll work with marketing to ensure this happens.
-   [ ] [Colour contrast …
=> Add Giving Tuesday and New Years Eve reminders logic

packages/modules/src/modules/banners/choiceCardsButtonsBanner/components/ChoiceCardFrequencyTabs.tsx, packages/modules/src/modules/banners/choiceCardsButtonsBanner/components/ChoiceCards.tsx, packages/modules/src/modules/banners/worldPressFreedomDay/components/ChoiceCards.tsx, packages/modules/src/modules/banners/worldPressFreedomDay/components/FrequencyTabs.tsx, packages/modules/src/modules/shared/helpers/choiceCards.ts
Following UXR, We would like to test changing the word “single” on the checkout to “One-time”. This would not be a test, this would be global.
[**Trello Card**](https://trello.com/c/c3cMVhhj/1625-changing-single-to-one-time-on-banner-epic-choice-cards-support-dotcom-components)
|Type|Before|After|
|--------|--------|--------|
|TemplateBanner|![image](https://github.com/guardian/support-dotcom-components/assets/76729591/0deb1f26-896d-41f9-80d8-c717429f2f5d)|![image](https://github.com/guardian/support-dotcom-components/assets/76729591/ec29e984-f0c4-4869-a716-c0fb92041d84)|
|WorldPressFreedomDay|![image](https://github.com/guardian/support-dotcom-components/assets/76729591/c7576139-0d06-40a7-bcf9-0ea95f249539)|![image](https://github.com/guardian/support-dotcom-components/assets/76729591/c0b …
=> Single to One-time frequency card for MomentChoiceCard Banner and Epic

packages/modules/src/modules/banners/designableBanner/components/DesignableBannerArticleCount.tsx, packages/modules/src/modules/banners/designableBanner/components/DesignableBannerArticleCountOptOut.tsx, packages/modules/src/modules/banners/designableBanner/components/DesignableBannerBody.tsx, packages/modules/src/modules/banners/designableBanner/components/DesignableBannerHeader.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerArticleCount.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerArticleCountOptOut.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerBody.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerHeader.tsx
Moment Template Banner Accessibility - browser-level font enlarging not affecting banner header and copy.
This change will apply to all Moment Template based banners.
[**Trello Card**](https://trello.com/c/2UxqCzRM/1634-moment-template-banner-browser-level-font-enlarging-not-affecting-banner-header-and-copy)
You can adjust Chrome's font settings from medium to very large here (chrome://settings/appearance) ->
|Banner|Font Size|Mobile|Desktop|
|--------|--------|--------|--------|
|ChoiceCardsMoment|Medium|<img width="375" alt="image" src="https://github.com/guardian/support-dotcom-components/assets/76729591/2ad3bc97-884c-4400-8400-71cf1aeb02da">|<img width="978" alt="image" src="https://github.com/guardian/support-dotcom-components/assets/76729591/1aa3e876-e4cc-40a8-b85c-56fe79ca9a92">| …
=> Browser font re-sizing supported for Moment Template And Design Banners

packages/server/src/api/bannerRouter.ts
Marketing want direct control of this.
This can be re-enabled in December
=> Disable scheduled banner deploys in US

packages/modules/src/modules/epics/ButtonApplePay.tsx, packages/modules/src/modules/epics/ContributionsEpicButtons.tsx
We released the Apple Pay Epic AB test yesterday. I checked the component events in the Page View table in the Data Lake today and noted we have no click events on the Apple Pay button recorded. This is because `submitComponentEvent` wasn't passed to `ButtonApplePay`.
=> Handle Apple Pay button click so it gets tracked in Ophan

packages/modules/src/modules/banners/common/choiceCard/ChoiceCardInteractive.tsx
RRCP live view of banner and epic tests with an amounts card show the card's tabs in reverse order (with "annual" to the left). When displayed on the main Guardian site the tabs appear in the correct order.
Reason for this discrepancy is because the ChoiceCard component (defined in SDC) processes the `displayContributionType` array without checking that the array's elements are in the correct order. This PR fixes this vulnerability.
Review in Storybook, and in CODE environment for SDC and SAC repos to check the update fixes the live preview functionality
__Live preview in RRCP__
__Expected tab order__ (Annual tab always on the right)
=> Small fix to enforce amounts card tab order

packages/modules/src/modules/banners/designableBanner/DesignableBanner.tsx, packages/modules/src/modules/banners/designableBanner/stories/DesignableBanner.stories.tsx
On DCR pages the bold is lost.
=> Enable bold in DesignableBanner

packages/modules/src/modules/banners/designableBanner/DesignableBanner.tsx, packages/modules/src/modules/banners/designableBanner/components/DesignableBannerCloseButton.tsx, packages/modules/src/modules/banners/momentTemplate/MomentTemplateBanner.tsx, packages/modules/src/modules/banners/momentTemplate/components/MomentTemplateBannerCloseButton.tsx
Banners are frequently too tall.
This makes the close button always in view for the DesignableBanner and MomentTemplateBanner.
Tabbing to the button still works
=> Make banner close button sticky

packages/modules/src/modules/epics/BylineWithHeadshot.tsx
Currently the byline image always gets cropped, even if you follow the guidance in the RRCP that it should be a square.
This is because we set the width to 30%.
It's necessary to limit the width at mobile, but we don't need to from tablet.
=> Avoid byline image cropping

.github/workflows/dotcom-components.yml
currently the `Release` workflow job fails with:
`Error: There is no .changeset directory in this project`
This is because we're using yarn workspaces.
We can use [`cwd`](https://github.com/changesets/action/tree/main#inputs) to tell changeset to run it from the relevant yarn workspace
=> Fix release with cwd

packages/dotcom/.changeset/config.json, packages/modules/package.json, packages/server/package.json, packages/shared/package.json
It has been trying to publish the other packages, even though they are listed as excluded in the changeset config file.
This PR makes the other packages private.
Running `yarn changeset publish` locally looks more promising:
Even though there are no changesets, it was trying to publish a first version because the other packages are not on npm.
=> Fix release - make packages private

packages/dotcom/.changeset/famous-llamas-check.md
this doesn't actually change anything, but is to test that the changeset release to npm works
=> test npm release

packages/modules/src/modules/banners/common/choiceCard/ChoiceCardInteractive.tsx, packages/modules/src/modules/banners/common/choiceCard/ChoiceCards.tsx, packages/modules/src/modules/banners/designableBanner/DesignableBanner.tsx, packages/modules/src/modules/banners/designableBanner/stories/DesignableBanner.stories.tsx, packages/shared/src/types/props/design.ts
Currently the designable banner tool only allows the choice card button background color to be set. This PR extends that functionality to allow choice card button background, text and border colors to be set via the tool.
See related PR in SAC: https://github.com/guardian/support-admin-console/pull/541
In SDC Storybook, and in RRCP CODE site (when both this PR and the accompanying SAC PR have been deployed to CODE).
**Using default colors** - no colors have been set for the amounts card design
**Using tool-defined colors**
=> Add color options to designable banner choice card

packages/modules/src/modules/epics/utils/ophan.ts
It's useful to be able to track clicks of the primary CTA on our channels (epic/banner/header links).
This has [just been reintroduced](https://github.com/guardian/support-dotcom-components/pull/1027) for the banner.
For the epic, the primary CTA clicks are being tracked against the `ACQUISITIONS_OTHER` componentType, but it's better to use `ACQUISITIONS_EPIC`.
This will help with a grafana dashboard + alerts that we're building.
=> Use correct componentType for epic clicks

packages/dotcom/.changeset/happy-garlics-sniff.md, packages/dotcom/src/index.ts
I'm working on [migrating](https://github.com/guardian/dotcom-rendering/pull/9959) the epic component to DCR
=> More exports to support migration of epic to DCR

packages/modules/src/modules/epics/utils/ophan.ts
This event tracks when the ctas component of the epic comes into view. It incorrectly has action `CLICK`.
We get over 1m of these events per day so it's quite misleading
=> Fix epic ctas view event

packages/modules/src/modules/banners/contributions/ContributionsBanner.stories.tsx, packages/modules/src/modules/banners/designableBanner/components/DesignableBannerCtas.tsx, packages/modules/src/modules/banners/designableBanner/stories/DesignableBanner.stories.tsx
Checks the baseUrl of the primary CTA in designable banners - if url is not to the support site we do not show the payment icons.
Before
After
=> Hide payment icons not support cta

packages/server/src/server.ts
We use `https://r.thegulocal.com` when running DCR locally. This change is necessary to avoid CORS errors when making requests to SDC
=> Add r.thegulocal.com to allowed origins

packages/modules/src/hooks/useMediaQuery.ts
On iOS 13 devices the DesignableBanner and MomentTemplateBanner components have a bug in the close button.
When a user clicks close, the banner is not immediately removed. On subsequent pageviews (e.g. refreshing the page) the banner is no longer displayed. This is because the localstorage item for recording when the banner was closed _is_ set.
The error in the console is:
`Unhandled Promise Rejection: TypeError: o.removeEventListener is not a function. (In 'o.removeEventListener("change",r)', 'o.removeEventListener' is undefined)`
The issue is the use of the `removeEventListener`, which is not available on old browsers.
There is already similar logic for handling `addEventListener`, and I've refactored this slightly at the same time.
=> Fix media eventListener on old safari

packages/shared/src/types/props/design.ts
The designable banner choice cards have been broken by the validation that was recently added [here](https://github.com/guardian/support-dotcom-components/commit/9d892033f5a199a78945e354042acd935d26b741#diff-9bcf42ad88e2672cbf6fecd6f0d2e94330a4e274fa938424edea3f6705874c42L29).
Currently the validation doesn't accept `null` values for optional fields, but dynamodb represents these as nulls. The fix (as elsewhere in the codebase) is to use zod's `nullish`
=> Fix banner choice cards validation

packages/modules/src/modules/banners/designableBanner/DesignableBanner.tsx, packages/modules/src/modules/banners/designableBanner/components/DesignableBannerCloseButton.tsx, packages/modules/src/modules/banners/designableBanner/stories/DesignableBanner.stories.tsx, packages/modules/src/modules/banners/designableBanner/styles/templateStyles.ts, packages/server/src/factories/bannerDesign.ts, packages/shared/src/types/props/design.ts
Use the full ‘The Guardian’ logo at the bottom right and remove the roundel from the top right, in order to have the RRCP match our design style guide.
Also position the close button within the grid, after discussion with designers.
The logo only shows from 740px (tablet) onwards.
- Create a designable banner
- See Guardian logo in bottom right
Wide
Tablet
Mobile (unchanged)
-   [ ] [The change …
=> Use the full ‘The Guardian’ logo at the bottom right and remove the roundel from the top right

packages/modules/src/modules/banners/designableBanner/DesignableBanner.tsx, packages/modules/src/modules/banners/designableBanner/settings.ts, packages/modules/src/modules/banners/designableBanner/stories/DesignableBanner.stories.tsx, packages/server/src/factories/bannerDesign.ts, packages/shared/src/types/props/design.ts
Remove roundel settings and property from banner design - following up on #1044 where it is no longer used in designable banners
=> Remove roundel from banner design

packages/modules/src/modules/banners/common/choiceCard/ChoiceCards.tsx
Moves the payment icons below the CTA and makes the CTA full width on mobile
Check Moment on storybook
| Before | After |
| --- | --- |
| ![image](https://github.com/guardian/support-dotcom-components/assets/99400613/5491bac5-8787-4191-99bd-9cc7c07391ed) | ![image](https://github.com/guardian/support-dotcom-components/assets/99400613/180e33fe-a416-43dd-8195-0ffd823ee8d1) |
This is a layout change and only moves non interactive elements so accessibility should be unaffected
=> Full width CTA and move payment icons on mobile

packages/modules/src/modules/banners/designableBanner/DesignableBanner.tsx
Small followup to #1044
Refactor the way to colour the "The Guardian" logo - after upgrading source the `SvgGuardianLogo` now has a `textColor` prop
Chromatic should have no diffs
=> Refactor Guardian logo colour

packages/modules/tsconfig.json
Remove manually adding emotion CSS prop into tsconfig, #890 introduced it and I can't tell why it's necessary. VS Code complains about it - as it's not a full file path.
Storybook ran normally locally and seems normal on this PR 
=> remove "files" from tsconfig

packages/server/src/utils/removeNullValues.test.ts, packages/server/src/utils/removeNullValues.ts
The `removeNullValues` was removing `undefined` properties because we used `!=` instead of `!==`. This PR fixes that and adds an undefined field into the test
=> Add 'undefined' test case and fix removeNullValues

packages/modules/src/modules/banners/designableBanner/components/DesignableBannerBody.tsx
Remove the padding to prevent highlighted text from overlapping previous lines and cutting off the text in designable banners. This was introduced in #1049 when changing the lineheight. 
I've tried to get it as close to possible to the [figma](https://www.figma.com/file/Awq5x4DJ6bIoXpmRiBDPHw/Banner-tooling-Templates?type=design&node-id=55-65120&mode=design&t=XZ1CtvE6t6m3RG7U-0).
Load banner: see gap between highlighted text, text from line above not cut off.
Before
After
-   [ ] [Colour contrast …
=> Banner: remove padding to stop highlighted text overlapping

packages/modules/src/modules/banners/common/choiceCard/ChoiceCards.tsx
Sets the choice card width to 280px when on Tablet breakpoint
New choice card wdith
Showing that the change has not impacted the alignments on the banner
=> RRCP: choice card width on Tablet

packages/modules/src/modules/banners/designableBanner/DesignableBanner.tsx
Aligns the heading and body text width on the banners to match the style guide:
- Wide 700px
- LeftCol 620px
- Desktop 460px
- Tablet 400px
[Trello card](https://trello.com/c/ezNCdCnX/157-rrcp-banner-text-width-design-system-s)
**Wide**
**Header**
**Body**
Alignment is unaffected:
**LeftCol**
**Header**
**Body**
Alignment is unaffected:
**Desktop**
**Header**
**Body**
Alignment is unaffected:
**Tablet**
**Header**
**Body**
Alignment is unaffected:
-   [ ] [Colour contrast …
=> RRCP Banner header and text box widths

packages/modules/.storybook/preview.tsx, packages/modules/src/modules/banners/contributions/ContributionsBanner.stories.tsx, packages/modules/src/modules/banners/contributions/ContributionsBannerReminderSignedOut.stories.tsx, packages/modules/src/modules/banners/contributions/ContributionsBannerWithSignIn.stories.tsx, packages/modules/src/modules/banners/designableBanner/stories/DesignableBanner.stories.tsx, packages/modules/src/modules/banners/environment/EnvironmentBanner.stories.tsx, packages/modules/src/modules/banners/europeMomentLocalLanguage/EuropeMomentLocalLanguageBanner.stories.tsx, packages/modules/src/modules/banners/momentTemplate/stories/MomentTemplateBanner.stories.tsx, packages/modules/src/modules/banners/signInPrompt/SignInPromptBanner.stories.tsx, packages/modules/src/modules/banners/worldPressFreedomDay/worldPressFreedomDayBanner.stories.tsx
Adds responsive viewports to chromatic config
This is a QoL test to improve the usefulness of chromatic so the outcome should be that our chromatic snapshots include changes to mobile view. This PR will add a whole suite of them but future PRs will only flag changes. Check the chromatic link on this PR to see the added snapshots.
=> Add responsive views to chromatic

packages/modules/src/modules/headers/HeaderWrapper.tsx, packages/server/src/tests/headers/headerTests.ts, packages/shared/src/types/abTests/header.ts, packages/shared/src/types/abTests/shared.ts, packages/shared/src/types/props/header.ts, packages/shared/src/types/purchaseInfo.ts
Follows [previous work](https://github.com/guardian/support-dotcom-components/pull/1058) on the epic AB test data.
Validates data from Dynamodb using zod, and migrates to inferring header types from the zod schemas to avoid duplication
=> Validate header test data from Dynamodb

packages/dotcom/.changeset/chilled-cobras-dream.md, packages/modules/.storybook/preview.tsx, packages/shared/src/types/props/epic.ts
These were accidentally dropped by [this PR](https://github.com/guardian/support-dotcom-components/pull/1058).
It didn't become a problem until updating the npm dependency in dotcom-rendering and running `tsc`.
=> Add missing epic fields

packages/server/src/tests/amp/ampEpicModels.ts, packages/server/src/tests/amp/ampEpicTests.ts, packages/shared/src/types/props/epic.ts
Continues the work to validate AB test data from Dynamodb.
The AMP epic situation is a bit different because there's no client side use of the models. DCR has the [AMP component](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/components/Epic.amp.tsx#L348).
But it's still good to validate the data from dynamo and infer the types from the schema.
Tested in CODE by viewing the epic on an AMP article, e.g. https://amp.code.dev-theguardian.com/football/2024/jan/04/wayne-rooney-needed-time-patience-lacking-in-football-birmingham
I also tested geolocation targeting still works by copying the request to SDC and using postman to set the `X-GU-GeoIP-Country-Code` header to `US`.
=> Validate amp epic data

packages/server/src/tests/epics/epicTests.ts, packages/server/src/tests/headers/headerTests.ts, packages/server/src/tests/store.ts, packages/shared/src/types/abTests/epic.ts, packages/shared/src/types/abTests/header.ts
Small followup to #1073 to use a consistent naming for our zod schemas that are coming from the tool. And make the schemas mandatory in `getTests`
=> AB Test Validation - Naming Consistency and make schema mandatory

packages/shared/src/types/props/epic.ts
After removing from the RRCP https://github.com/guardian/support-admin-console/pull/557
=> Remove footer from epic

packages/dotcom/.changeset/healthy-colts-fry.md
add a changeset for #1075 (should have done this in that PR but merged before doing this)
=> create changeset for removing footer prop

packages/modules/src/modules/banners/common/choiceCard/ChoiceCards.tsx, packages/modules/src/modules/banners/designableBanner/DesignableBanner.tsx, packages/modules/src/modules/banners/designableBanner/components/DesignableBannerHeader.tsx, packages/modules/src/modules/banners/designableBanner/components/DesignableBannerVisual.tsx, packages/modules/src/modules/banners/designableBanner/stories/DesignableBanner.stories.tsx, packages/modules/src/modules/banners/designableBanner/styles/templateStyles.ts, packages/modules/src/modules/shared/ResponsiveImage.tsx, packages/server/src/factories/bannerDesign.ts, packages/shared/src/types/props/design.ts
Fixes the right column width on banners for tablet and above
Test visually with storybook
Choice card 280px width on Tablet 
=> Fix right column width on banners

packages/modules/src/modules/banners/designableBanner/DesignableBanner.tsx
Fix the close button overlapping the headline text in mobile banners.
Storybook - mobile screen sizes
No header image
Before
After
Header image
After
=> Fix close button overlapping headline on mobile banner

packages/modules/src/modules/banners/designableBanner/stories/DesignableBanner.stories.tsx, packages/server/src/factories/bannerDesign.ts, packages/shared/src/types/props/design.ts
As part of updating the image ratios as part of [this card](https://trello.com/c/aLG1cg3T/133-rrcp-banner-image-ratio), for backwards compatibility we had kept the 'old' fields `tabletDesktop` and `wideURL`. The release has been successful (at this point) so this PR is to remove some of the usages of the old fields.
Tested in RRCP code that the deprecated fields are no longer displayed and the live preview functionality works (See image)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/pe …
=> RRCP field tidy up

packages/modules/src/modules/banners/common/choiceCard/ChoiceCards.tsx, packages/modules/src/modules/banners/designableBanner/DesignableBanner.tsx
Conditionally tweaks the grid in the banner so that when an image is present the close button and image are a single cell, when the choice cards are present, they are separate. See images to get a better idea, this has the greatest effect on wide. This also addresses the width of the choice cards, making them more consistent with designs.
=> Banner layout tweaks

packages/modules/src/modules/banners/designableBanner/components/DesignableBannerVisual.tsx, packages/modules/src/modules/banners/designableBanner/stories/DesignableBanner.stories.tsx
Banner header images on mobile and phablet breakpoints are now full width of the banner
[Trello card](https://trello.com/c/SU2sakWt/162-rrcp-banner-update-the-top-padding-of-header-image-s) part two of the card had already been done 🎉 
Mobile
Mobile medium
Phablet
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technolo …
=> header image on mobile breakpoints are full width

packages/server/src/api/epicRouter.ts, packages/server/src/bandit/banditData.ts, packages/server/src/bandit/banditSelection.test.ts, packages/server/src/bandit/banditSelection.ts, packages/server/src/server.ts, packages/server/src/tests/epics/epicSelection.test.ts, packages/server/src/tests/epics/epicSelection.ts, packages/shared/src/types/abTests/epic.ts
=> Implement WIP bandit data

cdk/lib/__snapshots__/dotcom-components.test.ts.snap, cdk/lib/dotcom-components.ts, packages/server/src/api/epicRouter.ts, packages/server/src/bandit/banditData.ts, packages/server/src/bandit/banditSelection.test.ts, packages/server/src/bandit/banditSelection.ts, packages/server/src/server.ts, packages/server/src/tests/epics/epicSelection.test.ts, packages/server/src/tests/epics/epicSelection.ts, packages/server/src/utils/cloudwatch.ts, packages/shared/src/types/abTests/epic.ts
Create multi armed bandit selection algorithm for Epic selection within SDC. See point 5 in [this doc](https://docs.google.com/document/d/1jV6DkkLLH90PetO1Os7c6pi8WEiCx2t9BUIraqIEAHU/edit)
- Fetch and cache variant data (views and AV) for each bandit test
- Calculate sample mean of each variant
- Implement ε-greedy algorithm, with hardcoded ε value for now
- Add alarms for errors
This work follows up on the work done in `support-analytics` ([initial PR](https://github.com/guardian/support-analytics/pull/319)) to create a state machine to serve the initial variant data
=> Support Multi Armed Bandit testing

packages/server/src/bandit/banditSelection.ts, packages/server/src/lib/ab.ts, packages/server/src/tests/epics/epicSelection.test.ts, packages/server/src/tests/epics/epicSelection.ts
Create a filter within epic selection to implement a null hypothesis test - testing that using multi armed bandit (MAB) selection (at random) does not show a statistical difference to using AB testing. Two RRCP Epic channel tests with hardcoded test names will be added and the new filter will pick between them at 50% probability, using a user's MVT cookie. Depending on which epic is chosen the respective selection logic will be used (AB testing vs MAB). 
We also set the probability of picking randomly, when using the MAB logic, to 100%. In other words when MAB logic is used, it will pick at random.
=> Bandit null hypothesis epic selection

packages/server/src/bandit/banditData.ts
Currently if an epic test has no variants then we get an error trying to access the mean of the highest performing variant -
`Cannot read properties of undefined (reading 'mean')`
This PR makes the `buildBanditDataForTest` function return early if there are no variants.
The `banditSelection.ts` logic already handles the case where no variant can be chosen
=> Guard against tests with no variants

packages/dotcom/.changeset/good-wasps-play.md, packages/server/src/lib/targeting.test.ts, packages/server/src/lib/targeting.ts, packages/server/src/lib/targetingTesting.test.ts, packages/server/src/tests/banners/bannerSelection.test.ts, packages/server/src/tests/banners/bannerSelection.ts, packages/shared/src/types/abTests/banner.ts, packages/shared/src/types/abTests/shared.ts, packages/shared/src/types/targeting/banner.ts
We have updated the model for bannertargeting  by adding hasConsented flag to the model, so that it aligns with the model in DCR (PR to follow)
We've also updated the testSchema model with a new type (ConsentStatus), so that the it aligns with the model in dynamodb table
we want to target banners from the Reader Revenue Control Panel based on what users have consented to
We have tested that the new hasConsented flag has been passed through from the API.
Changes were made in several systems. To test that they have the expected results, we performed integration testing by:
Reject-all
- load an article on localhost via DCR
- reject all by clicking 'reject all' the banner window
- using a console.log, observe that the boolean for hasConsented is set to false
Accepting
- load an article on …
=> Cc dp/add new reject all targeting field

packages/server/src/lib/targeting.test.ts, packages/server/src/lib/targeting.ts, packages/shared/src/types/abTests/shared.ts
Update to the targeting enum to match what we are passing through from Support Admin Console from Everyone to All
Tested on CODE by targeting the various groups and making sure the correct banner was displayed
=> Update to target all enum

packages/modules/src/modules/banners/designableBanner/DesignableBanner.tsx, packages/modules/src/modules/banners/designableBanner/components/DesignableBannerCtas.tsx, packages/modules/src/modules/banners/designableBanner/components/DesignableBannerReminder.tsx, packages/modules/src/modules/banners/designableBanner/components/DesignableBannerReminderSignedOut.tsx, packages/modules/src/modules/banners/designableBanner/stories/DesignableBanner.stories.tsx
Re-tools the new remind me later functionality to use the RRCP configuration options for the secondary CTA. This allows for the link colour and bg/border/text colours of the submit button on the reminder for to be adjusted in RRCP. Also adjusts the appearance of the CTAs on mobile breakpoints to be inline with the CTA under the choice cards
Have tweaked the stories to display the new feature by passing in the props related to RRCP data instead of tracking data so that storybook can demonstrate all changes in this PR
=> Configurable remind me later

packages/server/src/lib/history.test.ts, packages/server/src/lib/history.ts, packages/server/src/tests/epics/momentumTest.test.ts, packages/server/src/tests/epics/momentumTest.ts
I've refactored our logic so we include weeks missing from the article history targeting by calling getWeeksInWindow 3 times, doing this as a PR into our branch for better visibility
=> Momentum Test Changes

packages/server/src/lib/history.test.ts, packages/server/src/lib/history.ts, packages/server/src/tests/epics/epicSelection.ts, packages/server/src/tests/epics/momentumTest.test.ts, packages/server/src/tests/epics/momentumTest.ts
**Co-authored by** : Andrew Howe-Ely. and Lakshmi Pillai 
This is the first PR with the changes for Article Count: Momentum test
Here we are adding a new filter to epicSelection to show the **momentum epic**  to user who have increased engagement in last three months.The different categories are defined by D&I  [ here ](https://docs.google.com/spreadsheets/d/1XgSXBiE_moxCW9ka37uENW0KltLGUEQfHNaqQ-8-yRA/edit#gid=0)
[Trello card](https://trello.com/c/TddHzNCk/261-article-count-momentum-test-m)
Tested by API to /epic with constructed WeeklyArticleHistory data  and defining an epic with hard coded test name "MOMENTUM_EPIC" .
=> Momentum epic selection 

packages/dotcom/.changeset/thirty-eels-enjoy.md, packages/shared/src/lib/history.ts
Adding 'tone/recipes' to the list of tags that are used for article count
=> Add recipes tag to the list of tags in WeeklyArticleHistory

.github/workflows/dotcom-components.yml
Remove the line that excludes Dependabot PRs from running the build check Github action. 
Currently Dependabot PRs skip the build check, so they do not get unit tested and cannot be deployed to test on riff-raff.
=> Remove dependabot exception from build workflow

packages/dotcom/.changeset/mean-carrots-kiss.md, packages/dotcom/tsconfig.json, packages/modules/package.json, packages/modules/src/modules/shared/ModuleWrapper.tsx, packages/modules/src/types.ts, packages/modules/tsconfig.json, packages/shared/src/types/props/banner.ts, packages/shared/src/types/props/epic.ts, packages/shared/src/types/props/header.ts, yarn.lock
- updates the `moduleResolution` in `@guardian/support-dotcom-components` to use `"bundler"`
- updates imports to use the correct path for emotion's JSX type which this change enforces
- bumps `@guardian/source-react-components` to v23.0.1
=> use `"moduleResolution": "bundler”` in TypeScript

package.json, packages/dotcom/.changeset/good-spoons-stare.md, packages/dotcom/package.json, yarn.lock
Use the correct version of Zod in dev dependencies of `dotcom` as is in the peer dependencies (this was a typo in #1107). 
Also add Zod as a dev dependency of the mono `package.json`. This is to fix a warning that `@guardian/support-dotcom-components` has an unmet peer dependency while running `yarn install` from the root of the project.
Run `yarn install` and do not see warning about zod.
Before
After
=> Fix zod dev dependency

packages/server/src/api/epicRouter.ts, packages/server/src/lib/history.test.ts, packages/server/src/lib/history.ts, packages/server/src/tests/epics/epicSelection.test.ts, packages/shared/src/types/abTests/shared.ts
Reverts guardian/support-dotcom-components#1127
It's causing an article count of 0 to be returned, so let's revert while we investigate -
=> Revert "Changes to allow multiple tags"

packages/server/src/api/epicRouter.ts, packages/server/src/lib/history.test.ts, packages/server/src/lib/history.ts, packages/server/src/tests/epics/epicSelection.test.ts, packages/shared/src/types/abTests/shared.ts
Reverts guardian/support-dotcom-components#1132
This is to   allow multiple tags in SDC article count logic.
These are the same changes as in  #1127  +the bug fix for article count in forTargetedWeek getting 0
=> Bug fix for article count in forTargetedWeeks and changes to allow multiple tags 

packages/server/src/tests/epics/momentumTest.ts
Update the momentum test filter to include medium engagement (i.e. jumped 3 categories). 
So far the test has had very few impressions and conversions, this would open it up to a wider audience who have still increased their reading of articles month on month.
More impressions in the pageview datalake table and AB test dashboard
=> Momentum Epic: update test to include medium increases

packages/dotcom/.changeset/curvy-jokes-boil.md, packages/shared/src/types/targeting/banner.ts, packages/shared/src/types/targeting/shared.ts
Adds a new schema and type for the Abandoned Basket object, and adds it to the banner payload Type. This will be used in DCR when creating the payload to send to the SDC API.
The schema is a duplicate of the one in [support-frontend](https://github.com/guardian/support-frontend/blob/fc67babcbcb729a519c5d24ae1377b7e1816c490/support-frontend/assets/helpers/storage/abandonedBasketCookies.ts#L11)
[Trello](https://trello.com/c/HK9pkXd5/414-abandoned-basket-send-cookie-data-to-api)
Created the `/dist` folder with the new property `abandonedBasket` of `BannerPayload`, manually copied into DCR `node_modules` and can see `abandonedBasket` is present. 
I'm not sure how to test more thoroughly besides publishing a new version and consuming it in DCR
=> Add abandoned basket to banner payload type

packages/dotcom/.changeset/lucky-pugs-yell.md, packages/dotcom/src/index.ts
Adds `abandonedBasketSchema` to the `index.ts` exports, in order to be used from the npm package. Exporting it from its own file means it cannot be used downstream, only its type. In other words we have to export it as javascript
Tested locally with `pnpm link`
=> Add export for abandonedBasketSchema

packages/server/src/lib/history.ts
Currently only epics can have `tagIds` set in the `articlesViewedSettings` targeting config.
There is a bug where if `tagIds` is defined but empty, the calculated article count is 0.
This means that newer epic tests (ones with `tagIds` set) are not targeting users by article count.
=> Fix article count targeting

packages/server/src/lib/ab.ts, packages/server/src/tests/epics/epicSelection.test.ts, packages/server/src/tests/epics/epicSelection.ts
We're going to run an AB test which compares two ways of assigning browsers to variants within an AB test:
1. sticky variants - a browser stays in the same variant for the lifetime of a test (existing behaviour, using mvt cookie)
2. non-sticky variants - variant is selected randomly on each pageview
We're doing this by creating two identical AB tests in the Epic tool:
- `2024-05-29_STICKY_VARIANTS`
- `2024-05-29_NON_STICKY_VARIANTS`
=> Compare sticky vs non-sticky variants

packages/server/src/tests/epics/epicSelection.test.ts, packages/server/src/tests/epics/epicSelection.ts
by convention we add e.g. `__UK` to the name of a test, if we want to target slightly different copy at different regions, but group them together in a single AB test.
=> Enable suffix in sticky variant test names

packages/server/src/api/ampEpicRouter.ts
Adds a new state to amp-state which checks if the URL is support site.  If not, sets the state to true which is then picked up in the Epic.amp.tsx in DCR and used to hide the payment icons.
The epic is occasionally used for email sign up and similar where the payment cards are not relevant.
co-authored-by @andrewHEguardian 
[Trello card](https://trello.com/c/bf3uoki5) 
Related to PR in dotcom-rendering - [PR11476](https://github.com/guardian/dotcom-rendering/pull/11476)
This PR should be merged first.
In RRCP, change the URL in the epic from support.theguardian.com to www.theguardian.com and view the amp epic.
=> Hide Payment Icons when not support url

packages/server/src/api/ampEpicRouter.ts, packages/server/src/tests/amp/ampEpicModels.ts, packages/server/src/tests/amp/ampEpicSelection.ts
co-authored-by: @andrewHEguardian 
In conjunction with [support-admin-console PR598](https://github.com/guardian/support-admin-console/pull/598), this change hides the secondary button which is used as a support reminder to toggle the reminder element of the epic when the appropriate change is made in RRCP for Amp Epics.
NOTE: [support-admin-console PR598](https://github.com/guardian/support-admin-console/pull/598) needs to be merged first.
This change re-uses existing code from Epics.
We created a new value in the AmpEpicModel for secondaryCta.  It is set to 'undefined' if the secondary button in RRCP for the AMP Epic Test is set to 'None' and 'SecondaryCta' type if the RRCP dropdown is set to 'Contribution Reminder'. 
We use this to hide the secondaryCta button when the value is …
=> Use secondaryCta existence to show or hide the reminder CTA for amp epics

packages/dotcom/.changeset/strange-eyes-tease.md, packages/modules/src/modules/banners/localStorage.ts, packages/server/src/api/bannerRouter.ts, packages/server/src/lib/dates.ts, packages/server/src/lib/targeting.ts, packages/server/src/tests/banners/abandonedBasketTests.ts, packages/server/src/tests/banners/bannerSelection.test.ts, packages/server/src/tests/banners/bannerSelection.ts, packages/server/src/tests/banners/bannerTests.ts, packages/server/src/tests/banners/channelBannerTests.ts, packages/shared/src/types/props/banner.ts, packages/shared/src/types/targeting/banner.ts
Adds selection logic for the abandoned basket banner based on the cookie data sent in the request. Also adds a new channel called 'abandonedBasket', similar to sign in prompt tests. Adds one hardcoded test, copy TBC. Returns the abandonedBasket data in the response to be used in the client to generate the CTA url.
Send a request to `/banner`. If the request has `abandonedBasket` property and not `abandonedBasketLastClosedAt` within the last 24 hours - the response should be the "ABANDONED_BASKET" test. Otherwise it should return any other test.
=> Add abandoned basket banner channel selection

packages/modules/src/modules/banners/common/BannerWrapper.tsx, packages/shared/src/lib/tracking.test.ts, packages/shared/src/lib/tracking.ts
Add params to the support URL if the banner channel is abandoned basket. This is applicable for contributions and supporter plus products only.
(Locally)
Build the modules. Turn the abandoned banner hardcoded test from 'Draft' to 'Live'. Use `showMeTheBanner` in DCR - click the CTA and the URL should have the correct params.
The banner with correct CTA URL
=> Abandoned Basket: Create URL to return to checkout

packages/server/src/tests/epics/epicSelection.ts
While this is still experimental we're just using the name to enable non-sticky variants.
We're planning on using this for liveblog experiments
=> Update NON_STICKY test name check

packages/modules/src/modules/banners/designableBanner/components/DesignableBannerHeader.tsx
We're short on space on the mobile banner. This PR reduces the margin under the header on mobile only
=> Reduce banner header margin

packages/server/src/tests/banners/abandonedBasketTests.ts
Add finalised copy for abandoned basket banner variants.
- Add cookie to browser by visiting https://support.theguardian.com/uk/contribute#ab-abandonedBasket=variant
- `showMeTheBanner`
- See abandoned basket banner
v1
v2
=> Add copy for abandoned basket banner variants

packages/dotcom/.changeset/gorgeous-bulldogs-fix.md, packages/shared/src/types/props/epic.ts, packages/shared/src/types/props/shared.ts
aligns the newsletter sign up component in the epic.props and updates the SDC version
Released onto Code and triggered an Epic on an article to make sure that they still work as expected.
=> Live Blog Epic - update newsletter sign up props

packages/modules/src/modules/banners/designableBanner/DesignableBanner.tsx
Adds detection for the ios Safari app banner, and hides the choice cards if so (and send an ophan event).
When the RRCP banner is at `max-height: 90vh` and the ios Safari app banner is present the close button becomes blocked.
[Trello](https://trello.com/c/EnnzXAHB/510-make-rrcp-banner-smaller-if-safari-app-banner-shows)
We tested in storybook by setting the window.innerHeight to a smaller value in the storybook code. (ie added `window.innerHeight = 900;` to `DesignableBanner.stories.tsx`
We'll test in `CODE` to see that the banner renders as normal.
But we'll have to test in prod on an iPhone to check that this actually works
-   [ ] [Navigable with …
=> Hide choice cards when we think ios app banner is present

packages/modules/src/modules/banners/designableBanner/DesignableBanner.tsx
We're now hiding the choice cards if the safari "open in app" banner is detected.
However, the other CTA also fails to render.
Fixed -
=> Fix CTA on mobile safari

packages/dotcom/.changeset/fast-students-yawn.md, packages/shared/src/types/props/epic.ts
Changing the newsletter model back to what it was originally. The thought was we would be able to pass text through to DCR and have the button copy customisable but it's come to light that this isn't possible, and the change to the variable is not needed.
This remains as a safe change as it isn't being used.
-   [ ] [The change doesn't use only colour to convey …
=> New minor SDC version 

packages/modules/src/modules/banners/designableBanner/DesignableBanner.tsx
We've successfully tested hiding the choice cards if the safari "open in app" banner is present.
But for now we want to keep showing the choice cards. It's possible we'll bring this back later
=> Show choice cards if ios app banner present

packages/server/src/tests/banners/abandonedBasketTests.ts
Changes the copy in Abandoned basket test. "finalising" was the wrong spelling for the US, so we sidestepped by changing it to something else.
=> Abandoned basket: update copy

packages/dotcom/.changeset/nervous-timers-travel.md, packages/shared/src/types/props/epic.ts
We're changing our approach to the newsletter signup in the epic. DCR now has a component into which we can pass the `newsletterId`
=> Update newsletter signup fields

packages/modules/package.json, packages/server/src/bandit/banditData.ts, packages/server/src/tests/amp/ampEpicModels.ts, packages/shared/src/lib/geolocation.ts, packages/shared/src/types/abTests/banner.ts, packages/shared/src/types/abTests/epic.ts, packages/shared/src/types/abTests/header.ts, packages/shared/src/types/abTests/shared.ts, packages/shared/src/types/props/banner.ts, packages/shared/src/types/props/design.ts, packages/shared/src/types/props/epic.ts, packages/shared/src/types/props/header.ts, packages/shared/src/types/props/shared.ts, packages/shared/src/types/purchaseInfo.ts, packages/shared/src/types/targeting/shared.ts, yarn.lock
Change Zod wildcard imports from `import * as z from 'zod'` to `import { z } from 'zod'`, and bump `@rollup/plugin-commonjs`. 
Importing with the wildcard is not standard and draws attention in PRs, but isn't really a problem. However previously if you did `import {z}` - as your IDE autocomplete will probably suggest - you will see a runtime error in DCR and support components won't load ([see previous fix](https://github.com/guardian/support-dotcom-components/commit/6547348113888f9d85241ef7029d9e45dd90dcc5)).
The error message is not very helpful "Cannot read properties of undefined (reading 'object')". So in DCR I logged the error's stacktrace and saw it came from a rollup function with this error message ([stackoverflow](https://stackoverflow.com/questions/63691616/how-to-track-down-dyn …
=> Fix zod wildcard imports and bump rollup commonJS

packages/modules/src/modules/banners/designableBanner/components/DesignableBannerArticleCount.tsx
The Article Count Opt out link options were not visible for the readers with more than 50 article counts on the banners
=> Fix Article Count Opt Out on banners for top readers

cdk/lib/__snapshots__/dotcom-components.test.ts.snap, cdk/lib/dotcom-components.ts
We already have autoscaling, but let's start with 6 instances instead of the normal 3
2019 election web traffic -
=> Scale up for election

packages/modules/package.json, yarn.lock
Similar to https://github.com/guardian/braze-components/pull/500
Removes one of the paths causing us to pull in the `ip` package, which currently has an unpatchable vulnerability.
Tested in CODE
=> Upgrade rollup-plugin-filesize

packages/shared/src/lib/geolocation.ts
Fix the issue of Banner CTAs for Guardian Weekly returning a 404 error
An issue occurred while setting up a banner test and using links, [like this one](https://support.theguardian.com/subscribe/weekly/checkout?threeTierCreateSupporterPlusSubscription=true&period=Monthly&promoCode=3TIER_WEEKLY_UK_MONTHLY_V2), to the second step of the checkout, giving a 404 error when clicking through on the banner.
On investigating , we understood that clicking the Live /Web preview in RRCP appends the region code to the url entered in the Button Destination box in the RRCP.
we have a check in support site as part of enabling/ disabling threeTierCheckout to see if window.location.pathname starts with '/subscribe/weekly/checkout' .That check fails as in this case it is pathname comes as …
=> Fix the issue of region getting appended to GW checkout url on clicking Live preview 

packages/dotcom/.changeset/plenty-carrots-melt.md, packages/shared/src/lib/history.ts
Add new tag for investigation to the list of tags we track in WeeklyArticleHistory
=> Add new tag for investigation

packages/dotcom/.changeset/short-stingrays-juggle.md, packages/dotcom/src/index.ts, packages/dotcom/src/types.ts
We're moving the banner components over to DCR. [Draft PR here](https://github.com/guardian/dotcom-rendering/pull/12130).
To enable this we need to share a few things with DCR via the npm package.
=> Exports for banner migration to DCR

packages/server/src/utils/logging.ts
The server stopped sending logs to kibana since the [storybook upgrade](https://github.com/guardian/support-dotcom-components/pull/1201).
This is because the local log file no longer has the right permissions.
This must be the result of an update to the `log4js` dependency, which has tightened up permissions.
We can fix this by using the [file mode](https://nodejs.org/dist/latest-v12.x/docs/api/fs.html#fs_file_modes) parameter in log4js.
=> Fix log file permission

packages/dotcom/.changeset/good-chefs-marry.md, packages/shared/src/types/props/shared.ts
Update to the ticker model to have the ticker styling settings. This is a new addition from the source-development -kitchen which will allow for the ticker config to be customisable 
tested on code to make sure it hasn't broken anything
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colou …
=> Update to ticker model

packages/shared/src/lib/geolocation.test.ts, packages/shared/src/lib/geolocation.ts
Adds the URL `/checkout` to the `addRegionIdToSupportUrl`.
This needs to be done before we can merge https://github.com/guardian/dotcom-rendering/pull/12403 that is moving from the generic checkout (`/contribute/checkout`) to the generic checkout (`/checkout`).
Tests are provided in the test suite.
[This is used here in DCR](https://github.com/guardian/dotcom-rendering/blob/e2511167d3e3ca4ae83fd9f5e04f36bfa0c22b07/dotcom-rendering/src/components/marketing/lib/tracking.ts#L173).
We unblock the above mentioned PR.
This is additive so should be good to go.
=> feat: add checkout to addRegionIdToSupportUrl

.github/workflows/dotcom-components.yml
This was broken by the recent removal of yarn workspaces.
The workflow still had the old path.
=> Fix release workflow

package.json, yarn.lock
This dependency isn't actually used, and is pulling in a vulnerable version of `path-to-regexp`
=> Remove fetch-mock dependency

src/server/api/ampEpicRouter.ts, src/server/lib/tracking.ts
Currently we cannot add a querystring to the url in the RRCP. This is because SDC always adds another `?` onto it, so we get e.g.
`https://support.theguardian.com/contribute?promoCode=OCT_DISCOUNT_50_3_MONTHS?INTCMP=AMP__50_PERCENT__CONTROL&acquisitionData=...`
=> Support querystring in AMP epic

tsconfig.json
This change doesn't affect the server or npm package build. But intellij was getting confused about imports!
https://www.typescriptlang.org/tsconfig/#moduleResolution
=> Set moduleResolution to node

src/server/tests/banners/bannerSelection.test.ts, src/server/tests/banners/bannerSelection.ts, src/shared/types/abTests/banner.ts
Associated SAC change: https://github.com/guardian/support-admin-console/pull/636
Marketing want the ability to override the channel-wide deploy schedule.
For example: channel 2 deploys weekly, but they'd like to show an app install banner (for mobile users) every 24 hours.
The solution implemented here is to add a `deploySchedule` to the `BannerTest` model, to allow Marketing users to override the channel-wide deploy schedule. When set, it allows them to set the number of days between deploys per user. This uses the user's `lastClosedAt` timestamp to decide when to next deploy the banner.
=> Add deploySchedule to banner tests

package.json
We recently migrated to pnpm.
I've gone with the same version as DCR: https://github.com/guardian/dotcom-rendering/blob/main/package.json#L33C1-L33C34
=> set packageManager

src/server/api/bannerRouter.ts, src/server/bandit/banditData.ts, src/server/bandit/banditSelection.test.ts, src/server/factories/test.ts, src/server/lib/ab.test.ts, src/server/lib/targetingTesting.test.ts, src/server/server.ts, src/server/tests/amp/ampEpicSelection.test.ts, src/server/tests/banners/abandonedBasketTests.ts, src/server/tests/banners/bannerSelection.test.ts, src/server/tests/banners/bannerSelection.ts, src/server/tests/banners/signInPromptTests.ts, src/server/tests/epics/epicSelection.test.ts, src/server/tests/epics/epicTests.ts, src/server/tests/epics/fallback.ts, src/server/tests/epics/momentumTest.test.ts, src/server/tests/headers/headerSelection.test.ts, src/server/tests/headers/headerSelection.ts, src/server/tests/store.ts, src/shared/types/abTests/shared.ts, src/shared/types/props/banner.ts
Changes the banner variant selection logic to use the `methodologies` field, which enables bandit testing. This reuses the functionality used for epics.
Also fixes the fetching of data from the bandit table. It needs to [prefix the test name with the channel name](https://github.com/guardian/support-analytics/blob/main/bandit/src/query-lambda/dynamo.ts#L47).
In order to enable this, I've added the `channel` field to the `Test` model. This field is always present in the Dynamodb tests table (it's the partition key), so it's safe to make it mandatory.
=> Enable bandit testing on banners

src/server/bandit/banditData.ts
With this change, it will require 6 hours of data before the bandit strategy kicks in.
This means variants will be selected randomly until then, i.e. "pure exploration"
=> Minimum sample count for bandits

.changeset/cool-jeans-raise.md, .changeset/proud-ties-learn.md, README.md, src/server/factories/bannerDesign.ts, src/shared/types/props/design.ts
Adds an optional font size to the design model which can be picked up by DCR. This allows us to create a tiny banner headline size for banners with no copy.
[Trello ticket](https://trello.com/c/RKgNkcgw)
?TBC
The ability to add a tiny banner with a headline size of 17px and medium font-weight.
Added as optional at this point so that we have time to re-save all banners to pick up the default heading size before potentially making it a compulsory field later.
=> Adds heading size to design model

src/server/bandit/banditData.ts, src/server/lib/ab.test.ts, src/server/lib/ab.ts, src/shared/types/abTests/shared.ts
A [previous PR](https://github.com/guardian/support-dotcom-components/pull/1236) introduced the ability to configure more than 1 methodology per message test. E.g. AB test vs Bandit test.
If more than one methodology is configured then the the audience is split evenly between the methodologies. Each methodology is tracked separately with a different test name.
We haven't used this yet as it's not quite ready and it's not available in the RRCP tools.
This PR modifies the logic a little.
Instead of SDC having to generate a test name for each methodology, we instead add a `testName` field to the methodology model, so that the RRCP can define the names for tracking.
This test name is used in two ways:
1. for tracking views/acquisitions
2. for fetching sample data for the bandit
=> Allow methodologies to configure the test name

cdk/lib/__snapshots__/dotcom-components.test.ts.snap, cdk/lib/dotcom-components.ts, src/server/lib/superMode.ts
This PR is to use new super-mode-calculator tables after Super Mode BigQuery migration and the modification of the related query.
Tested in CODE
=> Point to new super-mode-calculator tables after Super Mode BigQuery migration

package.json, pnpm-lock.yaml
snyk + dependabot have flagged the `path-to-regexp` dependency, which comes via express.
https://security.snyk.io/vuln/SNYK-JS-PATHTOREGEXP-8482416
This update to express resolves this, by pulling in `path-to-regexp` v0.1.12
=> Bump express

src/server/factories/targeting.ts, src/server/lib/dates.test.ts, src/server/lib/dates.ts, src/server/tests/epics/epicSelection.test.ts, src/server/tests/epics/epicSelection.ts, src/server/tests/epics/momentumTest.test.ts, src/shared/types/targeting/banner.ts, src/shared/types/targeting/epic.ts, src/shared/types/targeting/header.ts
The `lastOneOffContributionDate` and `isRecurringContributor` are no longer required in the targeting data, we should just use `showSupportMessaging` instead.
This PR removes them so that we can stop sending them from DCR.
=> Remove lastOneOffContributionDate and isRecurringContributor from targeting data

src/server/api/epicRouter.ts, src/server/middleware/logging.ts
To help investigate a drop in super mode epics.
If an epic is being returned to the client then a new boolean field is added to the log, `epicSuperMode`.
We can then compare this data against the pageview table in bigquery to see if there's a discrepency.
From kibana:
=> Log epicSuperMode

src/server/roulette/rouletteSelection.test.ts, src/server/roulette/rouletteSelection.ts
Currently the "roulette" selection method doesn't work if there is not yet any data. This is because the means for the variants will be 0. If this is the case then it should randomly select a variant until there is enough data.
In the current implementation, no variant is ever returned when users are put into the test.
=> Fix roulette

package.json, pnpm-lock.yaml, src/server/api/epicRouter.ts, src/server/middleware/errorHandling.ts
Currently the error handling middleware just logs the error message.
For example, we had the following error:
`Something went wrong: Cannot read properties of undefined (reading 'mvtId')`
From this we cannot see which endpoint this was, or what the payload was. So it’s hard to investigate further.
This PR changes the `errorHandling` middleware to log an object with:
- the path
- error message
- stack trace
- request body
I've also removed the error message from the response to the client - just a 500 is enough.
E.g. from kibana -
=> Better error logging

src/server/api/auxiaProxyRouter.ts
Previous steps
- https://github.com/guardian/support-dotcom-components/pull/1265
Here we simply upgrade the interface of the Auxia end point, returning a different object, now that we will be expecting the client to process the optional user treatment.
=> Auxia Integration (Part 2)

src/server/api/auxiaProxyRouter.ts
Previous steps
- Part 1: https://github.com/guardian/support-dotcom-components/pull/1265
- Part 3: https://github.com/guardian/support-dotcom-components/pull/1273
Here we 
1. Simplify the payload used to query GetTreatments.
2. Update the URL used to query the treatments. (This is in premise of adding the end point to post to log treatment.)
Sister PR: https://github.com/guardian/dotcom-rendering/pull/13267
=> Auxia Integration (Part 3)

src/server/api/auxiaProxyRouter.ts
Previous steps:
- Part 1: https://github.com/guardian/support-dotcom-components/pull/1265
- Part 2: https://github.com/guardian/support-dotcom-components/pull/1273
- Part 3: https://github.com/guardian/support-dotcom-components/pull/1276
In this part we
1. Refactor the code a little bit to give better names to the types and functions needed for `/auxia/get-treatments`.
2. Implement `/auxia/log-treatment-interaction` 
Test on local:
```
curl "http://127.0.0.1:8082/auxia/log-treatment-interaction" \
-X POST \
-H "Content-Type: application/json" \
-d '{
"treatmentTrackingId": "105889_336_ad5eb464-68c6-4ca1-805c-294375422b48",
"treatmentId": "105889",
"surface": "ARTICLE_PAGE",
"interactionType": "CLICKED",
"interactionTimeMicros": 1667829258250000,
"actionName": "someActionName"
}' …
```
=> Auxia Integration (Part 4)

src/server/api/auxiaProxyRouter.ts
Previously, in Auxia Integration: https://github.com/guardian/support-dotcom-components/pull/1277
In this Part, we upgrade the requirements for the /auxia/get-treatments to require the following attributes: `browserId`, `is_supporter`, `daily_article_count`, `article_identifier`, as requested by Auxia. 
We also upgrade the requirements for the /auxia/log-treatment-interaction call, to add `browserId`.
=> Auxia Integration (Part 5) 

src/server/api/auxiaProxyRouter.ts
Previously, in Auxia Integration: https://github.com/guardian/support-dotcom-components/pull/1284
As we accidentally discovered here https://github.com/guardian/dotcom-rendering/pull/13335 , Auxia's answers may be incomplete, for instance when the client submitted incorrect data. Here we address that problem.
With this change we now have 
```
curl "http://127.0.0.1:8082/auxia/get-treatments" \
-X POST \
-H "Content-Type: application/json" \
-d '{
"browserId": "2598326e-7c",
"is_supporter" : true,
"daily_article_count": 12,
"article_identifier": "www.theguardian.com/us-news/2025/feb/06/trump-sanction-icc"
}'
{"status":false}
```  
and 
```
curl "http://127.0.0.1:8082/auxia/get-treatments" \
-X POST \
-H "Content-Type: application/json" \
-d '{
"browserId": "2598326e7c",
"is_supporter" : …
```
=> Auxia Integration (Part 5): gracefully handle incomplete Auxia answers

src/server/api/auxiaProxyRouter.ts
Here:
1. Prepare for the distinction between Auxia PROD and Auxia CODE while talking to the Auxia API. 
2. Also we never needed `profile_id`. 
3. To mirror the case of /auxia/get-treatments, we use a boolean for status in /auxia/log-treatment-interaction. (No change needed in DCR, we don't actually consume that answer)
=> auxia experiment: prepare for the distinction between stages

src/server/api/auxiaProxyRouter.ts
Here we require an additional attribute in the payload of the auxia queries and perform special handling in case the reader had non consented to their personal data being used. In this latter case, re do not connect to the Auxia API and return the GU template.
=> auxia experiment: Use default GU data in case of non consenting reader

src/server/api/auxiaProxyRouter.ts
Use the languageLocale of the current edition for the Auxia GetTreatments API call. and decommission `privacyButtonName`. We also correct the `guDefaultShouldShowTheGate` boolean which was the wrong way round.
sister changes: 
- https://github.com/guardian/dotcom-rendering/pull/13396
- https://github.com/guardian/dotcom-rendering/pull/13398
=> auxia experiment: set editionId and decommission privacyButtonName

src/server/server.ts
This corrects a problem that has existed for a while but only became apparent last couple of days as we experienced 500 errors: the position of error handling middleware matter in Express 🙃
https://stackoverflow.com/questions/72227296/does-the-position-of-error-handling-middleware-matter-in-express
Note that this also correct any problems with might have had with `GutterRouter`
=> auxia experiment: prevent 500 errors from bringing down the app

src/server/server.ts
Since rolling out the auxia experiment we've seen spikes in 502s from the LB. This indicates connection problems with the server.
This is a small change to see if it relates to the connection keep-alive timeout.
https://repost.aws/knowledge-center/elb-alb-troubleshoot-502-errors
> The load balancer receives a request and forwards it to the target. The target receives the request and starts to process it, but closes the connection to the load balancer too early. This usually occurs when the duration of the keep-alive timeout for the target is shorter than the idle timeout value of the load balancer. Make sure that the duration of the keep-alive timeout is greater than the idle timeout value.
The LB default idle timeout is 60 seconds, and the node.js default keep-alive is 5 seconds.
=> Set keepAliveTimeout

.changeset/early-cups-fetch.md, src/dotcom/types.ts, src/server/api/gutterRouter.ts, src/server/lib/tracking.ts
A set of small changes that help to clarify and add missing type safety. 
Added a missed GutterPayload listing to the dotcom types for the package.  If the GutterPayload in shared/types/targeting is ever moved, this will ensure DCR can still find it. It will need to be updated in DCR too.
Added type safety for the campaign code.
Deploy to CODE and run DCR against it.
=> Clarifications and fixes

src/server/middleware/logging.ts
Adds a `responseTimeMs` field to the logging (which ends up in kibana):
For non-auxia requests this should be very small because no additional network calls are made. But for the auxia endpoints it will be much longer.
Note that this is the time taken once the server begins handling a request, but does not account for delays either side.
Tested in CODE:
E.g. `/header` request:
```{"stack":"support","app":"dotcom-components","stage":"CODE","@timestamp":"2025-02-27T09:27:02.208Z","level":"INFO","level_value":20000,"status":200,"method":"POST","path":"/header","responseTimeMs":"2"}```
E.g. `/auxia/get-treatments` request:
```{"stack":"support","app":"dotcom-components","stage":"CODE","@timestamp":"2025-02-27T09:25:50.021Z","level":"INFO","level_value":20000,"status":200,"method":"POST","path" …
```
=> log response time

src/server/middleware/logging.ts
Currently this is being logged as a string (because `toFixed` returns a string!).
In order to do aggregations in kibana it needs to be a number
=> Log response time as number

src/server/middleware/logging.ts
I previously sent the `responseTimeMs` field as a string by mistake.
Kibana now insists that this field is a string, even after fixing it in SDC.
Renaming the field will solve this
=> Rename response time field

.changeset/gorgeous-days-give.md, src/server/api/bannerRouter.ts, src/server/api/epicRouter.ts, src/server/api/gutterRouter.ts, src/server/tests/banners/bannerSelection.ts, src/shared/types/targeting/banner.ts, src/shared/types/targeting/epic.ts, src/shared/types/targeting/gutter.ts, src/shared/types/targeting/shared.ts
We need to disable RRCP support messages on pages like [Privacy | The Guardian](https://www.theguardian.com/info/privacy)  like [Privacy | The Guardian](https://www.theguardian.com/info/privacy)
See green section here for full list: https://docs.google.com/spreadsheets/d/1KdwxnOecrV-2j3X-mX_kkvLgupPH8DvBgvEH-D-cRWg/edit?gid=0#gid=0Connect your Google account
[Trello card](https://trello.com/c/xeqIF1aP/944-do-not-show-epic-banner-on-info-pages)
Out of the list we are making this change for the below pageIds
1.  'info/privacy' 
2. 'info/complaints-and-corrections' 
3. 'about'
Tested using Postman
=> Hide epic and banners for info pages

cdk/lib/__snapshots__/dotcom-components.test.ts.snap, cdk/lib/dotcom-components.ts
We've had some short + shart ELB 502 spikes during heavy traffic. Autoscaling has been going up and down.
While we're running the auxia experiment let's maintain 6 instances
=> minimum 6 instances

src/server/api/auxiaProxyRouter.ts, src/server/signin-gate/lib.test.ts, src/server/signin-gate/lib.ts
Making the world a safer place, one test at a time
=> auxia experiment: move functions to lib and give them tests

src/server/api/auxiaProxyRouter.ts, src/server/middleware/logging.ts
We're investigating a discrepency with view counts in Auxia. Views are much higher in our own datalake than on Auxia's side.
This PR adds an `auxiaTreatmentId` field to the logging for both Auxia endpoints, so that we can see counts for:
1. each treatment that is returned by Auxia
2. each treatment view that we report to Auxia
This will show in the logs in Kibana
=> Log auxiaTreatmentId

src/server/api/auxiaProxyRouter.ts, src/server/middleware/logging.ts
We're now seeing an unexpectedly high number of auxia view events.
This change will help us to understand if we're sending duplicate view events
=> Log auxiaTreatmentTrackingId

src/server/roulette/rouletteSelection.test.ts, src/server/roulette/rouletteSelection.ts
Currently if a variant doesn’t get any acquisitions during the initial 6 hour discovery period then its weighting gets stuck at 0 forever.
Instead we can hardcoded a minimum weighting per variant to ensure we always explore all variants, even if their score is very low.
For now we're setting this to a minimum of 10% per variant.
=> minimum weight for roulette sampling

src/server/api/auxiaProxyRouter.ts, src/server/signin-gate/lib.test.ts, src/server/signin-gate/lib.ts
This is the follow up the DCR change ( https://github.com/guardian/dotcom-rendering/pull/13715 ), to add `country_key` as a new contextual attribute of the auxia GetTreatments payload.
=> auxia: add country information

src/server/api/gutterRouter.ts
Separating out the gutter component into its own Ophan Component Type (ACQUISITIONS_GUTTER) will allow us to more easily separate the data for the new Gutter component, add it to Grafana charts and add alerts to notify us if acquisitions from the component drop below a baseline.
This change only affects the server.
- [ophan-data-lake PR8229](https://github.com/guardian/ophan-data-lake/pull/8229)
- [ophan PR6849](https://github.com/guardian/ophan/pull/6849)
- [csnx PR2003](https://github.com/guardian/csnx/pull/2003)
- [SDC PR1316](https://github.com/guardian/support-dotcom-components/pull/1316)
Deploy to CODE and test against CODE DCR - open the network tab in dev tools and check if the new component type is being passed in the Ophan Component Event Payload.
Click on the CTA and check that …
=> Move to using new Ophan Component Type for Gutters

eslint.config.mjs, src/server/lib/fetchTickerData.ts, src/server/middleware/errorHandling.ts, src/server/tests/banners/bannerDeployTimes.ts, src/shared/types/targeting/shared.ts
This re-enables the eslint rule `@eslint-community/eslint-comments/require-description` to the default option recommended in @guardian/eslint-config and adds a comment to the 4 instances of rule override comments where 'any' is used.
Also @typescript-eslint/ban-types was removed without changes required - thought to be deprecated.
Reinstated after this [PR](https://github.com/guardian/support-dotcom-components/pull/1316) which switched off many of the rules that were not able to be fixed automatically and relates to [this Trello card](https://trello.com/c/aqo99v2Y) which we added to ensure we followed up on these rules.
run `pnpm lint` and you should get no linting errors.
=> Fix  eslint-comments/require-description rule

eslint.config.mjs, src/shared/types/props/epic.ts
One interface contains Function rather than a function signature. On checking what that is in DCR, it appears to be an empty param returning void.
Reinstated after this [PR which](https://github.com/guardian/support-dotcom-components/pull/1316) switched off many of the rules that were not able to be fixed automatically and relates to [this Trello card](https://trello.com/c/lc8lG7Zj) which we added to ensure we followed up on these rules.
run `pnpm lint` and you should get no linting errors.
Deploy to code and ensure you can use the secondary CTA to open/close the reminders section of Epics.
=> Reinstate typescript eslint no unsafe function type rule

src/server/selection/banditData.ts, src/server/selection/epsilonGreedySelection.test.ts, src/server/selection/epsilonGreedySelection.ts, src/server/selection/rouletteSelection.test.ts, src/server/selection/rouletteSelection.ts
The bandit data is fetched and cached regularly.
Originally this data was only used by the epsilon-greedy algorithm, which only requires the best variants (those with the highest mean). And so for efficiency the model just had a `bestVariants` array:
```
export interface BanditData {
testName: string;
bestVariants: BanditVariantData[]; // will contain more than 1 variant if there is a tie
}
```
We later added the "roulette" algorithm, which requires the means for all variants, so we added a `variants` field to the model:
```
export interface BanditData {
testName: string;
bestVariants: BanditVariantData[]; // will contain more than 1 variant if there is a tie
variants: BanditVariantData[];
}
```
This PR simplifies the model to:
```
export interface BanditData {
testName: string; …
```
=> Simplify BanditData model

src/server/lib/fetchTickerData.ts, src/server/tests/amp/ampEpicSelection.test.ts, src/shared/types/props/shared.ts
The ticker-calculator [now produces](https://github.com/guardian/contributions-ticker-calculator/pull/86) a `global` ticker value, which we'll be using in an upcoming campaign.
This PR adds this new ticker campaign name so that we can poll the value and serve it to the client.
There will also be a change to support-admin-console to make `global` a valid ticker option.
=> Support 'global' ticker campaign

eslint-suppressions.json, eslint.config.mjs, package.json, pnpm-lock.yaml, src/server/tests/banners/channelBannerTests.test.ts
This is a new way to suppress existing rule failures until they can be fixed while applying the rules to any new code. It means that we don't need to disable rules until we fix failures in existing code. 
This new feature is described in this blog post [https://eslint.org/blog/2025/04/introducing-bulk-suppressions](https://eslint.org/blog/2025/04/introducing-bulk-suppressions). 
It creates a new file called eslint-suppressions.json in the project root which holds the list of existing failures.  This can be pruned over time as they get fixed or the rules change.
It requires the latest version of eslint 9.24.0 so this has also been bumped.
If any rules need to be updated or altered as the team makes decision on them, this can be done in the eslint.config.mjs file and the suppressions file …
=> Bulk suppress existing eslint rule failures

.changeset/fluffy-beers-yawn.md, eslint-suppressions.json, src/dotcom/index.ts, src/server/tests/amp/ampEpicSelection.test.ts, src/server/tests/amp/ampTicker.ts, src/shared/types/props/shared.ts
This PR is to remove endType and countType from TickerSettings as these are no longer used.
This change was made as part of tooling Ticker in landing page tests
This is to support the changes in [SAC PR](https://github.com/guardian/support-admin-console/pull/725)
Deployed the SDC and SAC  branches to CODE and checked the changes in RRCP Preview option.Unable to test in Web preview as we haven't updated DCR yet
=> Update tickerSettings and remove endType and countType

riff-raff.yaml
As we've specified node v22.13.1 in the .nvmrc file, we need to ensure the AMIgo node image matches.
Deploy to CODE
Deploys to CODE successfully, banner, epic and gutter-ask appearing as usual
=> Bump AMIgo bake to match node version in .nvmrc

cdk/lib/__snapshots__/dotcom-components.test.ts.snap, cdk/lib/dotcom-components.ts
A [previous PR](https://github.com/guardian/support-dotcom-components/pull/1338) added memory usage metrics using the cloudwatch agent.
We want to view these memory metrics across the whole autoscaling group over time, as well as per instance.
I've done this using cloudwatch queries:
The current solution is not quite good enough because cloudwatch limits us to 3 hours of data when using queries:
And we cannot break it down further without using cloudwatch queries because the metrics are being grouped by autoscaling group _and_ instance ID:
and instance IDs change all the time with autoscaling/redeploys.
This PR solves this by adding an `aggregation_dimensions` field to aggregate by autoscaling group.
See https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-common …
=> Aggregate memory metrics by ASG

cdk/lib/__snapshots__/dotcom-components.test.ts.snap, cdk/lib/dotcom-components.ts
to show memory used
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/metrics-collected-by-CloudWatch-agent.html
=> Add mem_used metrics

src/server/selection/epsilonGreedySelection.test.ts, src/server/selection/epsilonGreedySelection.ts
Currently if all variants have the same mean then it incorrectly picks the first variant.
It should instead randomly pick from all of the variants in this case.
=> Fix epsilon-greedy when all variants tied

src/server/tests/banners/bannerSelection.ts
Enables any variant with the name including the string BANNER_V2 anywhere in the name to pick up the new choice cards.  This is a temporary fix while we build them as default to allow MRR to use them for an up-coming campaign.
Deploy to code and create a variant with BANNER_V2 in the name - check web preview.
Co-authored-by @tomrf1
=> Adjustment to allow hard coded 3 tier choice cards in new test variant

eslint-suppressions.json, src/server/api/auxiaProxyRouter.ts, src/server/signin-gate/lib.test.ts, src/server/signin-gate/lib.ts
This implement the deny of gate for the specific article identifier `www.theguardian.com/tips`.
Also, today is the day prettier decided to be really pedantic with me about types (see below pictures), so we do a bit of clarification (which is a good thing)
BEFORE:
AFTER:
=> deny /tips from being gated

src/server/lib/choiceCards/defaultChoiceCardSettings.ts
This is to match the existing formatting in DCR where this copy is currently hardcoded:
https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/components/marketing/epics/ThreeTierChoiceCards.tsx#L157
An upcoming PR will render this field as html:
https://github.com/guardian/dotcom-rendering/pull/13935/files#diff-781399bcbe277a36529151badd5c2b6ed23db29cdecd1fe96c25f5f87b50ca07R116
=> Choice cards formatting

docs/server.md, src/server/api/auxiaProxyRouter.ts, src/server/signin-gate/lib.test.ts, src/server/signin-gate/lib.ts
We are now sending mvtId to SDC
- https://github.com/guardian/dotcom-rendering/pull/13938
- https://github.com/guardian/dotcom-rendering/pull/13941
Here we are just implementing the function that is going to ensure invariance of the experiments cohorts as we decommission the old experiment(s) from DCR and hand over total air traffic control to SDC in the next PRs.
=> mvtIdIsAuxiaAudienceShare

src/server/api/auxiaProxyRouter.ts
This is the SDC change that comes with this DCR change: https://github.com/guardian/dotcom-rendering/pull/13944
Part of the progression towards giving SDC control of all gate logic.
=> should_show_legacy_gate_tmp

src/server/lib/choiceCards/choiceCards.ts
Currently the pill copy is not being sent to the client (e.g. "Recommended").
Also, for annual rate plans it should say e.g. "Support £12/annually", but currently it would say "Support £12/annual". We're not currently showing annual choices so it's not a bug yet.
Tested both fixes in CODE -
=> Fix pill and rate plan copy in choice cards

.changeset/small-spies-provide.md, src/server/api/bannerRouter.ts, src/server/api/epicRouter.ts, src/server/lib/choiceCards/choiceCards.test.ts, src/server/lib/choiceCards/choiceCards.ts, src/shared/types/abTests/banner.ts, src/shared/types/abTests/gutter.ts, src/shared/types/abTests/header.ts, src/shared/types/props/epic.ts, src/shared/types/props/gutter.ts, src/shared/types/props/header.ts
Currently if Marketing want to add a promo to a test variant they must add the `promoCode` parameter to the CTA url. This is then used to modify the choice cards to show the promo (if applicable). This is not great UX for Marketing and the choice cards integration feels a bit hacky.
Instead, here we add a `promoCodes` field to the variant models. This field will be used in 2 ways:
- it will be added to the CTA url, as `promoCode` querystring params,
- in the choice cards, to display the discount
This will require a DCR change to add the `promoCode` parameter to the CTA url, client-side.
It will be used on the header + gutter channels, which do not have choice cards.
Note - while the migration to using the new `promoCodes` field is underway, Marketing will not be able to use promos in the …
=> Add promoCodes field to variant models

.changeset/stale-carrots-speak.md, src/shared/types/props/banner.ts
I missed this in the [previous PR](https://github.com/guardian/support-dotcom-components/pull/1373)
Which is a sign that these models should ideally be consolidated in some way
=> Add promoCodes field to banner props model

package.json, pnpm-lock.yaml, src/server/api/epicRouter.ts, src/server/utils/cloudwatch.ts
This implements a batching mechanism for sending metric data to CloudWatch using putMetric
[Trello card](https://trello.com/c/EgcsqIuX/1165-sdc-do-not-send-cloudwatch-metrics-per-client-request)
This PR adds a [throttled](https://lodash.com/docs/4.17.15#throttle) mechanism for sending metrics, because it could get very expensive if we send a request to cloudwatch for each request from the apps. It caches in memory counts for each type of metric, and sends them all together in a single request.
Add console statement and putMetric('bandit-selection-error') at the top of epicRouter .Deployed the branch to CODE and clicked through a few pages with epic.
It triggered the alarm once and didn't get triggered for every event.All the 24 appeared with the same timestamp
=>  Throttle CloudWatch requests

src/server/api/auxiaProxyRouter.ts, src/server/signin-gate/lib.test.ts, src/server/signin-gate/lib.ts
`should_not_serve_mandatory` is introduced to indicate to Auxia when we enforce the condition that any gate they return should not be mandatory (aka: non dismissible). This is the companion PR of: https://github.com/guardian/dotcom-rendering/pull/14177
=> Introduce should_not_serve_mandatory

tsconfig.types.json
The types package build is currently failing with the error:
`Error: src/server/utils/aws.ts(6,14): error TS2742: The inferred type of 'credentials' cannot be named without a reference to '.pnpm/@aws-sdk+types@3.821.0/node_modules/@aws-sdk/types'. This is likely not portable. A type annotation is necessary.`
This has been happening since the [upgrade](https://github.com/guardian/support-dotcom-components/pull/1378) to AWS sdk v3.
Adding the type here is not simple.
However, the `aws.ts` file is only relevant to the server-side code. The solution in this PR is to exclude all server code from the types build.
=> Exclude server code from types build

.changeset/lemon-parrots-notice.md, package.json, pnpm-lock.yaml
Bumps @guardian/ophan-tracker-js to the latest version, 2.3.1. 
This keeps support-dotcom-component version in line with DCR
=> Bump ophan tracker js to latest version 

eslint-suppressions.json, package.json, src/dotcom/requests.ts
This removes the check for the existence of URLSearchParam before calling the constructor.  [URLSearchParams](https://nodejs.org/docs/latest-v22.x/api/url.html#class-urlsearchparams) is a class on the Node global object now therefore this condition was creating a lint error '@typescript-eslint/no-unnecessary-condition'.  It also simplifies the code
This PR also adds a prune-lint-suppressions script to the package JSON file - making it easier to find
Run into CODE and check if web-preview in CODE RRCP for banners, epics, gutters still displays as expected
=> Fix lint no unnecessary conditions in requests.ts

.changeset/nine-colts-compare.md, src/dotcom/requests.ts
Removes an incorrect import of `URLSearchParams` from the `'url'` module.
While bundling the client bundles with Webpack, a warning was being thrown:
```
export 'URLSearchParams' (imported as 'n') was not found in 'url'
```
This happened because `URLSearchParams` is not a named export from `'url'` in environments like the browser. It is available globally in modern JavaScript runtimes, so the import is unnecessary and potentially harmful when bundling for the web.
Removing the import resolves the warning without changing the runtime behavior.
* Run `make dev` and confirm the warning no longer appears during the build.
* Navigate through the affected functionality and confirm there are no regressions.
The Webpack build completes without module resolution warnings and the functionality …
=> fix: use global URLSearchParams

src/server/api/auxiaProxyRouter.ts, src/server/signin-gate/lib.test.ts, src/server/signin-gate/lib.ts
This introduces a refactoring to help understanding sign-in gate behaviour, something that is going to become important in a coming change. 
What we do here is moving from the dichotomy ( dismissible / non dismissible ) or the dichotomy ( mandatory / non mandatory ) to the more natural, and which avoid potentially misleading negations ( dismissible / mandatory ).
Companion DCR PR: https://github.com/guardian/dotcom-rendering/pull/14281
Note that here the only bit we cannot change, but that's ok, is the name of the Auxia extended attribute which will remain `should_not_serve_mandatory`.
=> refactoring: avoid using negatives in sign-in gate's behaviour names

.changeset/swift-oranges-travel.md, src/server/factories/bannerDesign.ts, src/shared/types/props/design.ts
Use automatic cta hover colours
[Trello card](https://trello.com/c/rrkYaudf/1089-banner-design-use-automatic-cta-hover-colours)
Currently in the RRCP banner design tool users have to configure the cta hover colours.
The latest version of source now has automatic hover colours on ctas, based on the main colour. If we use this instead then we can simplify the configuration of banner designs.
=> Remove hover from CTADesign for banners

src/server/api/auxiaProxyRouter.ts
In the case that
1. `body.shouldServeDismissible` is `true` (which at the moment is controlled by `utm_source=newsshowcase`, via `DRC:decideShouldServeDismissible`), and
2. `body.showDefaultGate` is defined (regardless of its value)
Then we serve a non dismissible gate. In other words `body.shouldServeDismissible` takes priority over the fact that `body.showDefaultGate` could possibly have value `mandatory`
=> The case of body.showDefaultGate !== undefined && body.shouldServeDismissible

src/server/api/auxiaProxyRouter.ts, src/server/signin-gate/lib.test.ts, src/server/signin-gate/lib.ts
The following GetTreatments payload should return a gate, but doesn't
.
.
Here we fix that problem by removing an old and incorrect gate control condition. Also this is an opportunity to test `getTreatments` which has never actually been tested 😬
=> Remove conflicting gate control condition

src/server/api/auxiaProxyRouter.ts, src/server/signin-gate/lib.test.ts
Add tests for getTreatments ( follow up of: https://github.com/guardian/support-dotcom-components/pull/1404 )
=> Add tests for getTreatments

src/server/lib/choiceCards/defaultChoiceCardSettings.ts
Update the supporter plus choice card with the following benefits:
Also updated mobile banner get defaulted to the top two bullet points only.
=> feat: update benefits copy for SupporterPlus and shorterChoiceCards

src/server/signin-gate/lib.ts
Prevent sign-in gate for Filter articles. This is the companion PR of DCR's https://github.com/guardian/dotcom-rendering/pull/14422/files
Note that we have a temporary duplication of logic on both system because we are in the middle of a refactoring. The client side code will be decommissioned soon.
=> Prevent sign-in gate for Filter articles

src/shared/lib/history.test.ts
This add timezone information to the fixtures in history.test.ts. This prevent failing tests when the local system is not on UK timezone. 
Co-discovered with @tomrf1 🥇
=> correct history tests

src/server/signin-gate/logic.md
In this change we encode the sign-in gate specs as defined by the business (Giulia). The logic file is going to be where the official specs are encoded and any further business modification of the gate should be reported in in this file in the same PR that implement the change.
The file was built from two diagrams that Pascal drew and that Giulia signed off. Given here for reference.
=> [sign-in gate] logic.md

src/server/api/auxiaProxyRouter.ts, src/server/signin-gate/libPure.ts, src/server/signin-gate/libPureTests/getTreatmentsRequestPayloadToGateType/ireland.test.ts, src/server/signin-gate/libPureTests/getTreatmentsRequestPayloadToGateType/special-cases.test.ts, src/server/signin-gate/libPureTests/getTreatmentsRequestPayloadToGateType/world-without-ireland.test.ts, src/server/signin-gate/libPureTests/hideSupportMessagingHasOverride.test.ts, src/server/signin-gate/libPureTests/isAuxiaAudienceShare.test.ts, src/server/signin-gate/libPureTests/isGuardianAudienceShare.test.ts, src/server/signin-gate/libPureTests/isStaffTestConditionShowDefaultGate.test.ts, src/server/signin-gate/libPureTests/staffTestConditionToDefaultGate.test.ts, src/server/signin-gate/libPureTests/userHasConsented.test.ts, src/server/signin-gate/logic.md, src/server/signin-gate/types.ts
Here we implement a new gate  condition by which we do not show the gate within 30 days of a single contribution events as defined by DCR's cookie `gu_hide_support_messaging`, SDC: GetTreatments payload: `hideSupportMessagingTimestamp`
This applies everywhere except when Auxia has full control of the gate. See logic.md for details.
Companion DCR change: https://github.com/guardian/dotcom-rendering/pull/14462
=> [sing-in gate] Implement hideSupportMessagingHasOverride

src/server/signin-gate/libPure.ts
This is the companion PR of https://github.com/guardian/dotcom-rendering/pull/14507
Here we move to using userTreatment.treatmentType, which takes the two values
- DISMISSABLE_SIGN_IN_GATE
- NONDISMISSIBLE_SIGN_IN_GATE
To be closer to the way Auxia model its data.
=> [auxia] use NONDISMISSIBLE_SIGN_IN_GATE for guMandatoryUserTreatment

.changeset/seven-kiwis-return.md, package.json, pnpm-lock.yaml
Bumps `ophan-tracker-js` to latest version as dotcom-rendering needs this. Sibling dotcom PR here: https://github.com/guardian/dotcom-rendering/pull/14572
=> Bump ophan-tracker-js
